// Images locales issues de l'export Crimpd fourni par l'utilisateur.
export const CLIMBING_IMAGES: Record<string, number> = {
  "Bar Scorpion": require("../../assets/images/climbing/3c3684f42f10_Bar_Scorpion-p.jpg"),
  Bouldering: require("../../assets/images/climbing/4b62353b94e9_Bouldering-p_2023.jpg"),
  "Campus 1-2-3": require("../../assets/images/climbing/86898aa366fe_campus-1-2.jpg"),
  "Campus 1-3-5": require("../../assets/images/climbing/728e960b4aae_campus-1-3.jpg"),
  "Campus 1-3-5-7-9": require("../../assets/images/climbing/728e960b4aae_campus-1-3.jpg"),
  "Campus 1-4-5": require("../../assets/images/climbing/c25cacac5474_campus-1-4.jpg"),
  "Campus 1-4-7": require("../../assets/images/climbing/c25cacac5474_campus-1-4.jpg"),
  "Campus 1-5-7": require("../../assets/images/climbing/e53ba9edc291_campus-1-5.jpg"),
  "Campus 1-5-8": require("../../assets/images/climbing/e53ba9edc291_campus-1-5.jpg"),
  "Campus Latch": require("../../assets/images/climbing/b90782974d1b_latch-1-p.jpg"),
  "Campusing Boulders": require("../../assets/images/climbing/572b3d158fe9_Campusing_Boulders-p_2023.jpg"),
  "Dead Hang - Specific Grip Warm-up": require("../../assets/images/climbing/4157931a04ff_Dead_Hang-Specific_grip_warm_up-p_2023.jpg"),
  "Dead Hang: 10-13mm Edge": require("../../assets/images/climbing/4a21dc47a383_10mmEdges.jpg"),
  "Dead Hang: 10mm Edge": require("../../assets/images/climbing/4a21dc47a383_10mmEdges.jpg"),
  "Dead Hang: 12mm Edge": require("../../assets/images/climbing/045a4a2a3a2b_Small_edges_12mm-p.jpg"),
  "Dead Hang: 20mm Edge": require("../../assets/images/climbing/8ca26d0069d7_Finger_strength_testing_2_arms_half_crimp-p.jpg"),
  "Dead Hang: 6-8mm Edge": require("../../assets/images/climbing/070ca16ac802_6mmEdges.jpg"),
  "Dead Hang: 6mm Edge": require("../../assets/images/climbing/fa98bc5e094c_small_edges_6mm-p.jpg"),
  "Dead Hang: 8mm Edge": require("../../assets/images/climbing/9d26f8df6d3b_small_edges_8_mm-p.jpg"),
  "Dead Hang: Back 3 Half Crimp": require("../../assets/images/climbing/b51620c5c0b3_Varied_grip_back_3-p.jpg"),
  "Dead Hang: Front 3 Half Crimp": require("../../assets/images/climbing/871f08b7f6d7_varied_grip_front_3_half-p.jpg"),
  "Dead Hang: Front 3 Open Drag": require("../../assets/images/climbing/eb4e7b516f33_Varied_grip_front_3_open-p.jpg"),
  "Dead Hang: Half Crimp": require("../../assets/images/climbing/b02ce0ac97ab_Body_weight_deadhang_exercise_shot-p.jpg"),
  "Dead Hang: One-arm": require("../../assets/images/climbing/f5b8274afbce_Dead_Hang_One-arm-p_2023.jpg"),
  "Deadpoint Practice": require("../../assets/images/climbing/71aedd52c5ae_Paradigm-Deadpoint3-p.jpg"),
  "Dynamic Move to Scorpion": require("../../assets/images/climbing/dad8baf90f93_Wall_Scorpion-1-p.jpg"),
  "Dyno Practice": require("../../assets/images/climbing/6e921c4de39a_dyno-p.jpg"),
  "Edge Pick-up": require("../../assets/images/climbing/ae386738d796_edge_half_crimp_close_up_1-p.jpg"),
  "Flexor Curl": require("../../assets/images/climbing/7e1ee72c5c0d_Flexor_Curl-p_2023.jpg"),
  "Floor Scorpion": require("../../assets/images/climbing/e62a157248f4_Floor_Scorpion-p.jpg"),
  "Foot Cut to Scorpion": require("../../assets/images/climbing/dad8baf90f93_Wall_Scorpion-1-p.jpg"),
  "Foot on Campusing": require("../../assets/images/climbing/f317623ae33a_Foot_on_Campusing-p_2023.jpg"),
  "Hands-free Climbing": require("../../assets/images/climbing/987530755d9c_emil-slab2-p.jpg"),
  "Heavy Finger Curls": require("../../assets/images/climbing/c4ab16c87335_heavy_finger_curls.jpg"),
  "Isometric Hang": require("../../assets/images/climbing/12ba47a89643_hangboard_isometric_two-arm-p.jpg"),
  "Isometric Hang: Front 2 Half Crimp": require("../../assets/images/climbing/14baf34fe900_front_two_half_crimp-p.jpg"),
  "Isometric Hang: Front 2 Open": require("../../assets/images/climbing/fc6159f5f1ac_front_two_open-p.jpg"),
  "Isometric Hang: Front 3 Open": require("../../assets/images/climbing/eb4e7b516f33_Varied_grip_front_3_open-p.jpg"),
  "Isometric Hang: Middle 2 Half Crimp": require("../../assets/images/climbing/46585f2787af_middle_two_half_crimp-p.jpg"),
  "Isometric Hang: Middle 2 Open": require("../../assets/images/climbing/125ee58babc7_middle_two_open-p.jpg"),
  "Isometric Hang: Sloper": require("../../assets/images/climbing/93023206cd90_Slopers-Isometric-p.jpg"),
  "Large Edge Scorpion": require("../../assets/images/climbing/4c2357d99384_Large_Edge_Scorpion-p.jpg"),
  "Lattice Circuit": require("../../assets/images/climbing/588502070b02_Lattice_Circuit-p_2023.jpg"),
  "Lock-off & Bump": require("../../assets/images/climbing/c796ffdcb1ce_lock-off1-p.jpg"),
  "Pinch Block": require("../../assets/images/climbing/3d208ce2e03b_pinch-block-close-up.jpg"),
  "Route Climbing": require("../../assets/images/climbing/409116aab126_Climbing-p_2023.jpg"),
  "Small Edge Scorpion": require("../../assets/images/climbing/d17e545e6656_Small_Edge_Scorpion-p.jpg"),
  "Static Move to Scorpion": require("../../assets/images/climbing/426dff687144_Wall_Scorpion-2-p.jpg"),
  "Tension Activations": require("../../assets/images/climbing/e5654b58ceae_Paradigm-Tension_Activations-p.jpg"),
  "Wide Campus 1-2-3": require("../../assets/images/climbing/1654df0f4977_wide_campus-1-2.jpg"),
  "Wide Campus 1-3-5": require("../../assets/images/climbing/c3944681940b_wide_campus-1-3.jpg"),
};
