import type { Muscle } from "./types";

// Exercices atomiques extraits de l'export Crimpd fourni par l'utilisateur.
// Sont exclus : Conditioning & Mobility, le cross-training générique et les
// mouvements d'échauffement non spécifiques à l'escalade.
export type ClimbingExercise = readonly [name: string, muscle: Muscle, equipment: string];

export const CLIMBING_EXERCISES: readonly ClimbingExercise[] = [
  ["Bar Scorpion", "shoulders", "pull-up bar"],
  ["Bouldering", "fullbody", "climbing wall"],
  ["Campus 1-2-3", "back", "campus board"],
  ["Campus 1-3-5", "back", "campus board"],
  ["Campus 1-3-5-7-9", "back", "campus board"],
  ["Campus 1-4-5", "back", "campus board"],
  ["Campus 1-4-7", "back", "campus board"],
  ["Campus 1-5-7", "back", "campus board"],
  ["Campus 1-5-8", "back", "campus board"],
  ["Campus Latch", "back", "campus board"],
  ["Campusing Boulders", "back", "climbing wall"],
  ["Dead Hang - Specific Grip Warm-up", "fingers", "fingerboard"],
  ["Dead Hang: 10-13mm Edge", "fingers", "fingerboard"],
  ["Dead Hang: 10mm Edge", "fingers", "fingerboard"],
  ["Dead Hang: 12mm Edge", "fingers", "fingerboard"],
  ["Dead Hang: 20mm Edge", "fingers", "fingerboard"],
  ["Dead Hang: 6-8mm Edge", "fingers", "fingerboard"],
  ["Dead Hang: 6mm Edge", "fingers", "fingerboard"],
  ["Dead Hang: 8mm Edge", "fingers", "fingerboard"],
  ["Dead Hang: Back 3 Half Crimp", "fingers", "fingerboard"],
  ["Dead Hang: Front 3 Half Crimp", "fingers", "fingerboard"],
  ["Dead Hang: Front 3 Open Drag", "fingers", "fingerboard"],
  ["Dead Hang: Half Crimp", "fingers", "fingerboard"],
  ["Dead Hang: One-arm", "fingers", "fingerboard"],
  ["Deadpoint Practice", "fullbody", "climbing wall"],
  ["Dynamic Move to Scorpion", "fullbody", "climbing wall"],
  ["Dyno Practice", "fullbody", "climbing wall"],
  ["Edge Pick-up", "fingers", "edge block"],
  ["Flexor Curl", "fingers", "dumbbell"],
  ["Floor Scorpion", "shoulders", "bodyweight"],
  ["Foot Cut to Scorpion", "fullbody", "climbing wall"],
  ["Foot on Campusing", "back", "campus board"],
  ["Hands-free Climbing", "fullbody", "climbing wall"],
  ["Heavy Finger Curls", "fingers", "dumbbell"],
  ["Isometric Hang", "fingers", "fingerboard"],
  ["Isometric Hang: Front 2 Half Crimp", "fingers", "fingerboard"],
  ["Isometric Hang: Front 2 Open", "fingers", "fingerboard"],
  ["Isometric Hang: Front 3 Open", "fingers", "fingerboard"],
  ["Isometric Hang: Middle 2 Half Crimp", "fingers", "fingerboard"],
  ["Isometric Hang: Middle 2 Open", "fingers", "fingerboard"],
  ["Isometric Hang: Sloper", "fingers", "fingerboard"],
  ["Large Edge Scorpion", "fullbody", "climbing wall"],
  ["Lattice Circuit", "forearms", "lattice board"],
  ["Lock-off & Bump", "back", "climbing wall"],
  ["Pinch Block", "fingers", "pinch block"],
  ["Route Climbing", "fullbody", "climbing wall"],
  ["Small Edge Scorpion", "fullbody", "climbing wall"],
  ["Static Move to Scorpion", "fullbody", "climbing wall"],
  ["Tension Activations", "fullbody", "climbing wall"],
  ["Wide Campus 1-2-3", "back", "campus board"],
  ["Wide Campus 1-3-5", "back", "campus board"],
];
