// Généré par scripts/gen-seed.py — images de free-exercise-db (domaine public)

export const EXERCISE_IMAGES: Record<string, number> = {
  '3/4 Sit-Up': require('../../assets/images/exercises/3_4_Sit_Up.jpg'),
  '90/90 Hamstring': require('../../assets/images/exercises/90_90_Hamstring.jpg'),
  'Ab Crunch Machine': require('../../assets/images/exercises/Ab_Crunch_Machine.jpg'),
  'Ab Roller': require('../../assets/images/exercises/Ab_Roller.jpg'),
  'Adductor': require('../../assets/images/exercises/Adductor.jpg'),
  'Adductor/Groin': require('../../assets/images/exercises/Adductor_Groin.jpg'),
  'Advanced Kettlebell Windmill': require('../../assets/images/exercises/Advanced_Kettlebell_Windmill.jpg'),
  'Air Bike': require('../../assets/images/exercises/Air_Bike.jpg'),
  'All Fours Quad Stretch': require('../../assets/images/exercises/All_Fours_Quad_Stretch.jpg'),
  'Alternate Hammer Curl': require('../../assets/images/exercises/Alternate_Hammer_Curl.jpg'),
  'Alternate Heel Touchers': require('../../assets/images/exercises/Alternate_Heel_Touchers.jpg'),
  'Alternate Incline Dumbbell Curl': require('../../assets/images/exercises/Alternate_Incline_Dumbbell_Curl.jpg'),
  'Alternate Leg Diagonal Bound': require('../../assets/images/exercises/Alternate_Leg_Diagonal_Bound.jpg'),
  'Alternating Cable Shoulder Press': require('../../assets/images/exercises/Alternating_Cable_Shoulder_Press.jpg'),
  'Alternating Deltoid Raise': require('../../assets/images/exercises/Alternating_Deltoid_Raise.jpg'),
  'Alternating Floor Press': require('../../assets/images/exercises/Alternating_Floor_Press.jpg'),
  'Alternating Hang Clean': require('../../assets/images/exercises/Alternating_Hang_Clean.jpg'),
  'Alternating Kettlebell Press': require('../../assets/images/exercises/Alternating_Kettlebell_Press.jpg'),
  'Alternating Kettlebell Row': require('../../assets/images/exercises/Alternating_Kettlebell_Row.jpg'),
  'Alternating Renegade Row': require('../../assets/images/exercises/Alternating_Renegade_Row.jpg'),
  'Ankle Circles': require('../../assets/images/exercises/Ankle_Circles.jpg'),
  'Ankle On The Knee': require('../../assets/images/exercises/Ankle_On_The_Knee.jpg'),
  'Anterior Tibialis-SMR': require('../../assets/images/exercises/Anterior_Tibialis_SMR.jpg'),
  'Anti-Gravity Press': require('../../assets/images/exercises/Anti_Gravity_Press.jpg'),
  'Arm Circles': require('../../assets/images/exercises/Arm_Circles.jpg'),
  'Arnold Dumbbell Press': require('../../assets/images/exercises/Arnold_Dumbbell_Press.jpg'),
  'Around The Worlds': require('../../assets/images/exercises/Around_The_Worlds.jpg'),
  'Atlas Stone Trainer': require('../../assets/images/exercises/Atlas_Stone_Trainer.jpg'),
  'Atlas Stones': require('../../assets/images/exercises/Atlas_Stones.jpg'),
  'Axle Deadlift': require('../../assets/images/exercises/Axle_Deadlift.jpg'),
  'Back Flyes - With Bands': require('../../assets/images/exercises/Back_Flyes___With_Bands.jpg'),
  'Backward Drag': require('../../assets/images/exercises/Backward_Drag.jpg'),
  'Backward Medicine Ball Throw': require('../../assets/images/exercises/Backward_Medicine_Ball_Throw.jpg'),
  'Balance Board': require('../../assets/images/exercises/Balance_Board.jpg'),
  'Ball Leg Curl': require('../../assets/images/exercises/Ball_Leg_Curl.jpg'),
  'Band Assisted Pull-Up': require('../../assets/images/exercises/Band_Assisted_Pull_Up.jpg'),
  'Band Good Morning': require('../../assets/images/exercises/Band_Good_Morning.jpg'),
  'Band Good Morning (Pull Through)': require('../../assets/images/exercises/Band_Good_Morning_Pull_Through.jpg'),
  'Band Hip Adductions': require('../../assets/images/exercises/Band_Hip_Adductions.jpg'),
  'Band Pull Apart': require('../../assets/images/exercises/Band_Pull_Apart.jpg'),
  'Band Skull Crusher': require('../../assets/images/exercises/Band_Skull_Crusher.jpg'),
  'Barbell Ab Rollout': require('../../assets/images/exercises/Barbell_Ab_Rollout.jpg'),
  'Barbell Ab Rollout - On Knees': require('../../assets/images/exercises/Barbell_Ab_Rollout___On_Knees.jpg'),
  'Barbell Bench Press - Medium Grip': require('../../assets/images/exercises/Barbell_Bench_Press___Medium_Grip.jpg'),
  'Barbell Curl': require('../../assets/images/exercises/Barbell_Curl.jpg'),
  'Barbell Curls Lying Against An Incline': require('../../assets/images/exercises/Barbell_Curls_Lying_Against_An_Incline.jpg'),
  'Barbell Deadlift': require('../../assets/images/exercises/Barbell_Deadlift.jpg'),
  'Barbell Full Squat': require('../../assets/images/exercises/Barbell_Full_Squat.jpg'),
  'Barbell Glute Bridge': require('../../assets/images/exercises/Barbell_Glute_Bridge.jpg'),
  'Barbell Guillotine Bench Press': require('../../assets/images/exercises/Barbell_Guillotine_Bench_Press.jpg'),
  'Barbell Hack Squat': require('../../assets/images/exercises/Barbell_Hack_Squat.jpg'),
  'Barbell Hip Thrust': require('../../assets/images/exercises/Barbell_Hip_Thrust.jpg'),
  'Barbell Incline Bench Press - Medium Grip': require('../../assets/images/exercises/Barbell_Incline_Bench_Press___Medium_Grip.jpg'),
  'Barbell Incline Shoulder Raise': require('../../assets/images/exercises/Barbell_Incline_Shoulder_Raise.jpg'),
  'Barbell Lunge': require('../../assets/images/exercises/Barbell_Lunge.jpg'),
  'Barbell Rear Delt Row': require('../../assets/images/exercises/Barbell_Rear_Delt_Row.jpg'),
  'Barbell Rollout from Bench': require('../../assets/images/exercises/Barbell_Rollout_from_Bench.jpg'),
  'Barbell Seated Calf Raise': require('../../assets/images/exercises/Barbell_Seated_Calf_Raise.jpg'),
  'Barbell Shoulder Press': require('../../assets/images/exercises/Barbell_Shoulder_Press.jpg'),
  'Barbell Shrug': require('../../assets/images/exercises/Barbell_Shrug.jpg'),
  'Barbell Shrug Behind The Back': require('../../assets/images/exercises/Barbell_Shrug_Behind_The_Back.jpg'),
  'Barbell Side Bend': require('../../assets/images/exercises/Barbell_Side_Bend.jpg'),
  'Barbell Side Split Squat': require('../../assets/images/exercises/Barbell_Side_Split_Squat.jpg'),
  'Barbell Squat': require('../../assets/images/exercises/Barbell_Squat.jpg'),
  'Barbell Squat To A Bench': require('../../assets/images/exercises/Barbell_Squat_To_A_Bench.jpg'),
  'Barbell Step Ups': require('../../assets/images/exercises/Barbell_Step_Ups.jpg'),
  'Barbell Walking Lunge': require('../../assets/images/exercises/Barbell_Walking_Lunge.jpg'),
  'Battling Ropes': require('../../assets/images/exercises/Battling_Ropes.jpg'),
  'Bear Crawl Sled Drags': require('../../assets/images/exercises/Bear_Crawl_Sled_Drags.jpg'),
  'Behind Head Chest Stretch': require('../../assets/images/exercises/Behind_Head_Chest_Stretch.jpg'),
  'Bench Dips': require('../../assets/images/exercises/Bench_Dips.jpg'),
  'Bench Jump': require('../../assets/images/exercises/Bench_Jump.jpg'),
  'Bench Press - Powerlifting': require('../../assets/images/exercises/Bench_Press___Powerlifting.jpg'),
  'Bench Press - With Bands': require('../../assets/images/exercises/Bench_Press___With_Bands.jpg'),
  'Bench Press with Chains': require('../../assets/images/exercises/Bench_Press_with_Chains.jpg'),
  'Bench Sprint': require('../../assets/images/exercises/Bench_Sprint.jpg'),
  'Bent-Arm Barbell Pullover': require('../../assets/images/exercises/Bent_Arm_Barbell_Pullover.jpg'),
  'Bent-Arm Dumbbell Pullover': require('../../assets/images/exercises/Bent_Arm_Dumbbell_Pullover.jpg'),
  'Bent-Knee Hip Raise': require('../../assets/images/exercises/Bent_Knee_Hip_Raise.jpg'),
  'Bent Over Barbell Row': require('../../assets/images/exercises/Bent_Over_Barbell_Row.jpg'),
  'Bent Over Dumbbell Rear Delt Raise With Head On Bench': require('../../assets/images/exercises/Bent_Over_Dumbbell_Rear_Delt_Raise_With_Head_On_Bench.jpg'),
  'Bent Over Low-Pulley Side Lateral': require('../../assets/images/exercises/Bent_Over_Low_Pulley_Side_Lateral.jpg'),
  'Bent Over One-Arm Long Bar Row': require('../../assets/images/exercises/Bent_Over_One_Arm_Long_Bar_Row.jpg'),
  'Bent Over Two-Arm Long Bar Row': require('../../assets/images/exercises/Bent_Over_Two_Arm_Long_Bar_Row.jpg'),
  'Bent Over Two-Dumbbell Row': require('../../assets/images/exercises/Bent_Over_Two_Dumbbell_Row.jpg'),
  'Bent Over Two-Dumbbell Row With Palms In': require('../../assets/images/exercises/Bent_Over_Two_Dumbbell_Row_With_Palms_In.jpg'),
  'Bent Press': require('../../assets/images/exercises/Bent_Press.jpg'),
  'Bicycling': require('../../assets/images/exercises/Bicycling.jpg'),
  'Bicycling, Stationary': require('../../assets/images/exercises/Bicycling_Stationary.jpg'),
  'Board Press': require('../../assets/images/exercises/Board_Press.jpg'),
  'Body-Up': require('../../assets/images/exercises/Body_Up.jpg'),
  'Body Tricep Press': require('../../assets/images/exercises/Body_Tricep_Press.jpg'),
  'Bodyweight Flyes': require('../../assets/images/exercises/Bodyweight_Flyes.jpg'),
  'Bodyweight Mid Row': require('../../assets/images/exercises/Bodyweight_Mid_Row.jpg'),
  'Bodyweight Squat': require('../../assets/images/exercises/Bodyweight_Squat.jpg'),
  'Bodyweight Walking Lunge': require('../../assets/images/exercises/Bodyweight_Walking_Lunge.jpg'),
  'Bosu Ball Cable Crunch With Side Bends': require('../../assets/images/exercises/Bosu_Ball_Cable_Crunch_With_Side_Bends.jpg'),
  'Bottoms-Up Clean From The Hang Position': require('../../assets/images/exercises/Bottoms_Up_Clean_From_The_Hang_Position.jpg'),
  'Bottoms Up': require('../../assets/images/exercises/Bottoms_Up.jpg'),
  'Box Jump (Multiple Response)': require('../../assets/images/exercises/Box_Jump_Multiple_Response.jpg'),
  'Box Skip': require('../../assets/images/exercises/Box_Skip.jpg'),
  'Box Squat': require('../../assets/images/exercises/Box_Squat.jpg'),
  'Box Squat with Bands': require('../../assets/images/exercises/Box_Squat_with_Bands.jpg'),
  'Box Squat with Chains': require('../../assets/images/exercises/Box_Squat_with_Chains.jpg'),
  'Brachialis-SMR': require('../../assets/images/exercises/Brachialis_SMR.jpg'),
  'Bradford/Rocky Presses': require('../../assets/images/exercises/Bradford_Rocky_Presses.jpg'),
  'Butt-Ups': require('../../assets/images/exercises/Butt_Ups.jpg'),
  'Butt Lift (Bridge)': require('../../assets/images/exercises/Butt_Lift_Bridge.jpg'),
  'Butterfly': require('../../assets/images/exercises/Butterfly.jpg'),
  'Cable Chest Press': require('../../assets/images/exercises/Cable_Chest_Press.jpg'),
  'Cable Crossover': require('../../assets/images/exercises/Cable_Crossover.jpg'),
  'Cable Crunch': require('../../assets/images/exercises/Cable_Crunch.jpg'),
  'Cable Deadlifts': require('../../assets/images/exercises/Cable_Deadlifts.jpg'),
  'Cable Hammer Curls - Rope Attachment': require('../../assets/images/exercises/Cable_Hammer_Curls___Rope_Attachment.jpg'),
  'Cable Hip Adduction': require('../../assets/images/exercises/Cable_Hip_Adduction.jpg'),
  'Cable Incline Pushdown': require('../../assets/images/exercises/Cable_Incline_Pushdown.jpg'),
  'Cable Incline Triceps Extension': require('../../assets/images/exercises/Cable_Incline_Triceps_Extension.jpg'),
  'Cable Internal Rotation': require('../../assets/images/exercises/Cable_Internal_Rotation.jpg'),
  'Cable Iron Cross': require('../../assets/images/exercises/Cable_Iron_Cross.jpg'),
  'Cable Judo Flip': require('../../assets/images/exercises/Cable_Judo_Flip.jpg'),
  'Cable Lying Triceps Extension': require('../../assets/images/exercises/Cable_Lying_Triceps_Extension.jpg'),
  'Cable One Arm Tricep Extension': require('../../assets/images/exercises/Cable_One_Arm_Tricep_Extension.jpg'),
  'Cable Preacher Curl': require('../../assets/images/exercises/Cable_Preacher_Curl.jpg'),
  'Cable Rear Delt Fly': require('../../assets/images/exercises/Cable_Rear_Delt_Fly.jpg'),
  'Cable Reverse Crunch': require('../../assets/images/exercises/Cable_Reverse_Crunch.jpg'),
  'Cable Rope Overhead Triceps Extension': require('../../assets/images/exercises/Cable_Rope_Overhead_Triceps_Extension.jpg'),
  'Cable Rope Rear-Delt Rows': require('../../assets/images/exercises/Cable_Rope_Rear_Delt_Rows.jpg'),
  'Cable Russian Twists': require('../../assets/images/exercises/Cable_Russian_Twists.jpg'),
  'Cable Seated Crunch': require('../../assets/images/exercises/Cable_Seated_Crunch.jpg'),
  'Cable Seated Lateral Raise': require('../../assets/images/exercises/Cable_Seated_Lateral_Raise.jpg'),
  'Cable Shoulder Press': require('../../assets/images/exercises/Cable_Shoulder_Press.jpg'),
  'Cable Shrugs': require('../../assets/images/exercises/Cable_Shrugs.jpg'),
  'Cable Wrist Curl': require('../../assets/images/exercises/Cable_Wrist_Curl.jpg'),
  'Calf-Machine Shoulder Shrug': require('../../assets/images/exercises/Calf_Machine_Shoulder_Shrug.jpg'),
  'Calf Press': require('../../assets/images/exercises/Calf_Press.jpg'),
  'Calf Press On The Leg Press Machine': require('../../assets/images/exercises/Calf_Press_On_The_Leg_Press_Machine.jpg'),
  'Calf Raise On A Dumbbell': require('../../assets/images/exercises/Calf_Raise_On_A_Dumbbell.jpg'),
  'Calf Raises - With Bands': require('../../assets/images/exercises/Calf_Raises___With_Bands.jpg'),
  'Calf Stretch Elbows Against Wall': require('../../assets/images/exercises/Calf_Stretch_Elbows_Against_Wall.jpg'),
  'Calf Stretch Hands Against Wall': require('../../assets/images/exercises/Calf_Stretch_Hands_Against_Wall.jpg'),
  'Calves-SMR': require('../../assets/images/exercises/Calves_SMR.jpg'),
  'Car Deadlift': require('../../assets/images/exercises/Car_Deadlift.jpg'),
  'Car Drivers': require('../../assets/images/exercises/Car_Drivers.jpg'),
  'Carioca Quick Step': require('../../assets/images/exercises/Carioca_Quick_Step.jpg'),
  'Cat Stretch': require('../../assets/images/exercises/Cat_Stretch.jpg'),
  'Catch and Overhead Throw': require('../../assets/images/exercises/Catch_and_Overhead_Throw.jpg'),
  'Chain Handle Extension': require('../../assets/images/exercises/Chain_Handle_Extension.jpg'),
  'Chain Press': require('../../assets/images/exercises/Chain_Press.jpg'),
  'Chair Leg Extended Stretch': require('../../assets/images/exercises/Chair_Leg_Extended_Stretch.jpg'),
  'Chair Lower Back Stretch': require('../../assets/images/exercises/Chair_Lower_Back_Stretch.jpg'),
  'Chair Squat': require('../../assets/images/exercises/Chair_Squat.jpg'),
  'Chair Upper Body Stretch': require('../../assets/images/exercises/Chair_Upper_Body_Stretch.jpg'),
  'Chest And Front Of Shoulder Stretch': require('../../assets/images/exercises/Chest_And_Front_Of_Shoulder_Stretch.jpg'),
  'Chest Push from 3 point stance': require('../../assets/images/exercises/Chest_Push_from_3_point_stance.jpg'),
  'Chest Push (multiple response)': require('../../assets/images/exercises/Chest_Push_multiple_response.jpg'),
  'Chest Push (single response)': require('../../assets/images/exercises/Chest_Push_single_response.jpg'),
  'Chest Push with Run Release': require('../../assets/images/exercises/Chest_Push_with_Run_Release.jpg'),
  'Chest Stretch on Stability Ball': require('../../assets/images/exercises/Chest_Stretch_on_Stability_Ball.jpg'),
  'Child\'s Pose': require('../../assets/images/exercises/Childs_Pose.jpg'),
  'Chin-Up': require('../../assets/images/exercises/Chin_Up.jpg'),
  'Chin To Chest Stretch': require('../../assets/images/exercises/Chin_To_Chest_Stretch.jpg'),
  'Circus Bell': require('../../assets/images/exercises/Circus_Bell.jpg'),
  'Clean': require('../../assets/images/exercises/Clean.jpg'),
  'Clean Deadlift': require('../../assets/images/exercises/Clean_Deadlift.jpg'),
  'Clean Pull': require('../../assets/images/exercises/Clean_Pull.jpg'),
  'Clean Shrug': require('../../assets/images/exercises/Clean_Shrug.jpg'),
  'Clean and Jerk': require('../../assets/images/exercises/Clean_and_Jerk.jpg'),
  'Clean and Press': require('../../assets/images/exercises/Clean_and_Press.jpg'),
  'Clean from Blocks': require('../../assets/images/exercises/Clean_from_Blocks.jpg'),
  'Clock Push-Up': require('../../assets/images/exercises/Clock_Push_Up.jpg'),
  'Close-Grip Barbell Bench Press': require('../../assets/images/exercises/Close_Grip_Barbell_Bench_Press.jpg'),
  'Close-Grip Dumbbell Press': require('../../assets/images/exercises/Close_Grip_Dumbbell_Press.jpg'),
  'Close-Grip EZ-Bar Curl with Band': require('../../assets/images/exercises/Close_Grip_EZ_Bar_Curl_with_Band.jpg'),
  'Close-Grip EZ-Bar Press': require('../../assets/images/exercises/Close_Grip_EZ_Bar_Press.jpg'),
  'Close-Grip EZ Bar Curl': require('../../assets/images/exercises/Close_Grip_EZ_Bar_Curl.jpg'),
  'Close-Grip Front Lat Pulldown': require('../../assets/images/exercises/Close_Grip_Front_Lat_Pulldown.jpg'),
  'Close-Grip Push-Up off of a Dumbbell': require('../../assets/images/exercises/Close_Grip_Push_Up_off_of_a_Dumbbell.jpg'),
  'Close-Grip Standing Barbell Curl': require('../../assets/images/exercises/Close_Grip_Standing_Barbell_Curl.jpg'),
  'Cocoons': require('../../assets/images/exercises/Cocoons.jpg'),
  'Conan\'s Wheel': require('../../assets/images/exercises/Conans_Wheel.jpg'),
  'Concentration Curls': require('../../assets/images/exercises/Concentration_Curls.jpg'),
  'Cross-Body Crunch': require('../../assets/images/exercises/Cross_Body_Crunch.jpg'),
  'Cross Body Hammer Curl': require('../../assets/images/exercises/Cross_Body_Hammer_Curl.jpg'),
  'Cross Over - With Bands': require('../../assets/images/exercises/Cross_Over___With_Bands.jpg'),
  'Crossover Reverse Lunge': require('../../assets/images/exercises/Crossover_Reverse_Lunge.jpg'),
  'Crucifix': require('../../assets/images/exercises/Crucifix.jpg'),
  'Crunch - Hands Overhead': require('../../assets/images/exercises/Crunch___Hands_Overhead.jpg'),
  'Crunch - Legs On Exercise Ball': require('../../assets/images/exercises/Crunch___Legs_On_Exercise_Ball.jpg'),
  'Crunches': require('../../assets/images/exercises/Crunches.jpg'),
  'Cuban Press': require('../../assets/images/exercises/Cuban_Press.jpg'),
  'Dancer\'s Stretch': require('../../assets/images/exercises/Dancers_Stretch.jpg'),
  'Dead Bug': require('../../assets/images/exercises/Dead_Bug.jpg'),
  'Deadlift with Bands': require('../../assets/images/exercises/Deadlift_with_Bands.jpg'),
  'Deadlift with Chains': require('../../assets/images/exercises/Deadlift_with_Chains.jpg'),
  'Decline Barbell Bench Press': require('../../assets/images/exercises/Decline_Barbell_Bench_Press.jpg'),
  'Decline Close-Grip Bench To Skull Crusher': require('../../assets/images/exercises/Decline_Close_Grip_Bench_To_Skull_Crusher.jpg'),
  'Decline Crunch': require('../../assets/images/exercises/Decline_Crunch.jpg'),
  'Decline Dumbbell Bench Press': require('../../assets/images/exercises/Decline_Dumbbell_Bench_Press.jpg'),
  'Decline Dumbbell Flyes': require('../../assets/images/exercises/Decline_Dumbbell_Flyes.jpg'),
  'Decline Dumbbell Triceps Extension': require('../../assets/images/exercises/Decline_Dumbbell_Triceps_Extension.jpg'),
  'Decline EZ Bar Triceps Extension': require('../../assets/images/exercises/Decline_EZ_Bar_Triceps_Extension.jpg'),
  'Decline Oblique Crunch': require('../../assets/images/exercises/Decline_Oblique_Crunch.jpg'),
  'Decline Push-Up': require('../../assets/images/exercises/Decline_Push_Up.jpg'),
  'Decline Reverse Crunch': require('../../assets/images/exercises/Decline_Reverse_Crunch.jpg'),
  'Decline Smith Press': require('../../assets/images/exercises/Decline_Smith_Press.jpg'),
  'Deficit Deadlift': require('../../assets/images/exercises/Deficit_Deadlift.jpg'),
  'Depth Jump Leap': require('../../assets/images/exercises/Depth_Jump_Leap.jpg'),
  'Dip Machine': require('../../assets/images/exercises/Dip_Machine.jpg'),
  'Dips - Chest Version': require('../../assets/images/exercises/Dips___Chest_Version.jpg'),
  'Dips - Triceps Version': require('../../assets/images/exercises/Dips___Triceps_Version.jpg'),
  'Donkey Calf Raises': require('../../assets/images/exercises/Donkey_Calf_Raises.jpg'),
  'Double Kettlebell Alternating Hang Clean': require('../../assets/images/exercises/Double_Kettlebell_Alternating_Hang_Clean.jpg'),
  'Double Kettlebell Jerk': require('../../assets/images/exercises/Double_Kettlebell_Jerk.jpg'),
  'Double Kettlebell Push Press': require('../../assets/images/exercises/Double_Kettlebell_Push_Press.jpg'),
  'Double Kettlebell Snatch': require('../../assets/images/exercises/Double_Kettlebell_Snatch.jpg'),
  'Double Kettlebell Windmill': require('../../assets/images/exercises/Double_Kettlebell_Windmill.jpg'),
  'Double Leg Butt Kick': require('../../assets/images/exercises/Double_Leg_Butt_Kick.jpg'),
  'Downward Facing Balance': require('../../assets/images/exercises/Downward_Facing_Balance.jpg'),
  'Drag Curl': require('../../assets/images/exercises/Drag_Curl.jpg'),
  'Drop Push': require('../../assets/images/exercises/Drop_Push.jpg'),
  'Dumbbell Alternate Bicep Curl': require('../../assets/images/exercises/Dumbbell_Alternate_Bicep_Curl.jpg'),
  'Dumbbell Bench Press': require('../../assets/images/exercises/Dumbbell_Bench_Press.jpg'),
  'Dumbbell Bench Press with Neutral Grip': require('../../assets/images/exercises/Dumbbell_Bench_Press_with_Neutral_Grip.jpg'),
  'Dumbbell Bicep Curl': require('../../assets/images/exercises/Dumbbell_Bicep_Curl.jpg'),
  'Dumbbell Clean': require('../../assets/images/exercises/Dumbbell_Clean.jpg'),
  'Dumbbell Floor Press': require('../../assets/images/exercises/Dumbbell_Floor_Press.jpg'),
  'Dumbbell Flyes': require('../../assets/images/exercises/Dumbbell_Flyes.jpg'),
  'Dumbbell Incline Row': require('../../assets/images/exercises/Dumbbell_Incline_Row.jpg'),
  'Dumbbell Incline Shoulder Raise': require('../../assets/images/exercises/Dumbbell_Incline_Shoulder_Raise.jpg'),
  'Dumbbell Lunges': require('../../assets/images/exercises/Dumbbell_Lunges.jpg'),
  'Dumbbell Lying One-Arm Rear Lateral Raise': require('../../assets/images/exercises/Dumbbell_Lying_One_Arm_Rear_Lateral_Raise.jpg'),
  'Dumbbell Lying Pronation': require('../../assets/images/exercises/Dumbbell_Lying_Pronation.jpg'),
  'Dumbbell Lying Rear Lateral Raise': require('../../assets/images/exercises/Dumbbell_Lying_Rear_Lateral_Raise.jpg'),
  'Dumbbell Lying Supination': require('../../assets/images/exercises/Dumbbell_Lying_Supination.jpg'),
  'Dumbbell One-Arm Shoulder Press': require('../../assets/images/exercises/Dumbbell_One_Arm_Shoulder_Press.jpg'),
  'Dumbbell One-Arm Triceps Extension': require('../../assets/images/exercises/Dumbbell_One_Arm_Triceps_Extension.jpg'),
  'Dumbbell One-Arm Upright Row': require('../../assets/images/exercises/Dumbbell_One_Arm_Upright_Row.jpg'),
  'Dumbbell Prone Incline Curl': require('../../assets/images/exercises/Dumbbell_Prone_Incline_Curl.jpg'),
  'Dumbbell Raise': require('../../assets/images/exercises/Dumbbell_Raise.jpg'),
  'Dumbbell Rear Lunge': require('../../assets/images/exercises/Dumbbell_Rear_Lunge.jpg'),
  'Dumbbell Scaption': require('../../assets/images/exercises/Dumbbell_Scaption.jpg'),
  'Dumbbell Seated Box Jump': require('../../assets/images/exercises/Dumbbell_Seated_Box_Jump.jpg'),
  'Dumbbell Seated One-Leg Calf Raise': require('../../assets/images/exercises/Dumbbell_Seated_One_Leg_Calf_Raise.jpg'),
  'Dumbbell Shoulder Press': require('../../assets/images/exercises/Dumbbell_Shoulder_Press.jpg'),
  'Dumbbell Shrug': require('../../assets/images/exercises/Dumbbell_Shrug.jpg'),
  'Dumbbell Side Bend': require('../../assets/images/exercises/Dumbbell_Side_Bend.jpg'),
  'Dumbbell Squat': require('../../assets/images/exercises/Dumbbell_Squat.jpg'),
  'Dumbbell Squat To A Bench': require('../../assets/images/exercises/Dumbbell_Squat_To_A_Bench.jpg'),
  'Dumbbell Step Ups': require('../../assets/images/exercises/Dumbbell_Step_Ups.jpg'),
  'Dumbbell Tricep Extension -Pronated Grip': require('../../assets/images/exercises/Dumbbell_Tricep_Extension__Pronated_Grip.jpg'),
  'Dynamic Back Stretch': require('../../assets/images/exercises/Dynamic_Back_Stretch.jpg'),
  'Dynamic Chest Stretch': require('../../assets/images/exercises/Dynamic_Chest_Stretch.jpg'),
  'EZ-Bar Curl': require('../../assets/images/exercises/EZ_Bar_Curl.jpg'),
  'EZ-Bar Skullcrusher': require('../../assets/images/exercises/EZ_Bar_Skullcrusher.jpg'),
  'Elbow Circles': require('../../assets/images/exercises/Elbow_Circles.jpg'),
  'Elbow to Knee': require('../../assets/images/exercises/Elbow_to_Knee.jpg'),
  'Elbows Back': require('../../assets/images/exercises/Elbows_Back.jpg'),
  'Elevated Back Lunge': require('../../assets/images/exercises/Elevated_Back_Lunge.jpg'),
  'Elevated Cable Rows': require('../../assets/images/exercises/Elevated_Cable_Rows.jpg'),
  'Elliptical Trainer': require('../../assets/images/exercises/Elliptical_Trainer.jpg'),
  'Exercise Ball Crunch': require('../../assets/images/exercises/Exercise_Ball_Crunch.jpg'),
  'Exercise Ball Pull-In': require('../../assets/images/exercises/Exercise_Ball_Pull_In.jpg'),
  'Extended Range One-Arm Kettlebell Floor Press': require('../../assets/images/exercises/Extended_Range_One_Arm_Kettlebell_Floor_Press.jpg'),
  'External Rotation': require('../../assets/images/exercises/External_Rotation.jpg'),
  'External Rotation with Band': require('../../assets/images/exercises/External_Rotation_with_Band.jpg'),
  'External Rotation with Cable': require('../../assets/images/exercises/External_Rotation_with_Cable.jpg'),
  'Face Pull': require('../../assets/images/exercises/Face_Pull.jpg'),
  'Farmer\'s Walk': require('../../assets/images/exercises/Farmers_Walk.jpg'),
  'Fast Skipping': require('../../assets/images/exercises/Fast_Skipping.jpg'),
  'Finger Curls': require('../../assets/images/exercises/Finger_Curls.jpg'),
  'Flat Bench Cable Flyes': require('../../assets/images/exercises/Flat_Bench_Cable_Flyes.jpg'),
  'Flat Bench Leg Pull-In': require('../../assets/images/exercises/Flat_Bench_Leg_Pull_In.jpg'),
  'Flat Bench Lying Leg Raise': require('../../assets/images/exercises/Flat_Bench_Lying_Leg_Raise.jpg'),
  'Flexor Incline Dumbbell Curls': require('../../assets/images/exercises/Flexor_Incline_Dumbbell_Curls.jpg'),
  'Floor Glute-Ham Raise': require('../../assets/images/exercises/Floor_Glute_Ham_Raise.jpg'),
  'Floor Press': require('../../assets/images/exercises/Floor_Press.jpg'),
  'Floor Press with Chains': require('../../assets/images/exercises/Floor_Press_with_Chains.jpg'),
  'Flutter Kicks': require('../../assets/images/exercises/Flutter_Kicks.jpg'),
  'Foot-SMR': require('../../assets/images/exercises/Foot_SMR.jpg'),
  'Forward Drag with Press': require('../../assets/images/exercises/Forward_Drag_with_Press.jpg'),
  'Frankenstein Squat': require('../../assets/images/exercises/Frankenstein_Squat.jpg'),
  'Freehand Jump Squat': require('../../assets/images/exercises/Freehand_Jump_Squat.jpg'),
  'Frog Hops': require('../../assets/images/exercises/Frog_Hops.jpg'),
  'Frog Sit-Ups': require('../../assets/images/exercises/Frog_Sit_Ups.jpg'),
  'Front Barbell Squat': require('../../assets/images/exercises/Front_Barbell_Squat.jpg'),
  'Front Barbell Squat To A Bench': require('../../assets/images/exercises/Front_Barbell_Squat_To_A_Bench.jpg'),
  'Front Box Jump': require('../../assets/images/exercises/Front_Box_Jump.jpg'),
  'Front Cable Raise': require('../../assets/images/exercises/Front_Cable_Raise.jpg'),
  'Front Cone Hops (or hurdle hops)': require('../../assets/images/exercises/Front_Cone_Hops_or_hurdle_hops.jpg'),
  'Front Dumbbell Raise': require('../../assets/images/exercises/Front_Dumbbell_Raise.jpg'),
  'Front Incline Dumbbell Raise': require('../../assets/images/exercises/Front_Incline_Dumbbell_Raise.jpg'),
  'Front Leg Raises': require('../../assets/images/exercises/Front_Leg_Raises.jpg'),
  'Front Plate Raise': require('../../assets/images/exercises/Front_Plate_Raise.jpg'),
  'Front Raise And Pullover': require('../../assets/images/exercises/Front_Raise_And_Pullover.jpg'),
  'Front Squat (Clean Grip)': require('../../assets/images/exercises/Front_Squat_Clean_Grip.jpg'),
  'Front Squats With Two Kettlebells': require('../../assets/images/exercises/Front_Squats_With_Two_Kettlebells.jpg'),
  'Front Two-Dumbbell Raise': require('../../assets/images/exercises/Front_Two_Dumbbell_Raise.jpg'),
  'Full Range-Of-Motion Lat Pulldown': require('../../assets/images/exercises/Full_Range_Of_Motion_Lat_Pulldown.jpg'),
  'Gironda Sternum Chins': require('../../assets/images/exercises/Gironda_Sternum_Chins.jpg'),
  'Glute Ham Raise': require('../../assets/images/exercises/Glute_Ham_Raise.jpg'),
  'Glute Kickback': require('../../assets/images/exercises/Glute_Kickback.jpg'),
  'Goblet Squat': require('../../assets/images/exercises/Goblet_Squat.jpg'),
  'Good Morning': require('../../assets/images/exercises/Good_Morning.jpg'),
  'Good Morning off Pins': require('../../assets/images/exercises/Good_Morning_off_Pins.jpg'),
  'Gorilla Chin/Crunch': require('../../assets/images/exercises/Gorilla_Chin_Crunch.jpg'),
  'Groin and Back Stretch': require('../../assets/images/exercises/Groin_and_Back_Stretch.jpg'),
  'Groiners': require('../../assets/images/exercises/Groiners.jpg'),
  'Hack Squat': require('../../assets/images/exercises/Hack_Squat.jpg'),
  'Hammer Curls': require('../../assets/images/exercises/Hammer_Curls.jpg'),
  'Hammer Grip Incline DB Bench Press': require('../../assets/images/exercises/Hammer_Grip_Incline_DB_Bench_Press.jpg'),
  'Hamstring-SMR': require('../../assets/images/exercises/Hamstring_SMR.jpg'),
  'Hamstring Stretch': require('../../assets/images/exercises/Hamstring_Stretch.jpg'),
  'Handstand Push-Ups': require('../../assets/images/exercises/Handstand_Push_Ups.jpg'),
  'Hang Clean': require('../../assets/images/exercises/Hang_Clean.jpg'),
  'Hang Clean - Below the Knees': require('../../assets/images/exercises/Hang_Clean___Below_the_Knees.jpg'),
  'Hang Snatch': require('../../assets/images/exercises/Hang_Snatch.jpg'),
  'Hang Snatch - Below Knees': require('../../assets/images/exercises/Hang_Snatch___Below_Knees.jpg'),
  'Hanging Bar Good Morning': require('../../assets/images/exercises/Hanging_Bar_Good_Morning.jpg'),
  'Hanging Leg Raise': require('../../assets/images/exercises/Hanging_Leg_Raise.jpg'),
  'Hanging Pike': require('../../assets/images/exercises/Hanging_Pike.jpg'),
  'Heaving Snatch Balance': require('../../assets/images/exercises/Heaving_Snatch_Balance.jpg'),
  'Heavy Bag Thrust': require('../../assets/images/exercises/Heavy_Bag_Thrust.jpg'),
  'High Cable Curls': require('../../assets/images/exercises/High_Cable_Curls.jpg'),
  'Hip Circles (prone)': require('../../assets/images/exercises/Hip_Circles_prone.jpg'),
  'Hip Extension with Bands': require('../../assets/images/exercises/Hip_Extension_with_Bands.jpg'),
  'Hip Flexion with Band': require('../../assets/images/exercises/Hip_Flexion_with_Band.jpg'),
  'Hip Lift with Band': require('../../assets/images/exercises/Hip_Lift_with_Band.jpg'),
  'Hug A Ball': require('../../assets/images/exercises/Hug_A_Ball.jpg'),
  'Hug Knees To Chest': require('../../assets/images/exercises/Hug_Knees_To_Chest.jpg'),
  'Hurdle Hops': require('../../assets/images/exercises/Hurdle_Hops.jpg'),
  'Hyperextensions (Back Extensions)': require('../../assets/images/exercises/Hyperextensions_Back_Extensions.jpg'),
  'Hyperextensions With No Hyperextension Bench': require('../../assets/images/exercises/Hyperextensions_With_No_Hyperextension_Bench.jpg'),
  'IT Band and Glute Stretch': require('../../assets/images/exercises/IT_Band_and_Glute_Stretch.jpg'),
  'Iliotibial Tract-SMR': require('../../assets/images/exercises/Iliotibial_Tract_SMR.jpg'),
  'Inchworm': require('../../assets/images/exercises/Inchworm.jpg'),
  'Incline Barbell Triceps Extension': require('../../assets/images/exercises/Incline_Barbell_Triceps_Extension.jpg'),
  'Incline Bench Pull': require('../../assets/images/exercises/Incline_Bench_Pull.jpg'),
  'Incline Cable Chest Press': require('../../assets/images/exercises/Incline_Cable_Chest_Press.jpg'),
  'Incline Cable Flye': require('../../assets/images/exercises/Incline_Cable_Flye.jpg'),
  'Incline Dumbbell Bench With Palms Facing In': require('../../assets/images/exercises/Incline_Dumbbell_Bench_With_Palms_Facing_In.jpg'),
  'Incline Dumbbell Curl': require('../../assets/images/exercises/Incline_Dumbbell_Curl.jpg'),
  'Incline Dumbbell Flyes': require('../../assets/images/exercises/Incline_Dumbbell_Flyes.jpg'),
  'Incline Dumbbell Flyes - With A Twist': require('../../assets/images/exercises/Incline_Dumbbell_Flyes___With_A_Twist.jpg'),
  'Incline Dumbbell Press': require('../../assets/images/exercises/Incline_Dumbbell_Press.jpg'),
  'Incline Hammer Curls': require('../../assets/images/exercises/Incline_Hammer_Curls.jpg'),
  'Incline Inner Biceps Curl': require('../../assets/images/exercises/Incline_Inner_Biceps_Curl.jpg'),
  'Incline Push-Up': require('../../assets/images/exercises/Incline_Push_Up.jpg'),
  'Incline Push-Up Close-Grip': require('../../assets/images/exercises/Incline_Push_Up_Close_Grip.jpg'),
  'Incline Push-Up Depth Jump': require('../../assets/images/exercises/Incline_Push_Up_Depth_Jump.jpg'),
  'Incline Push-Up Medium': require('../../assets/images/exercises/Incline_Push_Up_Medium.jpg'),
  'Incline Push-Up Reverse Grip': require('../../assets/images/exercises/Incline_Push_Up_Reverse_Grip.jpg'),
  'Incline Push-Up Wide': require('../../assets/images/exercises/Incline_Push_Up_Wide.jpg'),
  'Intermediate Groin Stretch': require('../../assets/images/exercises/Intermediate_Groin_Stretch.jpg'),
  'Intermediate Hip Flexor and Quad Stretch': require('../../assets/images/exercises/Intermediate_Hip_Flexor_and_Quad_Stretch.jpg'),
  'Internal Rotation with Band': require('../../assets/images/exercises/Internal_Rotation_with_Band.jpg'),
  'Inverted Row': require('../../assets/images/exercises/Inverted_Row.jpg'),
  'Inverted Row with Straps': require('../../assets/images/exercises/Inverted_Row_with_Straps.jpg'),
  'Iron Cross': require('../../assets/images/exercises/Iron_Cross.jpg'),
  'Iron Crosses (stretch)': require('../../assets/images/exercises/Iron_Crosses_stretch.jpg'),
  'Isometric Chest Squeezes': require('../../assets/images/exercises/Isometric_Chest_Squeezes.jpg'),
  'Isometric Neck Exercise - Front And Back': require('../../assets/images/exercises/Isometric_Neck_Exercise___Front_And_Back.jpg'),
  'Isometric Neck Exercise - Sides': require('../../assets/images/exercises/Isometric_Neck_Exercise___Sides.jpg'),
  'Isometric Wipers': require('../../assets/images/exercises/Isometric_Wipers.jpg'),
  'JM Press': require('../../assets/images/exercises/JM_Press.jpg'),
  'Jackknife Sit-Up': require('../../assets/images/exercises/Jackknife_Sit_Up.jpg'),
  'Janda Sit-Up': require('../../assets/images/exercises/Janda_Sit_Up.jpg'),
  'Jefferson Squats': require('../../assets/images/exercises/Jefferson_Squats.jpg'),
  'Jerk Balance': require('../../assets/images/exercises/Jerk_Balance.jpg'),
  'Jerk Dip Squat': require('../../assets/images/exercises/Jerk_Dip_Squat.jpg'),
  'Jogging, Treadmill': require('../../assets/images/exercises/Jogging_Treadmill.jpg'),
  'Keg Load': require('../../assets/images/exercises/Keg_Load.jpg'),
  'Kettlebell Arnold Press': require('../../assets/images/exercises/Kettlebell_Arnold_Press.jpg'),
  'Kettlebell Dead Clean': require('../../assets/images/exercises/Kettlebell_Dead_Clean.jpg'),
  'Kettlebell Figure 8': require('../../assets/images/exercises/Kettlebell_Figure_8.jpg'),
  'Kettlebell Hang Clean': require('../../assets/images/exercises/Kettlebell_Hang_Clean.jpg'),
  'Kettlebell One-Legged Deadlift': require('../../assets/images/exercises/Kettlebell_One_Legged_Deadlift.jpg'),
  'Kettlebell Pass Between The Legs': require('../../assets/images/exercises/Kettlebell_Pass_Between_The_Legs.jpg'),
  'Kettlebell Pirate Ships': require('../../assets/images/exercises/Kettlebell_Pirate_Ships.jpg'),
  'Kettlebell Pistol Squat': require('../../assets/images/exercises/Kettlebell_Pistol_Squat.jpg'),
  'Kettlebell Seated Press': require('../../assets/images/exercises/Kettlebell_Seated_Press.jpg'),
  'Kettlebell Seesaw Press': require('../../assets/images/exercises/Kettlebell_Seesaw_Press.jpg'),
  'Kettlebell Sumo High Pull': require('../../assets/images/exercises/Kettlebell_Sumo_High_Pull.jpg'),
  'Kettlebell Thruster': require('../../assets/images/exercises/Kettlebell_Thruster.jpg'),
  'Kettlebell Turkish Get-Up (Lunge style)': require('../../assets/images/exercises/Kettlebell_Turkish_Get_Up_Lunge_style.jpg'),
  'Kettlebell Turkish Get-Up (Squat style)': require('../../assets/images/exercises/Kettlebell_Turkish_Get_Up_Squat_style.jpg'),
  'Kettlebell Windmill': require('../../assets/images/exercises/Kettlebell_Windmill.jpg'),
  'Kipping Muscle Up': require('../../assets/images/exercises/Kipping_Muscle_Up.jpg'),
  'Knee Across The Body': require('../../assets/images/exercises/Knee_Across_The_Body.jpg'),
  'Knee Circles': require('../../assets/images/exercises/Knee_Circles.jpg'),
  'Knee/Hip Raise On Parallel Bars': require('../../assets/images/exercises/Knee_Hip_Raise_On_Parallel_Bars.jpg'),
  'Knee Tuck Jump': require('../../assets/images/exercises/Knee_Tuck_Jump.jpg'),
  'Kneeling Arm Drill': require('../../assets/images/exercises/Kneeling_Arm_Drill.jpg'),
  'Kneeling Cable Crunch With Alternating Oblique Twists': require('../../assets/images/exercises/Kneeling_Cable_Crunch_With_Alternating_Oblique_Twists.jpg'),
  'Kneeling Cable Triceps Extension': require('../../assets/images/exercises/Kneeling_Cable_Triceps_Extension.jpg'),
  'Kneeling Forearm Stretch': require('../../assets/images/exercises/Kneeling_Forearm_Stretch.jpg'),
  'Kneeling High Pulley Row': require('../../assets/images/exercises/Kneeling_High_Pulley_Row.jpg'),
  'Kneeling Hip Flexor': require('../../assets/images/exercises/Kneeling_Hip_Flexor.jpg'),
  'Kneeling Jump Squat': require('../../assets/images/exercises/Kneeling_Jump_Squat.jpg'),
  'Kneeling Single-Arm High Pulley Row': require('../../assets/images/exercises/Kneeling_Single_Arm_High_Pulley_Row.jpg'),
  'Kneeling Squat': require('../../assets/images/exercises/Kneeling_Squat.jpg'),
  'Landmine 180\'s': require('../../assets/images/exercises/Landmine_180s.jpg'),
  'Landmine Linear Jammer': require('../../assets/images/exercises/Landmine_Linear_Jammer.jpg'),
  'Lateral Bound': require('../../assets/images/exercises/Lateral_Bound.jpg'),
  'Lateral Box Jump': require('../../assets/images/exercises/Lateral_Box_Jump.jpg'),
  'Lateral Cone Hops': require('../../assets/images/exercises/Lateral_Cone_Hops.jpg'),
  'Lateral Raise - With Bands': require('../../assets/images/exercises/Lateral_Raise___With_Bands.jpg'),
  'Latissimus Dorsi-SMR': require('../../assets/images/exercises/Latissimus_Dorsi_SMR.jpg'),
  'Leg-Over Floor Press': require('../../assets/images/exercises/Leg_Over_Floor_Press.jpg'),
  'Leg-Up Hamstring Stretch': require('../../assets/images/exercises/Leg_Up_Hamstring_Stretch.jpg'),
  'Leg Extensions': require('../../assets/images/exercises/Leg_Extensions.jpg'),
  'Leg Lift': require('../../assets/images/exercises/Leg_Lift.jpg'),
  'Leg Press': require('../../assets/images/exercises/Leg_Press.jpg'),
  'Leg Pull-In': require('../../assets/images/exercises/Leg_Pull_In.jpg'),
  'Leverage Chest Press': require('../../assets/images/exercises/Leverage_Chest_Press.jpg'),
  'Leverage Deadlift': require('../../assets/images/exercises/Leverage_Deadlift.jpg'),
  'Leverage Decline Chest Press': require('../../assets/images/exercises/Leverage_Decline_Chest_Press.jpg'),
  'Leverage High Row': require('../../assets/images/exercises/Leverage_High_Row.jpg'),
  'Leverage Incline Chest Press': require('../../assets/images/exercises/Leverage_Incline_Chest_Press.jpg'),
  'Leverage Iso Row': require('../../assets/images/exercises/Leverage_Iso_Row.jpg'),
  'Leverage Shoulder Press': require('../../assets/images/exercises/Leverage_Shoulder_Press.jpg'),
  'Leverage Shrug': require('../../assets/images/exercises/Leverage_Shrug.jpg'),
  'Linear 3-Part Start Technique': require('../../assets/images/exercises/Linear_3_Part_Start_Technique.jpg'),
  'Linear Acceleration Wall Drill': require('../../assets/images/exercises/Linear_Acceleration_Wall_Drill.jpg'),
  'Linear Depth Jump': require('../../assets/images/exercises/Linear_Depth_Jump.jpg'),
  'Log Lift': require('../../assets/images/exercises/Log_Lift.jpg'),
  'London Bridges': require('../../assets/images/exercises/London_Bridges.jpg'),
  'Looking At Ceiling': require('../../assets/images/exercises/Looking_At_Ceiling.jpg'),
  'Low Cable Crossover': require('../../assets/images/exercises/Low_Cable_Crossover.jpg'),
  'Low Cable Triceps Extension': require('../../assets/images/exercises/Low_Cable_Triceps_Extension.jpg'),
  'Low Pulley Row To Neck': require('../../assets/images/exercises/Low_Pulley_Row_To_Neck.jpg'),
  'Lower Back-SMR': require('../../assets/images/exercises/Lower_Back_SMR.jpg'),
  'Lower Back Curl': require('../../assets/images/exercises/Lower_Back_Curl.jpg'),
  'Lunge Pass Through': require('../../assets/images/exercises/Lunge_Pass_Through.jpg'),
  'Lunge Sprint': require('../../assets/images/exercises/Lunge_Sprint.jpg'),
  'Lying Bent Leg Groin': require('../../assets/images/exercises/Lying_Bent_Leg_Groin.jpg'),
  'Lying Cable Curl': require('../../assets/images/exercises/Lying_Cable_Curl.jpg'),
  'Lying Cambered Barbell Row': require('../../assets/images/exercises/Lying_Cambered_Barbell_Row.jpg'),
  'Lying Close-Grip Bar Curl On High Pulley': require('../../assets/images/exercises/Lying_Close_Grip_Bar_Curl_On_High_Pulley.jpg'),
  'Lying Close-Grip Barbell Triceps Extension Behind The Head': require('../../assets/images/exercises/Lying_Close_Grip_Barbell_Triceps_Extension_Behind_The_Head.jpg'),
  'Lying Close-Grip Barbell Triceps Press To Chin': require('../../assets/images/exercises/Lying_Close_Grip_Barbell_Triceps_Press_To_Chin.jpg'),
  'Lying Crossover': require('../../assets/images/exercises/Lying_Crossover.jpg'),
  'Lying Dumbbell Tricep Extension': require('../../assets/images/exercises/Lying_Dumbbell_Tricep_Extension.jpg'),
  'Lying Face Down Plate Neck Resistance': require('../../assets/images/exercises/Lying_Face_Down_Plate_Neck_Resistance.jpg'),
  'Lying Face Up Plate Neck Resistance': require('../../assets/images/exercises/Lying_Face_Up_Plate_Neck_Resistance.jpg'),
  'Lying Glute': require('../../assets/images/exercises/Lying_Glute.jpg'),
  'Lying Hamstring': require('../../assets/images/exercises/Lying_Hamstring.jpg'),
  'Lying High Bench Barbell Curl': require('../../assets/images/exercises/Lying_High_Bench_Barbell_Curl.jpg'),
  'Lying Leg Curls': require('../../assets/images/exercises/Lying_Leg_Curls.jpg'),
  'Lying Machine Squat': require('../../assets/images/exercises/Lying_Machine_Squat.jpg'),
  'Lying One-Arm Lateral Raise': require('../../assets/images/exercises/Lying_One_Arm_Lateral_Raise.jpg'),
  'Lying Prone Quadriceps': require('../../assets/images/exercises/Lying_Prone_Quadriceps.jpg'),
  'Lying Rear Delt Raise': require('../../assets/images/exercises/Lying_Rear_Delt_Raise.jpg'),
  'Lying Supine Dumbbell Curl': require('../../assets/images/exercises/Lying_Supine_Dumbbell_Curl.jpg'),
  'Lying T-Bar Row': require('../../assets/images/exercises/Lying_T_Bar_Row.jpg'),
  'Lying Triceps Press': require('../../assets/images/exercises/Lying_Triceps_Press.jpg'),
  'Machine Bench Press': require('../../assets/images/exercises/Machine_Bench_Press.jpg'),
  'Machine Bicep Curl': require('../../assets/images/exercises/Machine_Bicep_Curl.jpg'),
  'Machine Preacher Curls': require('../../assets/images/exercises/Machine_Preacher_Curls.jpg'),
  'Machine Shoulder (Military) Press': require('../../assets/images/exercises/Machine_Shoulder_Military_Press.jpg'),
  'Machine Triceps Extension': require('../../assets/images/exercises/Machine_Triceps_Extension.jpg'),
  'Medicine Ball Chest Pass': require('../../assets/images/exercises/Medicine_Ball_Chest_Pass.jpg'),
  'Medicine Ball Full Twist': require('../../assets/images/exercises/Medicine_Ball_Full_Twist.jpg'),
  'Medicine Ball Scoop Throw': require('../../assets/images/exercises/Medicine_Ball_Scoop_Throw.jpg'),
  'Middle Back Shrug': require('../../assets/images/exercises/Middle_Back_Shrug.jpg'),
  'Middle Back Stretch': require('../../assets/images/exercises/Middle_Back_Stretch.jpg'),
  'Mixed Grip Chin': require('../../assets/images/exercises/Mixed_Grip_Chin.jpg'),
  'Monster Walk': require('../../assets/images/exercises/Monster_Walk.jpg'),
  'Mountain Climbers': require('../../assets/images/exercises/Mountain_Climbers.jpg'),
  'Moving Claw Series': require('../../assets/images/exercises/Moving_Claw_Series.jpg'),
  'Muscle Snatch': require('../../assets/images/exercises/Muscle_Snatch.jpg'),
  'Muscle Up': require('../../assets/images/exercises/Muscle_Up.jpg'),
  'Narrow Stance Hack Squats': require('../../assets/images/exercises/Narrow_Stance_Hack_Squats.jpg'),
  'Narrow Stance Leg Press': require('../../assets/images/exercises/Narrow_Stance_Leg_Press.jpg'),
  'Narrow Stance Squats': require('../../assets/images/exercises/Narrow_Stance_Squats.jpg'),
  'Natural Glute Ham Raise': require('../../assets/images/exercises/Natural_Glute_Ham_Raise.jpg'),
  'Neck-SMR': require('../../assets/images/exercises/Neck_SMR.jpg'),
  'Neck Press': require('../../assets/images/exercises/Neck_Press.jpg'),
  'Oblique Crunches': require('../../assets/images/exercises/Oblique_Crunches.jpg'),
  'Oblique Crunches - On The Floor': require('../../assets/images/exercises/Oblique_Crunches___On_The_Floor.jpg'),
  'Olympic Squat': require('../../assets/images/exercises/Olympic_Squat.jpg'),
  'On-Your-Back Quad Stretch': require('../../assets/images/exercises/On_Your_Back_Quad_Stretch.jpg'),
  'On Your Side Quad Stretch': require('../../assets/images/exercises/On_Your_Side_Quad_Stretch.jpg'),
  'One-Arm Dumbbell Row': require('../../assets/images/exercises/One_Arm_Dumbbell_Row.jpg'),
  'One-Arm Flat Bench Dumbbell Flye': require('../../assets/images/exercises/One_Arm_Flat_Bench_Dumbbell_Flye.jpg'),
  'One-Arm High-Pulley Cable Side Bends': require('../../assets/images/exercises/One_Arm_High_Pulley_Cable_Side_Bends.jpg'),
  'One-Arm Incline Lateral Raise': require('../../assets/images/exercises/One_Arm_Incline_Lateral_Raise.jpg'),
  'One-Arm Kettlebell Clean': require('../../assets/images/exercises/One_Arm_Kettlebell_Clean.jpg'),
  'One-Arm Kettlebell Clean and Jerk': require('../../assets/images/exercises/One_Arm_Kettlebell_Clean_and_Jerk.jpg'),
  'One-Arm Kettlebell Floor Press': require('../../assets/images/exercises/One_Arm_Kettlebell_Floor_Press.jpg'),
  'One-Arm Kettlebell Jerk': require('../../assets/images/exercises/One_Arm_Kettlebell_Jerk.jpg'),
  'One-Arm Kettlebell Military Press To The Side': require('../../assets/images/exercises/One_Arm_Kettlebell_Military_Press_To_The_Side.jpg'),
  'One-Arm Kettlebell Para Press': require('../../assets/images/exercises/One_Arm_Kettlebell_Para_Press.jpg'),
  'One-Arm Kettlebell Push Press': require('../../assets/images/exercises/One_Arm_Kettlebell_Push_Press.jpg'),
  'One-Arm Kettlebell Row': require('../../assets/images/exercises/One_Arm_Kettlebell_Row.jpg'),
  'One-Arm Kettlebell Snatch': require('../../assets/images/exercises/One_Arm_Kettlebell_Snatch.jpg'),
  'One-Arm Kettlebell Split Jerk': require('../../assets/images/exercises/One_Arm_Kettlebell_Split_Jerk.jpg'),
  'One-Arm Kettlebell Split Snatch': require('../../assets/images/exercises/One_Arm_Kettlebell_Split_Snatch.jpg'),
  'One-Arm Kettlebell Swings': require('../../assets/images/exercises/One_Arm_Kettlebell_Swings.jpg'),
  'One-Arm Long Bar Row': require('../../assets/images/exercises/One_Arm_Long_Bar_Row.jpg'),
  'One-Arm Medicine Ball Slam': require('../../assets/images/exercises/One_Arm_Medicine_Ball_Slam.jpg'),
  'One-Arm Open Palm Kettlebell Clean': require('../../assets/images/exercises/One_Arm_Open_Palm_Kettlebell_Clean.jpg'),
  'One-Arm Overhead Kettlebell Squats': require('../../assets/images/exercises/One_Arm_Overhead_Kettlebell_Squats.jpg'),
  'One-Arm Side Deadlift': require('../../assets/images/exercises/One_Arm_Side_Deadlift.jpg'),
  'One-Arm Side Laterals': require('../../assets/images/exercises/One_Arm_Side_Laterals.jpg'),
  'One-Legged Cable Kickback': require('../../assets/images/exercises/One_Legged_Cable_Kickback.jpg'),
  'One Arm Against Wall': require('../../assets/images/exercises/One_Arm_Against_Wall.jpg'),
  'One Arm Chin-Up': require('../../assets/images/exercises/One_Arm_Chin_Up.jpg'),
  'One Arm Dumbbell Bench Press': require('../../assets/images/exercises/One_Arm_Dumbbell_Bench_Press.jpg'),
  'One Arm Dumbbell Preacher Curl': require('../../assets/images/exercises/One_Arm_Dumbbell_Preacher_Curl.jpg'),
  'One Arm Floor Press': require('../../assets/images/exercises/One_Arm_Floor_Press.jpg'),
  'One Arm Lat Pulldown': require('../../assets/images/exercises/One_Arm_Lat_Pulldown.jpg'),
  'One Arm Pronated Dumbbell Triceps Extension': require('../../assets/images/exercises/One_Arm_Pronated_Dumbbell_Triceps_Extension.jpg'),
  'One Arm Supinated Dumbbell Triceps Extension': require('../../assets/images/exercises/One_Arm_Supinated_Dumbbell_Triceps_Extension.jpg'),
  'One Half Locust': require('../../assets/images/exercises/One_Half_Locust.jpg'),
  'One Handed Hang': require('../../assets/images/exercises/One_Handed_Hang.jpg'),
  'One Knee To Chest': require('../../assets/images/exercises/One_Knee_To_Chest.jpg'),
  'One Leg Barbell Squat': require('../../assets/images/exercises/One_Leg_Barbell_Squat.jpg'),
  'Open Palm Kettlebell Clean': require('../../assets/images/exercises/Open_Palm_Kettlebell_Clean.jpg'),
  'Otis-Up': require('../../assets/images/exercises/Otis_Up.jpg'),
  'Overhead Cable Curl': require('../../assets/images/exercises/Overhead_Cable_Curl.jpg'),
  'Overhead Lat': require('../../assets/images/exercises/Overhead_Lat.jpg'),
  'Overhead Slam': require('../../assets/images/exercises/Overhead_Slam.jpg'),
  'Overhead Squat': require('../../assets/images/exercises/Overhead_Squat.jpg'),
  'Overhead Stretch': require('../../assets/images/exercises/Overhead_Stretch.jpg'),
  'Overhead Triceps': require('../../assets/images/exercises/Overhead_Triceps.jpg'),
  'Pallof Press': require('../../assets/images/exercises/Pallof_Press.jpg'),
  'Pallof Press With Rotation': require('../../assets/images/exercises/Pallof_Press_With_Rotation.jpg'),
  'Palms-Down Dumbbell Wrist Curl Over A Bench': require('../../assets/images/exercises/Palms_Down_Dumbbell_Wrist_Curl_Over_A_Bench.jpg'),
  'Palms-Down Wrist Curl Over A Bench': require('../../assets/images/exercises/Palms_Down_Wrist_Curl_Over_A_Bench.jpg'),
  'Palms-Up Barbell Wrist Curl Over A Bench': require('../../assets/images/exercises/Palms_Up_Barbell_Wrist_Curl_Over_A_Bench.jpg'),
  'Palms-Up Dumbbell Wrist Curl Over A Bench': require('../../assets/images/exercises/Palms_Up_Dumbbell_Wrist_Curl_Over_A_Bench.jpg'),
  'Parallel Bar Dip': require('../../assets/images/exercises/Parallel_Bar_Dip.jpg'),
  'Pelvic Tilt Into Bridge': require('../../assets/images/exercises/Pelvic_Tilt_Into_Bridge.jpg'),
  'Peroneals-SMR': require('../../assets/images/exercises/Peroneals_SMR.jpg'),
  'Peroneals Stretch': require('../../assets/images/exercises/Peroneals_Stretch.jpg'),
  'Physioball Hip Bridge': require('../../assets/images/exercises/Physioball_Hip_Bridge.jpg'),
  'Pin Presses': require('../../assets/images/exercises/Pin_Presses.jpg'),
  'Piriformis-SMR': require('../../assets/images/exercises/Piriformis_SMR.jpg'),
  'Plank': require('../../assets/images/exercises/Plank.jpg'),
  'Plate Pinch': require('../../assets/images/exercises/Plate_Pinch.jpg'),
  'Plate Twist': require('../../assets/images/exercises/Plate_Twist.jpg'),
  'Platform Hamstring Slides': require('../../assets/images/exercises/Platform_Hamstring_Slides.jpg'),
  'Plie Dumbbell Squat': require('../../assets/images/exercises/Plie_Dumbbell_Squat.jpg'),
  'Plyo Kettlebell Pushups': require('../../assets/images/exercises/Plyo_Kettlebell_Pushups.jpg'),
  'Plyo Push-up': require('../../assets/images/exercises/Plyo_Push_up.jpg'),
  'Posterior Tibialis Stretch': require('../../assets/images/exercises/Posterior_Tibialis_Stretch.jpg'),
  'Power Clean': require('../../assets/images/exercises/Power_Clean.jpg'),
  'Power Clean from Blocks': require('../../assets/images/exercises/Power_Clean_from_Blocks.jpg'),
  'Power Jerk': require('../../assets/images/exercises/Power_Jerk.jpg'),
  'Power Partials': require('../../assets/images/exercises/Power_Partials.jpg'),
  'Power Snatch': require('../../assets/images/exercises/Power_Snatch.jpg'),
  'Power Snatch from Blocks': require('../../assets/images/exercises/Power_Snatch_from_Blocks.jpg'),
  'Power Stairs': require('../../assets/images/exercises/Power_Stairs.jpg'),
  'Preacher Curl': require('../../assets/images/exercises/Preacher_Curl.jpg'),
  'Preacher Hammer Dumbbell Curl': require('../../assets/images/exercises/Preacher_Hammer_Dumbbell_Curl.jpg'),
  'Press Sit-Up': require('../../assets/images/exercises/Press_Sit_Up.jpg'),
  'Prone Manual Hamstring': require('../../assets/images/exercises/Prone_Manual_Hamstring.jpg'),
  'Prowler Sprint': require('../../assets/images/exercises/Prowler_Sprint.jpg'),
  'Pull Through': require('../../assets/images/exercises/Pull_Through.jpg'),
  'Pullups': require('../../assets/images/exercises/Pullups.jpg'),
  'Push-Up Wide': require('../../assets/images/exercises/Push_Up_Wide.jpg'),
  'Push-Ups - Close Triceps Position': require('../../assets/images/exercises/Push_Ups___Close_Triceps_Position.jpg'),
  'Push-Ups With Feet Elevated': require('../../assets/images/exercises/Push_Ups_With_Feet_Elevated.jpg'),
  'Push-Ups With Feet On An Exercise Ball': require('../../assets/images/exercises/Push_Ups_With_Feet_On_An_Exercise_Ball.jpg'),
  'Push Press': require('../../assets/images/exercises/Push_Press.jpg'),
  'Push Press - Behind the Neck': require('../../assets/images/exercises/Push_Press___Behind_the_Neck.jpg'),
  'Push Up to Side Plank': require('../../assets/images/exercises/Push_Up_to_Side_Plank.jpg'),
  'Pushups': require('../../assets/images/exercises/Pushups.jpg'),
  'Pushups (Close and Wide Hand Positions)': require('../../assets/images/exercises/Pushups_Close_and_Wide_Hand_Positions.jpg'),
  'Pyramid': require('../../assets/images/exercises/Pyramid.jpg'),
  'Quad Stretch': require('../../assets/images/exercises/Quad_Stretch.jpg'),
  'Quadriceps-SMR': require('../../assets/images/exercises/Quadriceps_SMR.jpg'),
  'Quick Leap': require('../../assets/images/exercises/Quick_Leap.jpg'),
  'Rack Delivery': require('../../assets/images/exercises/Rack_Delivery.jpg'),
  'Rack Pull with Bands': require('../../assets/images/exercises/Rack_Pull_with_Bands.jpg'),
  'Rack Pulls': require('../../assets/images/exercises/Rack_Pulls.jpg'),
  'Rear Leg Raises': require('../../assets/images/exercises/Rear_Leg_Raises.jpg'),
  'Recumbent Bike': require('../../assets/images/exercises/Recumbent_Bike.jpg'),
  'Return Push from Stance': require('../../assets/images/exercises/Return_Push_from_Stance.jpg'),
  'Reverse Band Bench Press': require('../../assets/images/exercises/Reverse_Band_Bench_Press.jpg'),
  'Reverse Band Box Squat': require('../../assets/images/exercises/Reverse_Band_Box_Squat.jpg'),
  'Reverse Band Deadlift': require('../../assets/images/exercises/Reverse_Band_Deadlift.jpg'),
  'Reverse Band Power Squat': require('../../assets/images/exercises/Reverse_Band_Power_Squat.jpg'),
  'Reverse Band Sumo Deadlift': require('../../assets/images/exercises/Reverse_Band_Sumo_Deadlift.jpg'),
  'Reverse Barbell Curl': require('../../assets/images/exercises/Reverse_Barbell_Curl.jpg'),
  'Reverse Barbell Preacher Curls': require('../../assets/images/exercises/Reverse_Barbell_Preacher_Curls.jpg'),
  'Reverse Cable Curl': require('../../assets/images/exercises/Reverse_Cable_Curl.jpg'),
  'Reverse Crunch': require('../../assets/images/exercises/Reverse_Crunch.jpg'),
  'Reverse Flyes': require('../../assets/images/exercises/Reverse_Flyes.jpg'),
  'Reverse Flyes With External Rotation': require('../../assets/images/exercises/Reverse_Flyes_With_External_Rotation.jpg'),
  'Reverse Grip Bent-Over Rows': require('../../assets/images/exercises/Reverse_Grip_Bent_Over_Rows.jpg'),
  'Reverse Grip Triceps Pushdown': require('../../assets/images/exercises/Reverse_Grip_Triceps_Pushdown.jpg'),
  'Reverse Hyperextension': require('../../assets/images/exercises/Reverse_Hyperextension.jpg'),
  'Reverse Machine Flyes': require('../../assets/images/exercises/Reverse_Machine_Flyes.jpg'),
  'Reverse Plate Curls': require('../../assets/images/exercises/Reverse_Plate_Curls.jpg'),
  'Reverse Triceps Bench Press': require('../../assets/images/exercises/Reverse_Triceps_Bench_Press.jpg'),
  'Rhomboids-SMR': require('../../assets/images/exercises/Rhomboids_SMR.jpg'),
  'Rickshaw Carry': require('../../assets/images/exercises/Rickshaw_Carry.jpg'),
  'Rickshaw Deadlift': require('../../assets/images/exercises/Rickshaw_Deadlift.jpg'),
  'Ring Dips': require('../../assets/images/exercises/Ring_Dips.jpg'),
  'Rocket Jump': require('../../assets/images/exercises/Rocket_Jump.jpg'),
  'Rocking Standing Calf Raise': require('../../assets/images/exercises/Rocking_Standing_Calf_Raise.jpg'),
  'Rocky Pull-Ups/Pulldowns': require('../../assets/images/exercises/Rocky_Pull_Ups_Pulldowns.jpg'),
  'Romanian Deadlift': require('../../assets/images/exercises/Romanian_Deadlift.jpg'),
  'Romanian Deadlift from Deficit': require('../../assets/images/exercises/Romanian_Deadlift_from_Deficit.jpg'),
  'Rope Climb': require('../../assets/images/exercises/Rope_Climb.jpg'),
  'Rope Crunch': require('../../assets/images/exercises/Rope_Crunch.jpg'),
  'Rope Jumping': require('../../assets/images/exercises/Rope_Jumping.jpg'),
  'Rope Straight-Arm Pulldown': require('../../assets/images/exercises/Rope_Straight_Arm_Pulldown.jpg'),
  'Round The World Shoulder Stretch': require('../../assets/images/exercises/Round_The_World_Shoulder_Stretch.jpg'),
  'Rowing, Stationary': require('../../assets/images/exercises/Rowing_Stationary.jpg'),
  'Runner\'s Stretch': require('../../assets/images/exercises/Runners_Stretch.jpg'),
  'Running, Treadmill': require('../../assets/images/exercises/Running_Treadmill.jpg'),
  'Russian Twist': require('../../assets/images/exercises/Russian_Twist.jpg'),
  'Sandbag Load': require('../../assets/images/exercises/Sandbag_Load.jpg'),
  'Scapular Pull-Up': require('../../assets/images/exercises/Scapular_Pull_Up.jpg'),
  'Scissor Kick': require('../../assets/images/exercises/Scissor_Kick.jpg'),
  'Scissors Jump': require('../../assets/images/exercises/Scissors_Jump.jpg'),
  'Seated Band Hamstring Curl': require('../../assets/images/exercises/Seated_Band_Hamstring_Curl.jpg'),
  'Seated Barbell Military Press': require('../../assets/images/exercises/Seated_Barbell_Military_Press.jpg'),
  'Seated Barbell Twist': require('../../assets/images/exercises/Seated_Barbell_Twist.jpg'),
  'Seated Bent-Over One-Arm Dumbbell Triceps Extension': require('../../assets/images/exercises/Seated_Bent_Over_One_Arm_Dumbbell_Triceps_Extension.jpg'),
  'Seated Bent-Over Rear Delt Raise': require('../../assets/images/exercises/Seated_Bent_Over_Rear_Delt_Raise.jpg'),
  'Seated Bent-Over Two-Arm Dumbbell Triceps Extension': require('../../assets/images/exercises/Seated_Bent_Over_Two_Arm_Dumbbell_Triceps_Extension.jpg'),
  'Seated Biceps': require('../../assets/images/exercises/Seated_Biceps.jpg'),
  'Seated Cable Rows': require('../../assets/images/exercises/Seated_Cable_Rows.jpg'),
  'Seated Cable Shoulder Press': require('../../assets/images/exercises/Seated_Cable_Shoulder_Press.jpg'),
  'Seated Calf Raise': require('../../assets/images/exercises/Seated_Calf_Raise.jpg'),
  'Seated Calf Stretch': require('../../assets/images/exercises/Seated_Calf_Stretch.jpg'),
  'Seated Close-Grip Concentration Barbell Curl': require('../../assets/images/exercises/Seated_Close_Grip_Concentration_Barbell_Curl.jpg'),
  'Seated Dumbbell Curl': require('../../assets/images/exercises/Seated_Dumbbell_Curl.jpg'),
  'Seated Dumbbell Inner Biceps Curl': require('../../assets/images/exercises/Seated_Dumbbell_Inner_Biceps_Curl.jpg'),
  'Seated Dumbbell Palms-Down Wrist Curl': require('../../assets/images/exercises/Seated_Dumbbell_Palms_Down_Wrist_Curl.jpg'),
  'Seated Dumbbell Palms-Up Wrist Curl': require('../../assets/images/exercises/Seated_Dumbbell_Palms_Up_Wrist_Curl.jpg'),
  'Seated Dumbbell Press': require('../../assets/images/exercises/Seated_Dumbbell_Press.jpg'),
  'Seated Flat Bench Leg Pull-In': require('../../assets/images/exercises/Seated_Flat_Bench_Leg_Pull_In.jpg'),
  'Seated Floor Hamstring Stretch': require('../../assets/images/exercises/Seated_Floor_Hamstring_Stretch.jpg'),
  'Seated Front Deltoid': require('../../assets/images/exercises/Seated_Front_Deltoid.jpg'),
  'Seated Glute': require('../../assets/images/exercises/Seated_Glute.jpg'),
  'Seated Good Mornings': require('../../assets/images/exercises/Seated_Good_Mornings.jpg'),
  'Seated Hamstring': require('../../assets/images/exercises/Seated_Hamstring.jpg'),
  'Seated Hamstring and Calf Stretch': require('../../assets/images/exercises/Seated_Hamstring_and_Calf_Stretch.jpg'),
  'Seated Head Harness Neck Resistance': require('../../assets/images/exercises/Seated_Head_Harness_Neck_Resistance.jpg'),
  'Seated Leg Curl': require('../../assets/images/exercises/Seated_Leg_Curl.jpg'),
  'Seated Leg Tucks': require('../../assets/images/exercises/Seated_Leg_Tucks.jpg'),
  'Seated One-Arm Dumbbell Palms-Down Wrist Curl': require('../../assets/images/exercises/Seated_One_Arm_Dumbbell_Palms_Down_Wrist_Curl.jpg'),
  'Seated One-Arm Dumbbell Palms-Up Wrist Curl': require('../../assets/images/exercises/Seated_One_Arm_Dumbbell_Palms_Up_Wrist_Curl.jpg'),
  'Seated One-arm Cable Pulley Rows': require('../../assets/images/exercises/Seated_One_arm_Cable_Pulley_Rows.jpg'),
  'Seated Overhead Stretch': require('../../assets/images/exercises/Seated_Overhead_Stretch.jpg'),
  'Seated Palm-Up Barbell Wrist Curl': require('../../assets/images/exercises/Seated_Palm_Up_Barbell_Wrist_Curl.jpg'),
  'Seated Palms-Down Barbell Wrist Curl': require('../../assets/images/exercises/Seated_Palms_Down_Barbell_Wrist_Curl.jpg'),
  'Seated Side Lateral Raise': require('../../assets/images/exercises/Seated_Side_Lateral_Raise.jpg'),
  'Seated Triceps Press': require('../../assets/images/exercises/Seated_Triceps_Press.jpg'),
  'Seated Two-Arm Palms-Up Low-Pulley Wrist Curl': require('../../assets/images/exercises/Seated_Two_Arm_Palms_Up_Low_Pulley_Wrist_Curl.jpg'),
  'See-Saw Press (Alternating Side Press)': require('../../assets/images/exercises/See_Saw_Press_Alternating_Side_Press.jpg'),
  'Shotgun Row': require('../../assets/images/exercises/Shotgun_Row.jpg'),
  'Shoulder Circles': require('../../assets/images/exercises/Shoulder_Circles.jpg'),
  'Shoulder Press - With Bands': require('../../assets/images/exercises/Shoulder_Press___With_Bands.jpg'),
  'Shoulder Raise': require('../../assets/images/exercises/Shoulder_Raise.jpg'),
  'Shoulder Stretch': require('../../assets/images/exercises/Shoulder_Stretch.jpg'),
  'Side-Lying Floor Stretch': require('../../assets/images/exercises/Side_Lying_Floor_Stretch.jpg'),
  'Side Bridge': require('../../assets/images/exercises/Side_Bridge.jpg'),
  'Side Hop-Sprint': require('../../assets/images/exercises/Side_Hop_Sprint.jpg'),
  'Side Jackknife': require('../../assets/images/exercises/Side_Jackknife.jpg'),
  'Side Lateral Raise': require('../../assets/images/exercises/Side_Lateral_Raise.jpg'),
  'Side Laterals to Front Raise': require('../../assets/images/exercises/Side_Laterals_to_Front_Raise.jpg'),
  'Side Leg Raises': require('../../assets/images/exercises/Side_Leg_Raises.jpg'),
  'Side Lying Groin Stretch': require('../../assets/images/exercises/Side_Lying_Groin_Stretch.jpg'),
  'Side Neck Stretch': require('../../assets/images/exercises/Side_Neck_Stretch.jpg'),
  'Side Standing Long Jump': require('../../assets/images/exercises/Side_Standing_Long_Jump.jpg'),
  'Side To Side Chins': require('../../assets/images/exercises/Side_To_Side_Chins.jpg'),
  'Side Wrist Pull': require('../../assets/images/exercises/Side_Wrist_Pull.jpg'),
  'Side to Side Box Shuffle': require('../../assets/images/exercises/Side_to_Side_Box_Shuffle.jpg'),
  'Single-Arm Cable Crossover': require('../../assets/images/exercises/Single_Arm_Cable_Crossover.jpg'),
  'Single-Arm Linear Jammer': require('../../assets/images/exercises/Single_Arm_Linear_Jammer.jpg'),
  'Single-Arm Push-Up': require('../../assets/images/exercises/Single_Arm_Push_Up.jpg'),
  'Single-Cone Sprint Drill': require('../../assets/images/exercises/Single_Cone_Sprint_Drill.jpg'),
  'Single-Leg High Box Squat': require('../../assets/images/exercises/Single_Leg_High_Box_Squat.jpg'),
  'Single-Leg Hop Progression': require('../../assets/images/exercises/Single_Leg_Hop_Progression.jpg'),
  'Single-Leg Lateral Hop': require('../../assets/images/exercises/Single_Leg_Lateral_Hop.jpg'),
  'Single-Leg Leg Extension': require('../../assets/images/exercises/Single_Leg_Leg_Extension.jpg'),
  'Single-Leg Stride Jump': require('../../assets/images/exercises/Single_Leg_Stride_Jump.jpg'),
  'Single Dumbbell Raise': require('../../assets/images/exercises/Single_Dumbbell_Raise.jpg'),
  'Single Leg Butt Kick': require('../../assets/images/exercises/Single_Leg_Butt_Kick.jpg'),
  'Single Leg Glute Bridge': require('../../assets/images/exercises/Single_Leg_Glute_Bridge.jpg'),
  'Single Leg Push-off': require('../../assets/images/exercises/Single_Leg_Push_off.jpg'),
  'Sit-Up': require('../../assets/images/exercises/Sit_Up.jpg'),
  'Sit Squats': require('../../assets/images/exercises/Sit_Squats.jpg'),
  'Skating': require('../../assets/images/exercises/Skating.jpg'),
  'Sled Drag - Harness': require('../../assets/images/exercises/Sled_Drag___Harness.jpg'),
  'Sled Overhead Backward Walk': require('../../assets/images/exercises/Sled_Overhead_Backward_Walk.jpg'),
  'Sled Overhead Triceps Extension': require('../../assets/images/exercises/Sled_Overhead_Triceps_Extension.jpg'),
  'Sled Push': require('../../assets/images/exercises/Sled_Push.jpg'),
  'Sled Reverse Flye': require('../../assets/images/exercises/Sled_Reverse_Flye.jpg'),
  'Sled Row': require('../../assets/images/exercises/Sled_Row.jpg'),
  'Sledgehammer Swings': require('../../assets/images/exercises/Sledgehammer_Swings.jpg'),
  'Smith Incline Shoulder Raise': require('../../assets/images/exercises/Smith_Incline_Shoulder_Raise.jpg'),
  'Smith Machine Behind the Back Shrug': require('../../assets/images/exercises/Smith_Machine_Behind_the_Back_Shrug.jpg'),
  'Smith Machine Bench Press': require('../../assets/images/exercises/Smith_Machine_Bench_Press.jpg'),
  'Smith Machine Bent Over Row': require('../../assets/images/exercises/Smith_Machine_Bent_Over_Row.jpg'),
  'Smith Machine Calf Raise': require('../../assets/images/exercises/Smith_Machine_Calf_Raise.jpg'),
  'Smith Machine Close-Grip Bench Press': require('../../assets/images/exercises/Smith_Machine_Close_Grip_Bench_Press.jpg'),
  'Smith Machine Decline Press': require('../../assets/images/exercises/Smith_Machine_Decline_Press.jpg'),
  'Smith Machine Hang Power Clean': require('../../assets/images/exercises/Smith_Machine_Hang_Power_Clean.jpg'),
  'Smith Machine Hip Raise': require('../../assets/images/exercises/Smith_Machine_Hip_Raise.jpg'),
  'Smith Machine Incline Bench Press': require('../../assets/images/exercises/Smith_Machine_Incline_Bench_Press.jpg'),
  'Smith Machine Leg Press': require('../../assets/images/exercises/Smith_Machine_Leg_Press.jpg'),
  'Smith Machine One-Arm Upright Row': require('../../assets/images/exercises/Smith_Machine_One_Arm_Upright_Row.jpg'),
  'Smith Machine Overhead Shoulder Press': require('../../assets/images/exercises/Smith_Machine_Overhead_Shoulder_Press.jpg'),
  'Smith Machine Pistol Squat': require('../../assets/images/exercises/Smith_Machine_Pistol_Squat.jpg'),
  'Smith Machine Reverse Calf Raises': require('../../assets/images/exercises/Smith_Machine_Reverse_Calf_Raises.jpg'),
  'Smith Machine Squat': require('../../assets/images/exercises/Smith_Machine_Squat.jpg'),
  'Smith Machine Stiff-Legged Deadlift': require('../../assets/images/exercises/Smith_Machine_Stiff_Legged_Deadlift.jpg'),
  'Smith Machine Upright Row': require('../../assets/images/exercises/Smith_Machine_Upright_Row.jpg'),
  'Smith Single-Leg Split Squat': require('../../assets/images/exercises/Smith_Single_Leg_Split_Squat.jpg'),
  'Snatch': require('../../assets/images/exercises/Snatch.jpg'),
  'Snatch Balance': require('../../assets/images/exercises/Snatch_Balance.jpg'),
  'Snatch Deadlift': require('../../assets/images/exercises/Snatch_Deadlift.jpg'),
  'Snatch Pull': require('../../assets/images/exercises/Snatch_Pull.jpg'),
  'Snatch Shrug': require('../../assets/images/exercises/Snatch_Shrug.jpg'),
  'Snatch from Blocks': require('../../assets/images/exercises/Snatch_from_Blocks.jpg'),
  'Speed Band Overhead Triceps': require('../../assets/images/exercises/Speed_Band_Overhead_Triceps.jpg'),
  'Speed Box Squat': require('../../assets/images/exercises/Speed_Box_Squat.jpg'),
  'Speed Squats': require('../../assets/images/exercises/Speed_Squats.jpg'),
  'Spell Caster': require('../../assets/images/exercises/Spell_Caster.jpg'),
  'Spider Crawl': require('../../assets/images/exercises/Spider_Crawl.jpg'),
  'Spider Curl': require('../../assets/images/exercises/Spider_Curl.jpg'),
  'Spinal Stretch': require('../../assets/images/exercises/Spinal_Stretch.jpg'),
  'Split Clean': require('../../assets/images/exercises/Split_Clean.jpg'),
  'Split Jerk': require('../../assets/images/exercises/Split_Jerk.jpg'),
  'Split Jump': require('../../assets/images/exercises/Split_Jump.jpg'),
  'Split Snatch': require('../../assets/images/exercises/Split_Snatch.jpg'),
  'Split Squat with Dumbbells': require('../../assets/images/exercises/Split_Squat_with_Dumbbells.jpg'),
  'Split Squats': require('../../assets/images/exercises/Split_Squats.jpg'),
  'Squat Jerk': require('../../assets/images/exercises/Squat_Jerk.jpg'),
  'Squat with Bands': require('../../assets/images/exercises/Squat_with_Bands.jpg'),
  'Squat with Chains': require('../../assets/images/exercises/Squat_with_Chains.jpg'),
  'Squat with Plate Movers': require('../../assets/images/exercises/Squat_with_Plate_Movers.jpg'),
  'Squats - With Bands': require('../../assets/images/exercises/Squats___With_Bands.jpg'),
  'Stairmaster': require('../../assets/images/exercises/Stairmaster.jpg'),
  'Standing Alternating Dumbbell Press': require('../../assets/images/exercises/Standing_Alternating_Dumbbell_Press.jpg'),
  'Standing Barbell Calf Raise': require('../../assets/images/exercises/Standing_Barbell_Calf_Raise.jpg'),
  'Standing Barbell Press Behind Neck': require('../../assets/images/exercises/Standing_Barbell_Press_Behind_Neck.jpg'),
  'Standing Bent-Over One-Arm Dumbbell Triceps Extension': require('../../assets/images/exercises/Standing_Bent_Over_One_Arm_Dumbbell_Triceps_Extension.jpg'),
  'Standing Bent-Over Two-Arm Dumbbell Triceps Extension': require('../../assets/images/exercises/Standing_Bent_Over_Two_Arm_Dumbbell_Triceps_Extension.jpg'),
  'Standing Biceps Cable Curl': require('../../assets/images/exercises/Standing_Biceps_Cable_Curl.jpg'),
  'Standing Biceps Stretch': require('../../assets/images/exercises/Standing_Biceps_Stretch.jpg'),
  'Standing Bradford Press': require('../../assets/images/exercises/Standing_Bradford_Press.jpg'),
  'Standing Cable Chest Press': require('../../assets/images/exercises/Standing_Cable_Chest_Press.jpg'),
  'Standing Cable Lift': require('../../assets/images/exercises/Standing_Cable_Lift.jpg'),
  'Standing Cable Wood Chop': require('../../assets/images/exercises/Standing_Cable_Wood_Chop.jpg'),
  'Standing Calf Raises': require('../../assets/images/exercises/Standing_Calf_Raises.jpg'),
  'Standing Concentration Curl': require('../../assets/images/exercises/Standing_Concentration_Curl.jpg'),
  'Standing Dumbbell Calf Raise': require('../../assets/images/exercises/Standing_Dumbbell_Calf_Raise.jpg'),
  'Standing Dumbbell Press': require('../../assets/images/exercises/Standing_Dumbbell_Press.jpg'),
  'Standing Dumbbell Reverse Curl': require('../../assets/images/exercises/Standing_Dumbbell_Reverse_Curl.jpg'),
  'Standing Dumbbell Straight-Arm Front Delt Raise Above Head': require('../../assets/images/exercises/Standing_Dumbbell_Straight_Arm_Front_Delt_Raise_Above_Head.jpg'),
  'Standing Dumbbell Triceps Extension': require('../../assets/images/exercises/Standing_Dumbbell_Triceps_Extension.jpg'),
  'Standing Dumbbell Upright Row': require('../../assets/images/exercises/Standing_Dumbbell_Upright_Row.jpg'),
  'Standing Elevated Quad Stretch': require('../../assets/images/exercises/Standing_Elevated_Quad_Stretch.jpg'),
  'Standing Front Barbell Raise Over Head': require('../../assets/images/exercises/Standing_Front_Barbell_Raise_Over_Head.jpg'),
  'Standing Gastrocnemius Calf Stretch': require('../../assets/images/exercises/Standing_Gastrocnemius_Calf_Stretch.jpg'),
  'Standing Hamstring and Calf Stretch': require('../../assets/images/exercises/Standing_Hamstring_and_Calf_Stretch.jpg'),
  'Standing Hip Circles': require('../../assets/images/exercises/Standing_Hip_Circles.jpg'),
  'Standing Hip Flexors': require('../../assets/images/exercises/Standing_Hip_Flexors.jpg'),
  'Standing Inner-Biceps Curl': require('../../assets/images/exercises/Standing_Inner_Biceps_Curl.jpg'),
  'Standing Lateral Stretch': require('../../assets/images/exercises/Standing_Lateral_Stretch.jpg'),
  'Standing Leg Curl': require('../../assets/images/exercises/Standing_Leg_Curl.jpg'),
  'Standing Long Jump': require('../../assets/images/exercises/Standing_Long_Jump.jpg'),
  'Standing Low-Pulley Deltoid Raise': require('../../assets/images/exercises/Standing_Low_Pulley_Deltoid_Raise.jpg'),
  'Standing Low-Pulley One-Arm Triceps Extension': require('../../assets/images/exercises/Standing_Low_Pulley_One_Arm_Triceps_Extension.jpg'),
  'Standing Military Press': require('../../assets/images/exercises/Standing_Military_Press.jpg'),
  'Standing Olympic Plate Hand Squeeze': require('../../assets/images/exercises/Standing_Olympic_Plate_Hand_Squeeze.jpg'),
  'Standing One-Arm Cable Curl': require('../../assets/images/exercises/Standing_One_Arm_Cable_Curl.jpg'),
  'Standing One-Arm Dumbbell Curl Over Incline Bench': require('../../assets/images/exercises/Standing_One_Arm_Dumbbell_Curl_Over_Incline_Bench.jpg'),
  'Standing One-Arm Dumbbell Triceps Extension': require('../../assets/images/exercises/Standing_One_Arm_Dumbbell_Triceps_Extension.jpg'),
  'Standing Overhead Barbell Triceps Extension': require('../../assets/images/exercises/Standing_Overhead_Barbell_Triceps_Extension.jpg'),
  'Standing Palm-In One-Arm Dumbbell Press': require('../../assets/images/exercises/Standing_Palm_In_One_Arm_Dumbbell_Press.jpg'),
  'Standing Palms-In Dumbbell Press': require('../../assets/images/exercises/Standing_Palms_In_Dumbbell_Press.jpg'),
  'Standing Palms-Up Barbell Behind The Back Wrist Curl': require('../../assets/images/exercises/Standing_Palms_Up_Barbell_Behind_The_Back_Wrist_Curl.jpg'),
  'Standing Pelvic Tilt': require('../../assets/images/exercises/Standing_Pelvic_Tilt.jpg'),
  'Standing Rope Crunch': require('../../assets/images/exercises/Standing_Rope_Crunch.jpg'),
  'Standing Soleus And Achilles Stretch': require('../../assets/images/exercises/Standing_Soleus_And_Achilles_Stretch.jpg'),
  'Standing Toe Touches': require('../../assets/images/exercises/Standing_Toe_Touches.jpg'),
  'Standing Towel Triceps Extension': require('../../assets/images/exercises/Standing_Towel_Triceps_Extension.jpg'),
  'Standing Two-Arm Overhead Throw': require('../../assets/images/exercises/Standing_Two_Arm_Overhead_Throw.jpg'),
  'Star Jump': require('../../assets/images/exercises/Star_Jump.jpg'),
  'Step-up with Knee Raise': require('../../assets/images/exercises/Step_up_with_Knee_Raise.jpg'),
  'Step Mill': require('../../assets/images/exercises/Step_Mill.jpg'),
  'Stiff-Legged Barbell Deadlift': require('../../assets/images/exercises/Stiff_Legged_Barbell_Deadlift.jpg'),
  'Stiff-Legged Dumbbell Deadlift': require('../../assets/images/exercises/Stiff_Legged_Dumbbell_Deadlift.jpg'),
  'Stiff Leg Barbell Good Morning': require('../../assets/images/exercises/Stiff_Leg_Barbell_Good_Morning.jpg'),
  'Stomach Vacuum': require('../../assets/images/exercises/Stomach_Vacuum.jpg'),
  'Straight-Arm Dumbbell Pullover': require('../../assets/images/exercises/Straight_Arm_Dumbbell_Pullover.jpg'),
  'Straight-Arm Pulldown': require('../../assets/images/exercises/Straight_Arm_Pulldown.jpg'),
  'Straight Bar Bench Mid Rows': require('../../assets/images/exercises/Straight_Bar_Bench_Mid_Rows.jpg'),
  'Straight Raises on Incline Bench': require('../../assets/images/exercises/Straight_Raises_on_Incline_Bench.jpg'),
  'Stride Jump Crossover': require('../../assets/images/exercises/Stride_Jump_Crossover.jpg'),
  'Sumo Deadlift': require('../../assets/images/exercises/Sumo_Deadlift.jpg'),
  'Sumo Deadlift with Bands': require('../../assets/images/exercises/Sumo_Deadlift_with_Bands.jpg'),
  'Sumo Deadlift with Chains': require('../../assets/images/exercises/Sumo_Deadlift_with_Chains.jpg'),
  'Superman': require('../../assets/images/exercises/Superman.jpg'),
  'Supine Chest Throw': require('../../assets/images/exercises/Supine_Chest_Throw.jpg'),
  'Supine One-Arm Overhead Throw': require('../../assets/images/exercises/Supine_One_Arm_Overhead_Throw.jpg'),
  'Supine Two-Arm Overhead Throw': require('../../assets/images/exercises/Supine_Two_Arm_Overhead_Throw.jpg'),
  'Suspended Fallout': require('../../assets/images/exercises/Suspended_Fallout.jpg'),
  'Suspended Push-Up': require('../../assets/images/exercises/Suspended_Push_Up.jpg'),
  'Suspended Reverse Crunch': require('../../assets/images/exercises/Suspended_Reverse_Crunch.jpg'),
  'Suspended Row': require('../../assets/images/exercises/Suspended_Row.jpg'),
  'Suspended Split Squat': require('../../assets/images/exercises/Suspended_Split_Squat.jpg'),
  'Svend Press': require('../../assets/images/exercises/Svend_Press.jpg'),
  'T-Bar Row with Handle': require('../../assets/images/exercises/T_Bar_Row_with_Handle.jpg'),
  'Tate Press': require('../../assets/images/exercises/Tate_Press.jpg'),
  'The Straddle': require('../../assets/images/exercises/The_Straddle.jpg'),
  'Thigh Abductor': require('../../assets/images/exercises/Thigh_Abductor.jpg'),
  'Thigh Adductor': require('../../assets/images/exercises/Thigh_Adductor.jpg'),
  'Tire Flip': require('../../assets/images/exercises/Tire_Flip.jpg'),
  'Toe Touchers': require('../../assets/images/exercises/Toe_Touchers.jpg'),
  'Torso Rotation': require('../../assets/images/exercises/Torso_Rotation.jpg'),
  'Trail Running/Walking': require('../../assets/images/exercises/Trail_Running_Walking.jpg'),
  'Trap Bar Deadlift': require('../../assets/images/exercises/Trap_Bar_Deadlift.jpg'),
  'Tricep Dumbbell Kickback': require('../../assets/images/exercises/Tricep_Dumbbell_Kickback.jpg'),
  'Tricep Side Stretch': require('../../assets/images/exercises/Tricep_Side_Stretch.jpg'),
  'Triceps Overhead Extension with Rope': require('../../assets/images/exercises/Triceps_Overhead_Extension_with_Rope.jpg'),
  'Triceps Pushdown': require('../../assets/images/exercises/Triceps_Pushdown.jpg'),
  'Triceps Pushdown - Rope Attachment': require('../../assets/images/exercises/Triceps_Pushdown___Rope_Attachment.jpg'),
  'Triceps Pushdown - V-Bar Attachment': require('../../assets/images/exercises/Triceps_Pushdown___V_Bar_Attachment.jpg'),
  'Triceps Stretch': require('../../assets/images/exercises/Triceps_Stretch.jpg'),
  'Tuck Crunch': require('../../assets/images/exercises/Tuck_Crunch.jpg'),
  'Two-Arm Dumbbell Preacher Curl': require('../../assets/images/exercises/Two_Arm_Dumbbell_Preacher_Curl.jpg'),
  'Two-Arm Kettlebell Clean': require('../../assets/images/exercises/Two_Arm_Kettlebell_Clean.jpg'),
  'Two-Arm Kettlebell Jerk': require('../../assets/images/exercises/Two_Arm_Kettlebell_Jerk.jpg'),
  'Two-Arm Kettlebell Military Press': require('../../assets/images/exercises/Two_Arm_Kettlebell_Military_Press.jpg'),
  'Two-Arm Kettlebell Row': require('../../assets/images/exercises/Two_Arm_Kettlebell_Row.jpg'),
  'Underhand Cable Pulldowns': require('../../assets/images/exercises/Underhand_Cable_Pulldowns.jpg'),
  'Upper Back-Leg Grab': require('../../assets/images/exercises/Upper_Back_Leg_Grab.jpg'),
  'Upper Back Stretch': require('../../assets/images/exercises/Upper_Back_Stretch.jpg'),
  'Upright Barbell Row': require('../../assets/images/exercises/Upright_Barbell_Row.jpg'),
  'Upright Cable Row': require('../../assets/images/exercises/Upright_Cable_Row.jpg'),
  'Upright Row - With Bands': require('../../assets/images/exercises/Upright_Row___With_Bands.jpg'),
  'Upward Stretch': require('../../assets/images/exercises/Upward_Stretch.jpg'),
  'V-Bar Pulldown': require('../../assets/images/exercises/V_Bar_Pulldown.jpg'),
  'V-Bar Pullup': require('../../assets/images/exercises/V_Bar_Pullup.jpg'),
  'Vertical Swing': require('../../assets/images/exercises/Vertical_Swing.jpg'),
  'Walking, Treadmill': require('../../assets/images/exercises/Walking_Treadmill.jpg'),
  'Weighted Ball Hyperextension': require('../../assets/images/exercises/Weighted_Ball_Hyperextension.jpg'),
  'Weighted Ball Side Bend': require('../../assets/images/exercises/Weighted_Ball_Side_Bend.jpg'),
  'Weighted Bench Dip': require('../../assets/images/exercises/Weighted_Bench_Dip.jpg'),
  'Weighted Crunches': require('../../assets/images/exercises/Weighted_Crunches.jpg'),
  'Weighted Jump Squat': require('../../assets/images/exercises/Weighted_Jump_Squat.jpg'),
  'Weighted Pull Ups': require('../../assets/images/exercises/Weighted_Pull_Ups.jpg'),
  'Weighted Sissy Squat': require('../../assets/images/exercises/Weighted_Sissy_Squat.jpg'),
  'Weighted Sit-Ups - With Bands': require('../../assets/images/exercises/Weighted_Sit_Ups___With_Bands.jpg'),
  'Weighted Squat': require('../../assets/images/exercises/Weighted_Squat.jpg'),
  'Wide-Grip Barbell Bench Press': require('../../assets/images/exercises/Wide_Grip_Barbell_Bench_Press.jpg'),
  'Wide-Grip Decline Barbell Bench Press': require('../../assets/images/exercises/Wide_Grip_Decline_Barbell_Bench_Press.jpg'),
  'Wide-Grip Decline Barbell Pullover': require('../../assets/images/exercises/Wide_Grip_Decline_Barbell_Pullover.jpg'),
  'Wide-Grip Lat Pulldown': require('../../assets/images/exercises/Wide_Grip_Lat_Pulldown.jpg'),
  'Wide-Grip Pulldown Behind The Neck': require('../../assets/images/exercises/Wide_Grip_Pulldown_Behind_The_Neck.jpg'),
  'Wide-Grip Rear Pull-Up': require('../../assets/images/exercises/Wide_Grip_Rear_Pull_Up.jpg'),
  'Wide-Grip Standing Barbell Curl': require('../../assets/images/exercises/Wide_Grip_Standing_Barbell_Curl.jpg'),
  'Wide Stance Barbell Squat': require('../../assets/images/exercises/Wide_Stance_Barbell_Squat.jpg'),
  'Wide Stance Stiff Legs': require('../../assets/images/exercises/Wide_Stance_Stiff_Legs.jpg'),
  'Wind Sprints': require('../../assets/images/exercises/Wind_Sprints.jpg'),
  'Windmills': require('../../assets/images/exercises/Windmills.jpg'),
  'World\'s Greatest Stretch': require('../../assets/images/exercises/Worlds_Greatest_Stretch.jpg'),
  'Wrist Circles': require('../../assets/images/exercises/Wrist_Circles.jpg'),
  'Wrist Roller': require('../../assets/images/exercises/Wrist_Roller.jpg'),
  'Wrist Rotations with Straight Bar': require('../../assets/images/exercises/Wrist_Rotations_with_Straight_Bar.jpg'),
  'Yoke Walk': require('../../assets/images/exercises/Yoke_Walk.jpg'),
  'Zercher Squats': require('../../assets/images/exercises/Zercher_Squats.jpg'),
  'Zottman Curl': require('../../assets/images/exercises/Zottman_Curl.jpg'),
  'Zottman Preacher Curl': require('../../assets/images/exercises/Zottman_Preacher_Curl.jpg'),
};
