// Généré par scripts/import-flexopedia.py — exercices Flexopedia (mobilité)

export type MobilityExercise = readonly [string, string, string, string];
// Tuple : [nom, difficulté, type, muscle]
export const MOBILITY_EXERCISES: readonly MobilityExercise[] = [
  ['90-90 Side Foot Lifts', 'All Levels', 'Active Dynamic', 'shoulders'],
  ['Active Lunge Rocks with a Band', 'Intermediate', 'Active Dynamic', 'quads'],
  ['Active Lunge Rocks with a Block', 'Intermediate', 'Active Dynamic', 'quads'],
  ['Active Side Bend', 'All Levels', 'Active Dynamic', 'back'],
  ['Active Straddle Hover', 'Intermediate', 'Active Static / Active Dynamic', 'hamstrings'],
  ['Alligator Arms Hug', 'All Levels', 'Passive Static', 'shoulders'],
  ['Angry Toddler\'s Pose', 'All Levels', 'Passive Static', 'back'],
  ['Arched Back Pike Leg Lifts', 'Intermediate', 'Active Dynamic', 'hamstrings'],
  ['Arched Back Supine Leg Lifts', 'Intermediate', 'Active Dynamic', 'hamstrings'],
  ['Arched Back Supine Leg Straightens', 'Intermediate', 'Active Dynamic', 'hamstrings'],
  ['Arm Across the Chest Stretch', 'All Levels', 'Passive Static', 'shoulders'],
  ['Arm Circles', 'All Levels', 'Active Dynamic', 'shoulders'],
  ['Arm Swings', 'All Levels', 'Active Dynamic', 'shoulders'],
  ['Awkward Sun Tan', 'All Levels', 'Active Static', 'shoulders'],
  ['Back Extensions', 'All Levels', 'Active Dynamic', 'back'],
  ['Back Extensions with Block Lift', 'All Levels', 'Active Dynamic', 'back'],
  ['Back Extensions with Elbow Squeeze', 'All Levels', 'Active Dynamic', 'back'],
  ['Back-To-Wall Standing Split', 'Intermediate', 'Static Active', 'hamstrings'],
  ['Banded Kneeling Lunge Foot Fishtails', 'All Levels', 'Active Dynamic', 'shoulders'],
  ['Seated Hip Internal Rotation with a Band', 'All Levels', 'Active Dynamic', 'shoulders'],
  ['Banded Spider Straddle Leg Opens', 'All Levels', 'Active Dynamic', 'shoulders'],
  ['Banded Windshield Wipers', 'All Levels', 'Active Dynamic', 'fullbody'],
  ['Banded Windshield Wipers with Knee Lift', 'All Levels', 'Active Dynamic', 'fullbody'],
  ['Block Lunge Lean Backs', 'Intermediate', '“Passive” Static', 'quads'],
  ['Bow Pose', 'All Levels', 'Active Static', 'quads'],
  ['Butt-to-Wall Straddle Pancake Leg Lifts', 'All Levels', 'Active Dynamic', 'shoulders'],
  ['Butterfly Stretch', 'All Levels', 'Passive Static', 'glutes'],
  ['Cat-Cow', 'All Levels', 'Active Dynamic', 'back'],
  ['Chicken Wing Elbow Circles', 'All Levels', 'Active Dynamic', 'shoulders'],
  ['Child\'s Pose', 'All Levels', 'Passive Static', 'back'],
  ['Child\'s Pose Arm Lifts', 'All Levels', 'Active Dynamic', 'shoulders'],
  ['Clamshells', 'All Levels', 'Active Dynamic', 'shoulders'],
  ['Couch Stretch', 'Intermediate', 'Passive Static', 'quads'],
  ['Cow Face Pose Elevator', 'All Levels', 'Active Static', 'shoulders'],
  ['Dippy Birds', 'All Levels', 'Dynamic Active', 'hamstrings'],
  ['Disco Cow', 'All Levels', 'Active Dynamic', 'back'],
  ['Dolphin Shoulder Shrugs', 'Intermediate', 'Active Dynamic', 'shoulders'],
  ['Donkey Kicks', 'All Levels', 'Active Dynamic', 'quads'],
  ['Downward Dog', 'All Levels', 'Static Passive', 'hamstrings'],
  ['Downward Dog Shoulder Shrugs', 'Intermediate', 'Active Dynamic', 'shoulders'],
  ['Eagle Arms', 'Intermediate', 'Passive Static', 'shoulders'],
  ['Ear to Shoulder Stretch', 'All Levels', 'Passive Static', 'shoulders'],
  ['Fire Hydrants', 'All Levels', 'Active Dynamic', 'glutes'],
  ['Fire Hydrants with Foot Drop', 'All Levels', 'Active Dynamic', 'shoulders'],
  ['Floaty Birds', 'Intermediate', 'Active Dynamic', 'back'],
  ['Forearm Cat-Cow', 'All Levels', 'Active Dynamic', 'back'],
  ['Forward Fold', 'All Levels', 'Static Passive', 'hamstrings'],
  ['Forward Fold Half Split Slides', 'All Levels', 'Active Dynamic', 'hamstrings'],
  ['Frogger Hip Rocks', 'All Levels', '“Passive” Dynamic', 'glutes'],
  ['Frogger Stretch', 'All Levels', 'Passive Static', 'glutes'],
  ['Front Split Hip Unsquare-to-Square Slides', 'All Levels', 'Active Dynamic', 'hamstrings'],
  ['Full Spine Side Bend', 'All Levels', 'Passive Static', 'back'],
  ['Good Mornings', 'All Levels', 'Dynamic Active', 'hamstrings'],
  ['Half Middle Split', 'All Levels', 'Passive Static', 'glutes'],
  ['Half Middle Split Adductor Contract-Relax (PNF)', 'All Levels', 'Active Static', 'glutes'],
  ['Half Middle Split Glute Contract-Relax (PNF)', 'All Levels', 'Active Static', 'glutes'],
  ['Half Frogger Glutes Contract-Relax (PNF)', 'All Levels', 'Active Dynamic', 'glutes'],
  ['Half Middle Split Leg Lifts & Slides', 'All Levels', 'Active Dynamic', 'glutes'],
  ['Half Middle Split Slides', 'All Levels', 'Active Dynamic', 'glutes'],
  ['Half Split Hip Unsquare-to-Square Slides', 'All Levels', 'Active Dynamic', 'hamstrings'],
  ['Half Split Leg Lifts', 'Intermediate', 'Active Dynamic', 'hamstrings'],
  ['Hero Pose', 'All Levels', 'Passive Static', 'quads'],
  ['High Cobra', 'All Levels', 'Passive* Static', 'back'],
  ['High Cobra Arm Lifts', 'All Levels', 'Active Dynamic', 'back'],
  ['High Cobra Cat-Cow', 'All Levels', 'Active Dynamic', 'back'],
  ['Hip Internal Rotation Knee Block Crunches', 'All Levels', 'Active Dynamic', 'shoulders'],
  ['Hips-on-Blocks Glutes Contract-Relax', 'All Levels', 'Static Active', 'quads'],
  ['Horse Stance', 'All Levels', 'Active Static', 'glutes'],
  ['Kneeling Hip Rotation', 'All Levels', 'Active Dynamic', 'shoulders'],
  ['Kneeling Lunge', 'All Levels', 'Passive Static', 'quads'],
  ['Kneeling Lunge Hip Flexor Contract-Relax (PNF)', 'All Levels', 'Active Static', 'quads'],
  ['Kneeling Lunge Quads Contract-Relax (PNF)', 'All Levels', 'Active Static', 'quads'],
  ['Kneeling Lunge with Side Bend', 'All Levels', 'Passive Static', 'quads'],
  ['Legs Up the Wall', 'All Levels', 'Static Passive', 'hamstrings'],
  ['Low Cobra', 'All Levels', 'Passive Static', 'back'],
  ['Low Cobra Arm Lifts', 'All Levels', 'Active Dynamic', 'back'],
  ['Low Lunge Hip Circles', 'All Levels', '“Active” Dynamic', 'quads'],
  ['Lunge Hip Unsquare-to-Square Slides', 'All Levels', 'Active Dynamic', 'quads'],
  ['Lunge Knee Taps', 'All Levels', 'Active Dynamic', 'quads'],
  ['Lunge with Hand-Supported Backbend', 'All Levels', '“Passive” Static', 'quads'],
  ['Middle Split', 'All Levels', 'Passive Static', 'glutes'],
  ['Open Sesames', 'All Levels', 'Passive Static', 'shoulders'],
  ['Overhead Shoulder Shrugs', 'All Levels', 'Active Dynamic', 'shoulders'],
  ['Pendulum Leg Swings', 'All Levels', 'Active Dynamic', 'shoulders'],
  ['Pigeon Pose', 'All Levels', 'Passive Static', 'shoulders'],
  ['Prone Block Push', 'Intermediate', 'Active Static', 'shoulders'],
  ['Prone Butt Kicks', 'All Levels', 'Active Dynamic', 'quads'],
  ['Prone Feet Opens', 'All Levels', 'Active Dynamic', 'shoulders'],
  ['Prone Foot Splay', 'All Levels', 'Passive Static', 'fullbody'],
  ['Prone Quad Stretch', 'All Levels', 'Passive Static', 'quads'],
  ['Prone Quad Contract-Relax (PNF)', 'All Levels', 'Active Static', 'quads'],
  ['Prone Strap-Assisted Shoulder External Rotation', 'All Levels', 'Passive Static', 'shoulders'],
  ['Puppy Pose', 'All Levels', 'Passive* Static', 'back'],
  ['Puppy Pose Active Press', 'All Levels', 'Active Static', 'back'],
  ['Pyramid Good Mornings', 'All Levels', 'Active Dynamic', 'hamstrings'],
  ['Quad-Focused Lunge Rocks', 'Intermediate', '“Passive” Dynamic*', 'quads'],
  ['Ragdoll Forward Fold', 'All Levels', 'Static Passive', 'hamstrings'],
  ['Rear Hand Clasp', 'All Levels', 'Passive Static', 'shoulders'],
  ['Reclined Quad Stretch', 'Intermediate', 'Passive Static', 'quads'],
  ['Reverse Clamshells', 'All Levels', 'Active Dynamic', 'shoulders'],
  ['Reverse Tabletop', 'All Levels', 'Active Static', 'shoulders'],
  ['Robot Arms', 'All Levels', 'Active Dynamix', 'shoulders'],
  ['Rounded Back Leg Extensions', 'All Levels', 'Dynamic Active', 'quads'],
  ['Scapular Push Ups', 'All Levels', 'Active Dynamic', 'shoulders'],
  ['Sciatic Nerve Glide', 'All Levels', 'Nerve Mobilization', 'hamstrings'],
  ['Seated Hip External Rotation with a Band', 'All Levels', 'Active Dynamic', 'shoulders'],
  ['Seated Twist', 'All Levels', 'Active Dynamic', 'back'],
  ['Seated Wall Straddle Pancake', 'All Levels', 'Passive Static', 'hamstrings'],
  ['Serving Cookies', 'All Levels', 'Active Dynamic', 'shoulders'],
  ['Shoulder Flossing', 'All Levels', 'Active Dynamic', 'shoulders'],
  ['Shoulder Protraction-Retraction Reaches', 'All Levels', 'Active Dynamic', 'shoulders'],
  ['Side-Lying Froggy Kicks', 'All Levels', 'Active Dynamic', 'hamstrings'],
  ['Side-Lying Leg Lifts', 'All Levels', 'Active Dynamic', 'hamstrings'],
  ['Sinking Ships', 'All Levels', 'Active Dynamic', 'back'],
  ['Sleeper Stretch', 'All Levels', 'Passive Static', 'shoulders'],
  ['Sleeper Stretch Contract-Relax', 'All Levels', 'Active static', 'shoulders'],
  ['Spidermans', 'All Levels', 'Active Dynamic', 'glutes'],
  ['Split Knee Straightens', 'Intermediate', 'Active Dynamic', 'quads'],
  ['Standing Active Twist', 'All Levels', 'Active Dynamic', 'back'],
  ['Standing Back Leg Lifts', 'All Levels', 'Active Dynamic', 'quads'],
  ['Standing End Range Leg Lifts', 'All Levels', 'Active Dynamic', 'hamstrings'],
  ['Standing End Range Side Leg Lifts', 'All Levels', 'Active Dynamic', 'hamstrings'],
  ['Standing Floppy Arm Twist', 'All Levels', 'Active Dynamic', 'back'],
  ['Standing Leg Lifts', 'All Levels', 'Active Dynamic', 'hamstrings'],
  ['Standing Lunge', 'All Levels', 'Passive Static', 'quads'],
  ['Standing Lunge Slides', 'All Levels', 'Active Dynamic', 'quads'],
  ['Standing Side Leg Lifts', 'All Levels', 'Active Dynamic', 'hamstrings'],
  ['Standing Split', 'Intermediate', 'Static Active', 'hamstrings'],
  ['Standing Split Kicks', 'All Levels', 'Dynamic Active', 'hamstrings'],
  ['Straddle Hip External Rotation with Band', 'All Levels', 'Active Dynamic', 'shoulders'],
  ['Straddle Leg Lifts', 'All Levels', 'Active Dynamic', 'hamstrings'],
  ['Straddle Leg Opens', 'All Levels', 'Active Dynamic', 'glutes'],
  ['Straddle Pancake', 'All Levels', 'Passive Static', 'hamstrings'],
  ['Straddle Pancake Leg Opens', 'All Levels', 'Active Dynamic', 'hamstrings'],
  ['Straddle Rainbow Leg Lifts', 'All Levels', 'Active Dynamic', 'hamstrings'],
  ['Straddle Side to Side Reaches', 'All Levels', 'Active Dynamic', 'hamstrings'],
  ['Strap-Assisted Floaty Birds', 'Intermediate', 'Active Dynamic', 'back'],
  ['Strap-Assisted Pitcher\'s Stretch', 'All Levels', 'Passive Static', 'shoulders'],
  ['Sumo Squat Knee Drops', 'All Levels', 'Active Dynamic', 'fullbody'],
  ['Sumo Squat Twist', 'All Levels', 'Passive Static', 'glutes'],
  ['Super Active Bow Pose', 'All Levels', 'Active Static', 'quads'],
  ['Supine Figure-4 Contract-Relax (Active Glutes)', 'All Levels', 'Passive Static', 'shoulders'],
  ['Supine Figure-4 Stretch', 'All Levels', 'Passive Static', 'glutes'],
  ['Supine Frogger Leg Opens', 'All Levels', 'Active Dynamic', 'glutes'],
  ['Supine Froggy Kicks', 'All Levels', 'Active Dynamic', 'hamstrings'],
  ['Supine Half Straddle Opens', 'All Levels', 'Active Dynamic', 'glutes'],
  ['Supine Hamstring Stretch', 'All Levels', 'Static Passive', 'hamstrings'],
  ['Supine Hamstring PNF (Hamstrings)', 'All Levels', 'Static Active', 'hamstrings'],
  ['Supine Hamstring PNF (Hip Flexors)', 'All Levels', 'Static Active', 'hamstrings'],
  ['Supine Leg Lifts', 'All Levels', 'Active Dynamic', 'hamstrings'],
  ['Supine Leg Lifts with Hips on Blocks', 'Intermediate', 'Active Dynamic', 'hamstrings'],
  ['Supine Toes-to-Wall Leg Extensions', 'Intermediate', 'Dynamic Active', 'hamstrings'],
  ['Supine Wall Straddle', 'All Levels', 'Passive Static', 'glutes'],
  ['Tabletop Side Crunches', 'All Levels', 'Active Dynamic', 'back'],
  ['Thoracic Side Bend', 'All Levels', 'Passive Static', 'back'],
  ['Three Legged Down Dog Banded Leg Extensions', 'Intermediate', 'Active Dynamic', 'hamstrings'],
  ['Three Legged Down Dog Leg Lifts', 'All Levels', 'Active Dynamic', 'hamstrings'],
  ['Wall Angels', 'All Levels', 'Active Dynamic', 'shoulders'],
  ['Wall Block Hitchikers', 'All Levels', 'Active Dynamic', 'shoulders'],
  ['Wall Chest Stretch', 'All Levels', 'Passive Static', 'shoulders'],
  ['Wall Chest Stretch Back Contract-Relax (PNF)', 'All Levels', 'Active Static', 'shoulders'],
  ['Wall Chest Stretch Pec Contract-Relax (PNF)', 'All Levels', 'Active Static', 'shoulders'],
  ['Wall Devils', 'All Levels', 'Active Dynamic', 'shoulders'],
  ['Wall Heel Slides', 'All Levels', 'Active Dynamic', 'hamstrings'],
  ['Wall Split Handstand Back Leg Pulses', 'Advanced', 'Active Dynamic', 'hamstrings'],
  ['Wall Split Handstand Front Leg Pulses', 'Advanced', 'Active Dynamic', 'hamstrings'],
  ['Wall Standing Split', 'Intermediate', 'Passive Static', 'hamstrings'],
  ['Wall Standing Split Kicks', 'Intermediate', 'Dynamic Active', 'hamstrings'],
  ['Wide Legged Good Mornings', 'All Levels', 'Active Dynamic', 'hamstrings'],
  ['Windmill Twist', 'All Levels', 'Passive* Dynamic', 'back'],
  ['Windshield Wipers', 'All Levels', '“Passive” Dynamic', 'fullbody'],
  ['Yogi Squat', 'All Levels', 'Passive Static', 'glutes'],
  ['Zombie Roll Ups', 'All Levels', 'Active Dynamic', 'back'],
];
