// Généré par scripts/import-flexopedia.py — images Flexopedia (Dani Winks Flexibility)

export const MOBILITY_IMAGES: Record<string, number> = {
  '90-90 Side Foot Lifts': require('../../assets/images/mobility/90_90_Side_Foot_Lifts.png'),
  'Active Lunge Rocks with a Band': require('../../assets/images/mobility/Active_Lunge_Rocks_with_a_Band.png'),
  'Active Lunge Rocks with a Block': require('../../assets/images/mobility/Active_Lunge_Rocks_with_a_Block.png'),
  'Active Side Bend': require('../../assets/images/mobility/Active_Side_Bend.png'),
  'Active Straddle Hover': require('../../assets/images/mobility/Active_Straddle_Hover.png'),
  'Alligator Arms Hug': require('../../assets/images/mobility/Alligator_Arms_Hug.png'),
  'Angry Toddler\'s Pose': require('../../assets/images/mobility/Angry_Toddler_s_Pose.png'),
  'Arched Back Pike Leg Lifts': require('../../assets/images/mobility/Arched_Back_Pike_Leg_Lifts.png'),
  'Arched Back Supine Leg Lifts': require('../../assets/images/mobility/Arched_Back_Supine_Leg_Lifts.png'),
  'Arched Back Supine Leg Straightens': require('../../assets/images/mobility/Arched_Back_Supine_Leg_Straightens.png'),
  'Arm Across the Chest Stretch': require('../../assets/images/mobility/Arm_Across_the_Chest_Stretch.png'),
  'Arm Circles': require('../../assets/images/mobility/Arm_Circles.png'),
  'Arm Swings': require('../../assets/images/mobility/Arm_Swings.png'),
  'Awkward Sun Tan': require('../../assets/images/mobility/Awkward_Sun_Tan.png'),
  'Back Extensions': require('../../assets/images/mobility/Back_Extensions.png'),
  'Back Extensions with Block Lift': require('../../assets/images/mobility/Back_Extensions_with_Block_Lift.png'),
  'Back Extensions with Elbow Squeeze': require('../../assets/images/mobility/Back_Extensions_with_Elbow_Squeeze.png'),
  'Back-To-Wall Standing Split': require('../../assets/images/mobility/Back_To_Wall_Standing_Split.png'),
  'Banded Kneeling Lunge Foot Fishtails': require('../../assets/images/mobility/Banded_Kneeling_Lunge_Foot_Fishtails.png'),
  'Banded Spider Straddle Leg Opens': require('../../assets/images/mobility/Banded_Spider_Straddle_Leg_Opens.png'),
  'Banded Windshield Wipers': require('../../assets/images/mobility/Banded_Windshield_Wipers.png'),
  'Banded Windshield Wipers with Knee Lift': require('../../assets/images/mobility/Banded_Windshield_Wipers_with_Knee_Lift.png'),
  'Block Lunge Lean Backs': require('../../assets/images/mobility/Block_Lunge_Lean_Backs.png'),
  'Bow Pose': require('../../assets/images/mobility/Bow_Pose.png'),
  'Butt-to-Wall Straddle Pancake Leg Lifts': require('../../assets/images/mobility/Butt_to_Wall_Straddle_Pancake_Leg_Lifts.png'),
  'Butterfly Stretch': require('../../assets/images/mobility/Butterfly_Stretch.png'),
  'Cat-Cow': require('../../assets/images/mobility/Cat_Cow.png'),
  'Chicken Wing Elbow Circles': require('../../assets/images/mobility/Chicken_Wing_Elbow_Circles.png'),
  'Child\'s Pose': require('../../assets/images/mobility/Child_s_Pose.png'),
  'Child\'s Pose Arm Lifts': require('../../assets/images/mobility/Child_s_Pose_Arm_Lifts.png'),
  'Clamshells': require('../../assets/images/mobility/Clamshells.png'),
  'Couch Stretch': require('../../assets/images/mobility/Couch_Stretch.png'),
  'Cow Face Pose Elevator': require('../../assets/images/mobility/Cow_Face_Pose_Elevator.png'),
  'Dippy Birds': require('../../assets/images/mobility/Dippy_Birds.png'),
  'Disco Cow': require('../../assets/images/mobility/Disco_Cow.png'),
  'Dolphin Shoulder Shrugs': require('../../assets/images/mobility/Dolphin_Shoulder_Shrugs.png'),
  'Donkey Kicks': require('../../assets/images/mobility/Donkey_Kicks.png'),
  'Downward Dog': require('../../assets/images/mobility/Downward_Dog.png'),
  'Downward Dog Shoulder Shrugs': require('../../assets/images/mobility/Downward_Dog_Shoulder_Shrugs.png'),
  'Eagle Arms': require('../../assets/images/mobility/Eagle_Arms.png'),
  'Ear to Shoulder Stretch': require('../../assets/images/mobility/Ear_to_Shoulder_Stretch.png'),
  'Fire Hydrants': require('../../assets/images/mobility/Fire_Hydrants.png'),
  'Fire Hydrants with Foot Drop': require('../../assets/images/mobility/Fire_Hydrants_with_Foot_Drop.png'),
  'Floaty Birds': require('../../assets/images/mobility/Floaty_Birds.png'),
  'Forearm Cat-Cow': require('../../assets/images/mobility/Forearm_Cat_Cow.png'),
  'Forward Fold': require('../../assets/images/mobility/Forward_Fold.png'),
  'Forward Fold Half Split Slides': require('../../assets/images/mobility/Forward_Fold_Half_Split_Slides.png'),
  'Frogger Hip Rocks': require('../../assets/images/mobility/Frogger_Hip_Rocks.png'),
  'Frogger Stretch': require('../../assets/images/mobility/Frogger_Stretch.png'),
  'Front Split Hip Unsquare-to-Square Slides': require('../../assets/images/mobility/Front_Split_Hip_Unsquare_to_Square_Slides.png'),
  'Full Spine Side Bend': require('../../assets/images/mobility/Full_Spine_Side_Bend.png'),
  'Good Mornings': require('../../assets/images/mobility/Good_Mornings.png'),
  'Half Frogger Glutes Contract-Relax (PNF)': require('../../assets/images/mobility/Half_Frogger_Glutes_Contract_Relax_PNF.png'),
  'Half Middle Split': require('../../assets/images/mobility/Half_Middle_Split.png'),
  'Half Middle Split Adductor Contract-Relax (PNF)': require('../../assets/images/mobility/Half_Middle_Split_Adductor_Contract_Relax_PNF.png'),
  'Half Middle Split Glute Contract-Relax (PNF)': require('../../assets/images/mobility/Half_Middle_Split_Glute_Contract_Relax_PNF.png'),
  'Half Middle Split Leg Lifts & Slides': require('../../assets/images/mobility/Half_Middle_Split_Leg_Lifts_Slides.png'),
  'Half Middle Split Slides': require('../../assets/images/mobility/Half_Middle_Split_Slides.png'),
  'Half Split Hip Unsquare-to-Square Slides': require('../../assets/images/mobility/Half_Split_Hip_Unsquare_to_Square_Slides.png'),
  'Half Split Leg Lifts': require('../../assets/images/mobility/Half_Split_Leg_Lifts.png'),
  'Hero Pose': require('../../assets/images/mobility/Hero_Pose.png'),
  'High Cobra': require('../../assets/images/mobility/High_Cobra.png'),
  'High Cobra Arm Lifts': require('../../assets/images/mobility/High_Cobra_Arm_Lifts.png'),
  'High Cobra Cat-Cow': require('../../assets/images/mobility/High_Cobra_Cat_Cow.png'),
  'Hip Internal Rotation Knee Block Crunches': require('../../assets/images/mobility/Hip_Internal_Rotation_Knee_Block_Crunches.png'),
  'Hips-on-Blocks Glutes Contract-Relax': require('../../assets/images/mobility/Hips_on_Blocks_Glutes_Contract_Relax.png'),
  'Horse Stance': require('../../assets/images/mobility/Horse_Stance.png'),
  'Kneeling Hip Rotation': require('../../assets/images/mobility/Kneeling_Hip_Rotation.png'),
  'Kneeling Lunge': require('../../assets/images/mobility/Kneeling_Lunge.png'),
  'Kneeling Lunge Hip Flexor Contract-Relax (PNF)': require('../../assets/images/mobility/Kneeling_Lunge_Hip_Flexor_Contract_Relax_PNF.png'),
  'Kneeling Lunge Quads Contract-Relax (PNF)': require('../../assets/images/mobility/Kneeling_Lunge_Quads_Contract_Relax_PNF.png'),
  'Kneeling Lunge with Side Bend': require('../../assets/images/mobility/Kneeling_Lunge_with_Side_Bend.png'),
  'Legs Up the Wall': require('../../assets/images/mobility/Legs_Up_the_Wall.png'),
  'Low Cobra': require('../../assets/images/mobility/Low_Cobra.png'),
  'Low Cobra Arm Lifts': require('../../assets/images/mobility/Low_Cobra_Arm_Lifts.png'),
  'Low Lunge Hip Circles': require('../../assets/images/mobility/Low_Lunge_Hip_Circles.png'),
  'Lunge Hip Unsquare-to-Square Slides': require('../../assets/images/mobility/Lunge_Hip_Unsquare_to_Square_Slides.png'),
  'Lunge Knee Taps': require('../../assets/images/mobility/Lunge_Knee_Taps.png'),
  'Lunge with Hand-Supported Backbend': require('../../assets/images/mobility/Lunge_with_Hand_Supported_Backbend.png'),
  'Middle Split': require('../../assets/images/mobility/Middle_Split.png'),
  'Open Sesames': require('../../assets/images/mobility/Open_Sesames.png'),
  'Overhead Shoulder Shrugs': require('../../assets/images/mobility/Overhead_Shoulder_Shrugs.png'),
  'Pendulum Leg Swings': require('../../assets/images/mobility/Pendulum_Leg_Swings.png'),
  'Pigeon Pose': require('../../assets/images/mobility/Pigeon_Pose.png'),
  'Prone Block Push': require('../../assets/images/mobility/Prone_Block_Push.png'),
  'Prone Butt Kicks': require('../../assets/images/mobility/Prone_Butt_Kicks.png'),
  'Prone Feet Opens': require('../../assets/images/mobility/Prone_Feet_Opens.png'),
  'Prone Foot Splay': require('../../assets/images/mobility/Prone_Foot_Splay.png'),
  'Prone Quad Contract-Relax (PNF)': require('../../assets/images/mobility/Prone_Quad_Contract_Relax_PNF.png'),
  'Prone Quad Stretch': require('../../assets/images/mobility/Prone_Quad_Stretch.png'),
  'Prone Strap-Assisted Shoulder External Rotation': require('../../assets/images/mobility/Prone_Strap_Assisted_Shoulder_External_Rotation.png'),
  'Puppy Pose': require('../../assets/images/mobility/Puppy_Pose.png'),
  'Puppy Pose Active Press': require('../../assets/images/mobility/Puppy_Pose_Active_Press.png'),
  'Pyramid Good Mornings': require('../../assets/images/mobility/Pyramid_Good_Mornings.png'),
  'Quad-Focused Lunge Rocks': require('../../assets/images/mobility/Quad_Focused_Lunge_Rocks.png'),
  'Ragdoll Forward Fold': require('../../assets/images/mobility/Ragdoll_Forward_Fold.png'),
  'Rear Hand Clasp': require('../../assets/images/mobility/Rear_Hand_Clasp.png'),
  'Reclined Quad Stretch': require('../../assets/images/mobility/Reclined_Quad_Stretch.png'),
  'Reverse Clamshells': require('../../assets/images/mobility/Reverse_Clamshells.png'),
  'Reverse Tabletop': require('../../assets/images/mobility/Reverse_Tabletop.png'),
  'Robot Arms': require('../../assets/images/mobility/Robot_Arms.png'),
  'Rounded Back Leg Extensions': require('../../assets/images/mobility/Rounded_Back_Leg_Extensions.png'),
  'Scapular Push Ups': require('../../assets/images/mobility/Scapular_Push_Ups.png'),
  'Sciatic Nerve Glide': require('../../assets/images/mobility/Sciatic_Nerve_Glide.png'),
  'Seated Hip External Rotation with a Band': require('../../assets/images/mobility/Seated_Hip_External_Rotation_with_a_Band.png'),
  'Seated Hip Internal Rotation with a Band': require('../../assets/images/mobility/Seated_Hip_Internal_Rotation_with_a_Band.png'),
  'Seated Twist': require('../../assets/images/mobility/Seated_Twist.png'),
  'Seated Wall Straddle Pancake': require('../../assets/images/mobility/Seated_Wall_Straddle_Pancake.png'),
  'Serving Cookies': require('../../assets/images/mobility/Serving_Cookies.png'),
  'Shoulder Flossing': require('../../assets/images/mobility/Shoulder_Flossing.png'),
  'Shoulder Protraction-Retraction Reaches': require('../../assets/images/mobility/Shoulder_Protraction_Retraction_Reaches.png'),
  'Side-Lying Froggy Kicks': require('../../assets/images/mobility/Side_Lying_Froggy_Kicks.png'),
  'Side-Lying Leg Lifts': require('../../assets/images/mobility/Side_Lying_Leg_Lifts.png'),
  'Sinking Ships': require('../../assets/images/mobility/Sinking_Ships.png'),
  'Sleeper Stretch': require('../../assets/images/mobility/Sleeper_Stretch.png'),
  'Sleeper Stretch Contract-Relax': require('../../assets/images/mobility/Sleeper_Stretch_Contract_Relax.png'),
  'Spidermans': require('../../assets/images/mobility/Spidermans.png'),
  'Split Knee Straightens': require('../../assets/images/mobility/Split_Knee_Straightens.png'),
  'Standing Active Twist': require('../../assets/images/mobility/Standing_Active_Twist.png'),
  'Standing Back Leg Lifts': require('../../assets/images/mobility/Standing_Back_Leg_Lifts.png'),
  'Standing End Range Leg Lifts': require('../../assets/images/mobility/Standing_End_Range_Leg_Lifts.png'),
  'Standing End Range Side Leg Lifts': require('../../assets/images/mobility/Standing_End_Range_Side_Leg_Lifts.png'),
  'Standing Floppy Arm Twist': require('../../assets/images/mobility/Standing_Floppy_Arm_Twist.png'),
  'Standing Leg Lifts': require('../../assets/images/mobility/Standing_Leg_Lifts.png'),
  'Standing Lunge': require('../../assets/images/mobility/Standing_Lunge.png'),
  'Standing Lunge Slides': require('../../assets/images/mobility/Standing_Lunge_Slides.png'),
  'Standing Side Leg Lifts': require('../../assets/images/mobility/Standing_Side_Leg_Lifts.png'),
  'Standing Split': require('../../assets/images/mobility/Standing_Split.png'),
  'Standing Split Kicks': require('../../assets/images/mobility/Standing_Split_Kicks.png'),
  'Straddle Hip External Rotation with Band': require('../../assets/images/mobility/Straddle_Hip_External_Rotation_with_Band.png'),
  'Straddle Leg Lifts': require('../../assets/images/mobility/Straddle_Leg_Lifts.png'),
  'Straddle Leg Opens': require('../../assets/images/mobility/Straddle_Leg_Opens.png'),
  'Straddle Pancake': require('../../assets/images/mobility/Straddle_Pancake.png'),
  'Straddle Pancake Leg Opens': require('../../assets/images/mobility/Straddle_Pancake_Leg_Opens.png'),
  'Straddle Rainbow Leg Lifts': require('../../assets/images/mobility/Straddle_Rainbow_Leg_Lifts.png'),
  'Straddle Side to Side Reaches': require('../../assets/images/mobility/Straddle_Side_to_Side_Reaches.png'),
  'Strap-Assisted Floaty Birds': require('../../assets/images/mobility/Strap_Assisted_Floaty_Birds.png'),
  'Strap-Assisted Pitcher\'s Stretch': require('../../assets/images/mobility/Strap_Assisted_Pitcher_s_Stretch.png'),
  'Sumo Squat Knee Drops': require('../../assets/images/mobility/Sumo_Squat_Knee_Drops.png'),
  'Sumo Squat Twist': require('../../assets/images/mobility/Sumo_Squat_Twist.png'),
  'Super Active Bow Pose': require('../../assets/images/mobility/Super_Active_Bow_Pose.png'),
  'Supine Figure-4 Contract-Relax (Active Glutes)': require('../../assets/images/mobility/Supine_Figure_4_Contract_Relax_Active_Glutes.png'),
  'Supine Figure-4 Stretch': require('../../assets/images/mobility/Supine_Figure_4_Stretch.png'),
  'Supine Frogger Leg Opens': require('../../assets/images/mobility/Supine_Frogger_Leg_Opens.png'),
  'Supine Froggy Kicks': require('../../assets/images/mobility/Supine_Froggy_Kicks.png'),
  'Supine Half Straddle Opens': require('../../assets/images/mobility/Supine_Half_Straddle_Opens.png'),
  'Supine Hamstring PNF (Hamstrings)': require('../../assets/images/mobility/Supine_Hamstring_PNF_Hamstrings.png'),
  'Supine Hamstring PNF (Hip Flexors)': require('../../assets/images/mobility/Supine_Hamstring_PNF_Hip_Flexors.png'),
  'Supine Hamstring Stretch': require('../../assets/images/mobility/Supine_Hamstring_Stretch.png'),
  'Supine Leg Lifts': require('../../assets/images/mobility/Supine_Leg_Lifts.png'),
  'Supine Leg Lifts with Hips on Blocks': require('../../assets/images/mobility/Supine_Leg_Lifts_with_Hips_on_Blocks.png'),
  'Supine Toes-to-Wall Leg Extensions': require('../../assets/images/mobility/Supine_Toes_to_Wall_Leg_Extensions.png'),
  'Supine Wall Straddle': require('../../assets/images/mobility/Supine_Wall_Straddle.png'),
  'Tabletop Side Crunches': require('../../assets/images/mobility/Tabletop_Side_Crunches.png'),
  'Thoracic Side Bend': require('../../assets/images/mobility/Thoracic_Side_Bend.png'),
  'Three Legged Down Dog Banded Leg Extensions': require('../../assets/images/mobility/Three_Legged_Down_Dog_Banded_Leg_Extensions.png'),
  'Three Legged Down Dog Leg Lifts': require('../../assets/images/mobility/Three_Legged_Down_Dog_Leg_Lifts.png'),
  'Wall Angels': require('../../assets/images/mobility/Wall_Angels.png'),
  'Wall Block Hitchikers': require('../../assets/images/mobility/Wall_Block_Hitchikers.png'),
  'Wall Chest Stretch': require('../../assets/images/mobility/Wall_Chest_Stretch.png'),
  'Wall Chest Stretch Back Contract-Relax (PNF)': require('../../assets/images/mobility/Wall_Chest_Stretch_Back_Contract_Relax_PNF.png'),
  'Wall Chest Stretch Pec Contract-Relax (PNF)': require('../../assets/images/mobility/Wall_Chest_Stretch_Pec_Contract_Relax_PNF.png'),
  'Wall Devils': require('../../assets/images/mobility/Wall_Devils.png'),
  'Wall Heel Slides': require('../../assets/images/mobility/Wall_Heel_Slides.png'),
  'Wall Split Handstand Back Leg Pulses': require('../../assets/images/mobility/Wall_Split_Handstand_Back_Leg_Pulses.png'),
  'Wall Split Handstand Front Leg Pulses': require('../../assets/images/mobility/Wall_Split_Handstand_Front_Leg_Pulses.png'),
  'Wall Standing Split': require('../../assets/images/mobility/Wall_Standing_Split.png'),
  'Wall Standing Split Kicks': require('../../assets/images/mobility/Wall_Standing_Split_Kicks.png'),
  'Wide Legged Good Mornings': require('../../assets/images/mobility/Wide_Legged_Good_Mornings.png'),
  'Windmill Twist': require('../../assets/images/mobility/Windmill_Twist.png'),
  'Windshield Wipers': require('../../assets/images/mobility/Windshield_Wipers.png'),
  'Yogi Squat': require('../../assets/images/mobility/Yogi_Squat.png'),
  'Zombie Roll Ups': require('../../assets/images/mobility/Zombie_Roll_Ups.png'),
};
