import type { Muscle, Equipment } from "./types";

// Généré par scripts/gen-seed.py depuis yuhonas/free-exercise-db (Unlicense)
export type SeedExercise = readonly [string, Muscle, Equipment];

export const SEED_EXERCISES: readonly SeedExercise[] = [
  ['3/4 Sit-Up', 'core', 'bodyweight'],
  ['90/90 Hamstring', 'hamstrings', 'bodyweight'],
  ['Ab Crunch Machine', 'core', 'machine'],
  ['Ab Roller', 'core', 'other'],
  ['Adductor', 'glutes', 'other'],
  ['Adductor/Groin', 'glutes', 'other'],
  ['Advanced Kettlebell Windmill', 'core', 'kettlebell'],
  ['Air Bike', 'core', 'bodyweight'],
  ['All Fours Quad Stretch', 'quads', 'bodyweight'],
  ['Alternate Hammer Curl', 'biceps', 'dumbbell'],
  ['Alternate Heel Touchers', 'core', 'bodyweight'],
  ['Alternate Incline Dumbbell Curl', 'biceps', 'dumbbell'],
  ['Alternate Leg Diagonal Bound', 'quads', 'other'],
  ['Alternating Cable Shoulder Press', 'shoulders', 'cable'],
  ['Alternating Deltoid Raise', 'shoulders', 'dumbbell'],
  ['Alternating Floor Press', 'chest', 'kettlebell'],
  ['Alternating Hang Clean', 'hamstrings', 'kettlebell'],
  ['Alternating Kettlebell Press', 'shoulders', 'kettlebell'],
  ['Alternating Kettlebell Row', 'back', 'kettlebell'],
  ['Alternating Renegade Row', 'back', 'kettlebell'],
  ['Ankle Circles', 'calves', 'other'],
  ['Ankle On The Knee', 'glutes', 'other'],
  ['Anterior Tibialis-SMR', 'calves', 'other'],
  ['Anti-Gravity Press', 'shoulders', 'barbell'],
  ['Arm Circles', 'shoulders', 'other'],
  ['Arnold Dumbbell Press', 'shoulders', 'dumbbell'],
  ['Around The Worlds', 'chest', 'dumbbell'],
  ['Atlas Stone Trainer', 'back', 'other'],
  ['Atlas Stones', 'back', 'other'],
  ['Axle Deadlift', 'back', 'other'],
  ['Back Flyes - With Bands', 'shoulders', 'band'],
  ['Backward Drag', 'quads', 'other'],
  ['Backward Medicine Ball Throw', 'shoulders', 'other'],
  ['Balance Board', 'calves', 'other'],
  ['Ball Leg Curl', 'hamstrings', 'other'],
  ['Band Assisted Pull-Up', 'back', 'other'],
  ['Band Good Morning', 'hamstrings', 'band'],
  ['Band Good Morning (Pull Through)', 'hamstrings', 'band'],
  ['Band Hip Adductions', 'glutes', 'band'],
  ['Band Pull Apart', 'shoulders', 'band'],
  ['Band Skull Crusher', 'triceps', 'band'],
  ['Barbell Ab Rollout', 'core', 'barbell'],
  ['Barbell Ab Rollout - On Knees', 'core', 'barbell'],
  ['Barbell Bench Press - Medium Grip', 'chest', 'barbell'],
  ['Barbell Curl', 'biceps', 'barbell'],
  ['Barbell Curls Lying Against An Incline', 'biceps', 'barbell'],
  ['Barbell Deadlift', 'back', 'barbell'],
  ['Barbell Full Squat', 'quads', 'barbell'],
  ['Barbell Glute Bridge', 'glutes', 'barbell'],
  ['Barbell Guillotine Bench Press', 'chest', 'barbell'],
  ['Barbell Hack Squat', 'quads', 'barbell'],
  ['Barbell Hip Thrust', 'glutes', 'barbell'],
  ['Barbell Incline Bench Press - Medium Grip', 'chest', 'barbell'],
  ['Barbell Incline Shoulder Raise', 'shoulders', 'barbell'],
  ['Barbell Lunge', 'quads', 'barbell'],
  ['Barbell Rear Delt Row', 'shoulders', 'barbell'],
  ['Barbell Rollout from Bench', 'core', 'barbell'],
  ['Barbell Seated Calf Raise', 'calves', 'barbell'],
  ['Barbell Shoulder Press', 'shoulders', 'barbell'],
  ['Barbell Shrug', 'traps', 'barbell'],
  ['Barbell Shrug Behind The Back', 'traps', 'barbell'],
  ['Barbell Side Bend', 'core', 'barbell'],
  ['Barbell Side Split Squat', 'quads', 'barbell'],
  ['Barbell Squat', 'quads', 'barbell'],
  ['Barbell Squat To A Bench', 'quads', 'barbell'],
  ['Barbell Step Ups', 'quads', 'barbell'],
  ['Barbell Walking Lunge', 'quads', 'barbell'],
  ['Battling Ropes', 'shoulders', 'other'],
  ['Bear Crawl Sled Drags', 'quads', 'other'],
  ['Behind Head Chest Stretch', 'chest', 'other'],
  ['Bench Dips', 'triceps', 'bodyweight'],
  ['Bench Jump', 'quads', 'bodyweight'],
  ['Bench Press - Powerlifting', 'triceps', 'barbell'],
  ['Bench Press - With Bands', 'chest', 'band'],
  ['Bench Press with Chains', 'triceps', 'barbell'],
  ['Bench Sprint', 'quads', 'other'],
  ['Bent-Arm Barbell Pullover', 'back', 'barbell'],
  ['Bent-Arm Dumbbell Pullover', 'chest', 'dumbbell'],
  ['Bent-Knee Hip Raise', 'core', 'bodyweight'],
  ['Bent Over Barbell Row', 'back', 'barbell'],
  ['Bent Over Dumbbell Rear Delt Raise With Head On Bench', 'shoulders', 'dumbbell'],
  ['Bent Over Low-Pulley Side Lateral', 'shoulders', 'cable'],
  ['Bent Over One-Arm Long Bar Row', 'back', 'barbell'],
  ['Bent Over Two-Arm Long Bar Row', 'back', 'barbell'],
  ['Bent Over Two-Dumbbell Row', 'back', 'dumbbell'],
  ['Bent Over Two-Dumbbell Row With Palms In', 'back', 'dumbbell'],
  ['Bent Press', 'core', 'kettlebell'],
  ['Bicycling', 'quads', 'other'],
  ['Bicycling, Stationary', 'quads', 'machine'],
  ['Board Press', 'triceps', 'barbell'],
  ['Body-Up', 'triceps', 'bodyweight'],
  ['Body Tricep Press', 'triceps', 'bodyweight'],
  ['Bodyweight Flyes', 'chest', 'barbell'],
  ['Bodyweight Mid Row', 'back', 'other'],
  ['Bodyweight Squat', 'quads', 'bodyweight'],
  ['Bodyweight Walking Lunge', 'quads', 'other'],
  ['Bosu Ball Cable Crunch With Side Bends', 'core', 'cable'],
  ['Bottoms-Up Clean From The Hang Position', 'forearms', 'kettlebell'],
  ['Bottoms Up', 'core', 'bodyweight'],
  ['Box Jump (Multiple Response)', 'hamstrings', 'other'],
  ['Box Skip', 'hamstrings', 'other'],
  ['Box Squat', 'quads', 'barbell'],
  ['Box Squat with Bands', 'quads', 'barbell'],
  ['Box Squat with Chains', 'quads', 'barbell'],
  ['Brachialis-SMR', 'biceps', 'other'],
  ['Bradford/Rocky Presses', 'shoulders', 'barbell'],
  ['Butt-Ups', 'core', 'bodyweight'],
  ['Butt Lift (Bridge)', 'glutes', 'bodyweight'],
  ['Butterfly', 'chest', 'machine'],
  ['Cable Chest Press', 'chest', 'cable'],
  ['Cable Crossover', 'chest', 'cable'],
  ['Cable Crunch', 'core', 'cable'],
  ['Cable Deadlifts', 'quads', 'cable'],
  ['Cable Hammer Curls - Rope Attachment', 'biceps', 'cable'],
  ['Cable Hip Adduction', 'quads', 'cable'],
  ['Cable Incline Pushdown', 'back', 'cable'],
  ['Cable Incline Triceps Extension', 'triceps', 'cable'],
  ['Cable Internal Rotation', 'shoulders', 'cable'],
  ['Cable Iron Cross', 'chest', 'cable'],
  ['Cable Judo Flip', 'core', 'cable'],
  ['Cable Lying Triceps Extension', 'triceps', 'cable'],
  ['Cable One Arm Tricep Extension', 'triceps', 'cable'],
  ['Cable Preacher Curl', 'biceps', 'cable'],
  ['Cable Rear Delt Fly', 'shoulders', 'cable'],
  ['Cable Reverse Crunch', 'core', 'cable'],
  ['Cable Rope Overhead Triceps Extension', 'triceps', 'cable'],
  ['Cable Rope Rear-Delt Rows', 'shoulders', 'cable'],
  ['Cable Russian Twists', 'core', 'cable'],
  ['Cable Seated Crunch', 'core', 'cable'],
  ['Cable Seated Lateral Raise', 'shoulders', 'cable'],
  ['Cable Shoulder Press', 'shoulders', 'cable'],
  ['Cable Shrugs', 'traps', 'cable'],
  ['Cable Wrist Curl', 'forearms', 'cable'],
  ['Calf-Machine Shoulder Shrug', 'traps', 'machine'],
  ['Calf Press', 'calves', 'machine'],
  ['Calf Press On The Leg Press Machine', 'calves', 'machine'],
  ['Calf Raise On A Dumbbell', 'calves', 'dumbbell'],
  ['Calf Raises - With Bands', 'calves', 'band'],
  ['Calf Stretch Elbows Against Wall', 'calves', 'other'],
  ['Calf Stretch Hands Against Wall', 'calves', 'other'],
  ['Calves-SMR', 'calves', 'other'],
  ['Car Deadlift', 'quads', 'other'],
  ['Car Drivers', 'shoulders', 'barbell'],
  ['Carioca Quick Step', 'glutes', 'other'],
  ['Cat Stretch', 'back', 'other'],
  ['Catch and Overhead Throw', 'back', 'other'],
  ['Chain Handle Extension', 'triceps', 'other'],
  ['Chain Press', 'chest', 'other'],
  ['Chair Leg Extended Stretch', 'hamstrings', 'other'],
  ['Chair Lower Back Stretch', 'back', 'other'],
  ['Chair Squat', 'quads', 'machine'],
  ['Chair Upper Body Stretch', 'shoulders', 'other'],
  ['Chest And Front Of Shoulder Stretch', 'chest', 'other'],
  ['Chest Push from 3 point stance', 'chest', 'other'],
  ['Chest Push (multiple response)', 'chest', 'other'],
  ['Chest Push (single response)', 'chest', 'other'],
  ['Chest Push with Run Release', 'chest', 'other'],
  ['Chest Stretch on Stability Ball', 'chest', 'other'],
  ['Child\'s Pose', 'back', 'other'],
  ['Chin-Up', 'back', 'bodyweight'],
  ['Chin To Chest Stretch', 'traps', 'other'],
  ['Circus Bell', 'shoulders', 'other'],
  ['Clean', 'hamstrings', 'barbell'],
  ['Clean Deadlift', 'hamstrings', 'barbell'],
  ['Clean Pull', 'quads', 'barbell'],
  ['Clean Shrug', 'traps', 'barbell'],
  ['Clean and Jerk', 'shoulders', 'barbell'],
  ['Clean and Press', 'shoulders', 'barbell'],
  ['Clean from Blocks', 'quads', 'barbell'],
  ['Clock Push-Up', 'chest', 'bodyweight'],
  ['Close-Grip Barbell Bench Press', 'triceps', 'barbell'],
  ['Close-Grip Dumbbell Press', 'triceps', 'dumbbell'],
  ['Close-Grip EZ-Bar Curl with Band', 'biceps', 'barbell'],
  ['Close-Grip EZ-Bar Press', 'triceps', 'barbell'],
  ['Close-Grip EZ Bar Curl', 'biceps', 'barbell'],
  ['Close-Grip Front Lat Pulldown', 'back', 'cable'],
  ['Close-Grip Push-Up off of a Dumbbell', 'triceps', 'bodyweight'],
  ['Close-Grip Standing Barbell Curl', 'biceps', 'barbell'],
  ['Cocoons', 'core', 'bodyweight'],
  ['Conan\'s Wheel', 'quads', 'other'],
  ['Concentration Curls', 'biceps', 'dumbbell'],
  ['Cross-Body Crunch', 'core', 'bodyweight'],
  ['Cross Body Hammer Curl', 'biceps', 'dumbbell'],
  ['Cross Over - With Bands', 'chest', 'band'],
  ['Crossover Reverse Lunge', 'back', 'other'],
  ['Crucifix', 'shoulders', 'other'],
  ['Crunch - Hands Overhead', 'core', 'bodyweight'],
  ['Crunch - Legs On Exercise Ball', 'core', 'bodyweight'],
  ['Crunches', 'core', 'bodyweight'],
  ['Cuban Press', 'shoulders', 'dumbbell'],
  ['Dancer\'s Stretch', 'back', 'other'],
  ['Dead Bug', 'core', 'bodyweight'],
  ['Deadlift with Bands', 'back', 'barbell'],
  ['Deadlift with Chains', 'back', 'barbell'],
  ['Decline Barbell Bench Press', 'chest', 'barbell'],
  ['Decline Close-Grip Bench To Skull Crusher', 'triceps', 'barbell'],
  ['Decline Crunch', 'core', 'bodyweight'],
  ['Decline Dumbbell Bench Press', 'chest', 'dumbbell'],
  ['Decline Dumbbell Flyes', 'chest', 'dumbbell'],
  ['Decline Dumbbell Triceps Extension', 'triceps', 'dumbbell'],
  ['Decline EZ Bar Triceps Extension', 'triceps', 'barbell'],
  ['Decline Oblique Crunch', 'core', 'bodyweight'],
  ['Decline Push-Up', 'chest', 'other'],
  ['Decline Reverse Crunch', 'core', 'bodyweight'],
  ['Decline Smith Press', 'chest', 'machine'],
  ['Deficit Deadlift', 'back', 'barbell'],
  ['Depth Jump Leap', 'quads', 'other'],
  ['Dip Machine', 'triceps', 'machine'],
  ['Dips - Chest Version', 'chest', 'other'],
  ['Dips - Triceps Version', 'triceps', 'bodyweight'],
  ['Donkey Calf Raises', 'calves', 'other'],
  ['Double Kettlebell Alternating Hang Clean', 'hamstrings', 'kettlebell'],
  ['Double Kettlebell Jerk', 'shoulders', 'kettlebell'],
  ['Double Kettlebell Push Press', 'shoulders', 'kettlebell'],
  ['Double Kettlebell Snatch', 'shoulders', 'kettlebell'],
  ['Double Kettlebell Windmill', 'core', 'kettlebell'],
  ['Double Leg Butt Kick', 'quads', 'bodyweight'],
  ['Downward Facing Balance', 'glutes', 'other'],
  ['Drag Curl', 'biceps', 'barbell'],
  ['Drop Push', 'chest', 'other'],
  ['Dumbbell Alternate Bicep Curl', 'biceps', 'dumbbell'],
  ['Dumbbell Bench Press', 'chest', 'dumbbell'],
  ['Dumbbell Bench Press with Neutral Grip', 'chest', 'dumbbell'],
  ['Dumbbell Bicep Curl', 'biceps', 'dumbbell'],
  ['Dumbbell Clean', 'hamstrings', 'dumbbell'],
  ['Dumbbell Floor Press', 'triceps', 'dumbbell'],
  ['Dumbbell Flyes', 'chest', 'dumbbell'],
  ['Dumbbell Incline Row', 'back', 'dumbbell'],
  ['Dumbbell Incline Shoulder Raise', 'shoulders', 'dumbbell'],
  ['Dumbbell Lunges', 'quads', 'dumbbell'],
  ['Dumbbell Lying One-Arm Rear Lateral Raise', 'shoulders', 'dumbbell'],
  ['Dumbbell Lying Pronation', 'forearms', 'dumbbell'],
  ['Dumbbell Lying Rear Lateral Raise', 'shoulders', 'dumbbell'],
  ['Dumbbell Lying Supination', 'forearms', 'dumbbell'],
  ['Dumbbell One-Arm Shoulder Press', 'shoulders', 'dumbbell'],
  ['Dumbbell One-Arm Triceps Extension', 'triceps', 'dumbbell'],
  ['Dumbbell One-Arm Upright Row', 'shoulders', 'dumbbell'],
  ['Dumbbell Prone Incline Curl', 'biceps', 'dumbbell'],
  ['Dumbbell Raise', 'shoulders', 'dumbbell'],
  ['Dumbbell Rear Lunge', 'quads', 'dumbbell'],
  ['Dumbbell Scaption', 'shoulders', 'dumbbell'],
  ['Dumbbell Seated Box Jump', 'quads', 'dumbbell'],
  ['Dumbbell Seated One-Leg Calf Raise', 'calves', 'dumbbell'],
  ['Dumbbell Shoulder Press', 'shoulders', 'dumbbell'],
  ['Dumbbell Shrug', 'traps', 'dumbbell'],
  ['Dumbbell Side Bend', 'core', 'dumbbell'],
  ['Dumbbell Squat', 'quads', 'dumbbell'],
  ['Dumbbell Squat To A Bench', 'quads', 'dumbbell'],
  ['Dumbbell Step Ups', 'quads', 'dumbbell'],
  ['Dumbbell Tricep Extension -Pronated Grip', 'triceps', 'dumbbell'],
  ['Dynamic Back Stretch', 'back', 'other'],
  ['Dynamic Chest Stretch', 'chest', 'other'],
  ['EZ-Bar Curl', 'biceps', 'barbell'],
  ['EZ-Bar Skullcrusher', 'triceps', 'barbell'],
  ['Elbow Circles', 'shoulders', 'other'],
  ['Elbow to Knee', 'core', 'bodyweight'],
  ['Elbows Back', 'chest', 'other'],
  ['Elevated Back Lunge', 'quads', 'barbell'],
  ['Elevated Cable Rows', 'back', 'cable'],
  ['Elliptical Trainer', 'quads', 'machine'],
  ['Exercise Ball Crunch', 'core', 'other'],
  ['Exercise Ball Pull-In', 'core', 'other'],
  ['Extended Range One-Arm Kettlebell Floor Press', 'chest', 'kettlebell'],
  ['External Rotation', 'shoulders', 'dumbbell'],
  ['External Rotation with Band', 'shoulders', 'band'],
  ['External Rotation with Cable', 'shoulders', 'cable'],
  ['Face Pull', 'shoulders', 'cable'],
  ['Farmer\'s Walk', 'forearms', 'other'],
  ['Fast Skipping', 'quads', 'bodyweight'],
  ['Finger Curls', 'forearms', 'barbell'],
  ['Flat Bench Cable Flyes', 'chest', 'cable'],
  ['Flat Bench Leg Pull-In', 'core', 'bodyweight'],
  ['Flat Bench Lying Leg Raise', 'core', 'bodyweight'],
  ['Flexor Incline Dumbbell Curls', 'biceps', 'dumbbell'],
  ['Floor Glute-Ham Raise', 'hamstrings', 'other'],
  ['Floor Press', 'triceps', 'barbell'],
  ['Floor Press with Chains', 'triceps', 'barbell'],
  ['Flutter Kicks', 'glutes', 'bodyweight'],
  ['Foot-SMR', 'calves', 'other'],
  ['Forward Drag with Press', 'chest', 'other'],
  ['Frankenstein Squat', 'quads', 'barbell'],
  ['Freehand Jump Squat', 'quads', 'bodyweight'],
  ['Frog Hops', 'quads', 'other'],
  ['Frog Sit-Ups', 'core', 'bodyweight'],
  ['Front Barbell Squat', 'quads', 'barbell'],
  ['Front Barbell Squat To A Bench', 'quads', 'barbell'],
  ['Front Box Jump', 'hamstrings', 'other'],
  ['Front Cable Raise', 'shoulders', 'cable'],
  ['Front Cone Hops (or hurdle hops)', 'quads', 'other'],
  ['Front Dumbbell Raise', 'shoulders', 'dumbbell'],
  ['Front Incline Dumbbell Raise', 'shoulders', 'dumbbell'],
  ['Front Leg Raises', 'hamstrings', 'bodyweight'],
  ['Front Plate Raise', 'shoulders', 'other'],
  ['Front Raise And Pullover', 'chest', 'barbell'],
  ['Front Squat (Clean Grip)', 'quads', 'barbell'],
  ['Front Squats With Two Kettlebells', 'quads', 'kettlebell'],
  ['Front Two-Dumbbell Raise', 'shoulders', 'dumbbell'],
  ['Full Range-Of-Motion Lat Pulldown', 'back', 'cable'],
  ['Gironda Sternum Chins', 'back', 'other'],
  ['Glute Ham Raise', 'hamstrings', 'machine'],
  ['Glute Kickback', 'glutes', 'bodyweight'],
  ['Goblet Squat', 'quads', 'kettlebell'],
  ['Good Morning', 'hamstrings', 'barbell'],
  ['Good Morning off Pins', 'hamstrings', 'barbell'],
  ['Gorilla Chin/Crunch', 'core', 'bodyweight'],
  ['Groin and Back Stretch', 'glutes', 'other'],
  ['Groiners', 'glutes', 'bodyweight'],
  ['Hack Squat', 'quads', 'machine'],
  ['Hammer Curls', 'biceps', 'dumbbell'],
  ['Hammer Grip Incline DB Bench Press', 'chest', 'dumbbell'],
  ['Hamstring-SMR', 'hamstrings', 'other'],
  ['Hamstring Stretch', 'hamstrings', 'other'],
  ['Handstand Push-Ups', 'shoulders', 'bodyweight'],
  ['Hang Clean', 'quads', 'barbell'],
  ['Hang Clean - Below the Knees', 'quads', 'barbell'],
  ['Hang Snatch', 'hamstrings', 'barbell'],
  ['Hang Snatch - Below Knees', 'hamstrings', 'barbell'],
  ['Hanging Bar Good Morning', 'hamstrings', 'barbell'],
  ['Hanging Leg Raise', 'core', 'bodyweight'],
  ['Hanging Pike', 'core', 'bodyweight'],
  ['Heaving Snatch Balance', 'quads', 'barbell'],
  ['Heavy Bag Thrust', 'chest', 'other'],
  ['High Cable Curls', 'biceps', 'cable'],
  ['Hip Circles (prone)', 'glutes', 'bodyweight'],
  ['Hip Extension with Bands', 'glutes', 'band'],
  ['Hip Flexion with Band', 'quads', 'band'],
  ['Hip Lift with Band', 'glutes', 'band'],
  ['Hug A Ball', 'back', 'other'],
  ['Hug Knees To Chest', 'back', 'other'],
  ['Hurdle Hops', 'hamstrings', 'other'],
  ['Hyperextensions (Back Extensions)', 'back', 'other'],
  ['Hyperextensions With No Hyperextension Bench', 'back', 'bodyweight'],
  ['IT Band and Glute Stretch', 'glutes', 'other'],
  ['Iliotibial Tract-SMR', 'glutes', 'other'],
  ['Inchworm', 'hamstrings', 'bodyweight'],
  ['Incline Barbell Triceps Extension', 'triceps', 'barbell'],
  ['Incline Bench Pull', 'back', 'barbell'],
  ['Incline Cable Chest Press', 'chest', 'cable'],
  ['Incline Cable Flye', 'chest', 'cable'],
  ['Incline Dumbbell Bench With Palms Facing In', 'chest', 'dumbbell'],
  ['Incline Dumbbell Curl', 'biceps', 'dumbbell'],
  ['Incline Dumbbell Flyes', 'chest', 'dumbbell'],
  ['Incline Dumbbell Flyes - With A Twist', 'chest', 'dumbbell'],
  ['Incline Dumbbell Press', 'chest', 'dumbbell'],
  ['Incline Hammer Curls', 'biceps', 'dumbbell'],
  ['Incline Inner Biceps Curl', 'biceps', 'dumbbell'],
  ['Incline Push-Up', 'chest', 'bodyweight'],
  ['Incline Push-Up Close-Grip', 'triceps', 'bodyweight'],
  ['Incline Push-Up Depth Jump', 'chest', 'other'],
  ['Incline Push-Up Medium', 'chest', 'bodyweight'],
  ['Incline Push-Up Reverse Grip', 'chest', 'bodyweight'],
  ['Incline Push-Up Wide', 'chest', 'bodyweight'],
  ['Intermediate Groin Stretch', 'hamstrings', 'other'],
  ['Intermediate Hip Flexor and Quad Stretch', 'quads', 'other'],
  ['Internal Rotation with Band', 'shoulders', 'band'],
  ['Inverted Row', 'back', 'other'],
  ['Inverted Row with Straps', 'back', 'other'],
  ['Iron Cross', 'shoulders', 'dumbbell'],
  ['Iron Crosses (stretch)', 'quads', 'other'],
  ['Isometric Chest Squeezes', 'chest', 'bodyweight'],
  ['Isometric Neck Exercise - Front And Back', 'traps', 'bodyweight'],
  ['Isometric Neck Exercise - Sides', 'traps', 'bodyweight'],
  ['Isometric Wipers', 'chest', 'bodyweight'],
  ['JM Press', 'triceps', 'barbell'],
  ['Jackknife Sit-Up', 'core', 'bodyweight'],
  ['Janda Sit-Up', 'core', 'bodyweight'],
  ['Jefferson Squats', 'quads', 'barbell'],
  ['Jerk Balance', 'shoulders', 'barbell'],
  ['Jerk Dip Squat', 'quads', 'barbell'],
  ['Jogging, Treadmill', 'quads', 'machine'],
  ['Keg Load', 'back', 'other'],
  ['Kettlebell Arnold Press', 'shoulders', 'kettlebell'],
  ['Kettlebell Dead Clean', 'hamstrings', 'kettlebell'],
  ['Kettlebell Figure 8', 'core', 'kettlebell'],
  ['Kettlebell Hang Clean', 'hamstrings', 'kettlebell'],
  ['Kettlebell One-Legged Deadlift', 'hamstrings', 'kettlebell'],
  ['Kettlebell Pass Between The Legs', 'core', 'kettlebell'],
  ['Kettlebell Pirate Ships', 'shoulders', 'kettlebell'],
  ['Kettlebell Pistol Squat', 'quads', 'kettlebell'],
  ['Kettlebell Seated Press', 'shoulders', 'kettlebell'],
  ['Kettlebell Seesaw Press', 'shoulders', 'kettlebell'],
  ['Kettlebell Sumo High Pull', 'traps', 'kettlebell'],
  ['Kettlebell Thruster', 'shoulders', 'kettlebell'],
  ['Kettlebell Turkish Get-Up (Lunge style)', 'shoulders', 'kettlebell'],
  ['Kettlebell Turkish Get-Up (Squat style)', 'shoulders', 'kettlebell'],
  ['Kettlebell Windmill', 'core', 'kettlebell'],
  ['Kipping Muscle Up', 'back', 'other'],
  ['Knee Across The Body', 'glutes', 'other'],
  ['Knee Circles', 'calves', 'bodyweight'],
  ['Knee/Hip Raise On Parallel Bars', 'core', 'other'],
  ['Knee Tuck Jump', 'hamstrings', 'bodyweight'],
  ['Kneeling Arm Drill', 'shoulders', 'other'],
  ['Kneeling Cable Crunch With Alternating Oblique Twists', 'core', 'cable'],
  ['Kneeling Cable Triceps Extension', 'triceps', 'cable'],
  ['Kneeling Forearm Stretch', 'forearms', 'other'],
  ['Kneeling High Pulley Row', 'back', 'cable'],
  ['Kneeling Hip Flexor', 'quads', 'other'],
  ['Kneeling Jump Squat', 'glutes', 'barbell'],
  ['Kneeling Single-Arm High Pulley Row', 'back', 'cable'],
  ['Kneeling Squat', 'glutes', 'barbell'],
  ['Landmine 180\'s', 'core', 'barbell'],
  ['Landmine Linear Jammer', 'shoulders', 'barbell'],
  ['Lateral Bound', 'glutes', 'bodyweight'],
  ['Lateral Box Jump', 'glutes', 'other'],
  ['Lateral Cone Hops', 'glutes', 'other'],
  ['Lateral Raise - With Bands', 'shoulders', 'band'],
  ['Latissimus Dorsi-SMR', 'back', 'other'],
  ['Leg-Over Floor Press', 'chest', 'kettlebell'],
  ['Leg-Up Hamstring Stretch', 'hamstrings', 'other'],
  ['Leg Extensions', 'quads', 'machine'],
  ['Leg Lift', 'glutes', 'bodyweight'],
  ['Leg Press', 'quads', 'machine'],
  ['Leg Pull-In', 'core', 'bodyweight'],
  ['Leverage Chest Press', 'chest', 'machine'],
  ['Leverage Deadlift', 'quads', 'machine'],
  ['Leverage Decline Chest Press', 'chest', 'machine'],
  ['Leverage High Row', 'back', 'machine'],
  ['Leverage Incline Chest Press', 'chest', 'machine'],
  ['Leverage Iso Row', 'back', 'machine'],
  ['Leverage Shoulder Press', 'shoulders', 'machine'],
  ['Leverage Shrug', 'traps', 'machine'],
  ['Linear 3-Part Start Technique', 'hamstrings', 'other'],
  ['Linear Acceleration Wall Drill', 'hamstrings', 'other'],
  ['Linear Depth Jump', 'quads', 'other'],
  ['Log Lift', 'shoulders', 'other'],
  ['London Bridges', 'back', 'other'],
  ['Looking At Ceiling', 'quads', 'other'],
  ['Low Cable Crossover', 'chest', 'cable'],
  ['Low Cable Triceps Extension', 'triceps', 'cable'],
  ['Low Pulley Row To Neck', 'shoulders', 'cable'],
  ['Lower Back-SMR', 'back', 'other'],
  ['Lower Back Curl', 'core', 'bodyweight'],
  ['Lunge Pass Through', 'hamstrings', 'kettlebell'],
  ['Lunge Sprint', 'quads', 'machine'],
  ['Lying Bent Leg Groin', 'glutes', 'other'],
  ['Lying Cable Curl', 'biceps', 'cable'],
  ['Lying Cambered Barbell Row', 'back', 'barbell'],
  ['Lying Close-Grip Bar Curl On High Pulley', 'biceps', 'cable'],
  ['Lying Close-Grip Barbell Triceps Extension Behind The Head', 'triceps', 'barbell'],
  ['Lying Close-Grip Barbell Triceps Press To Chin', 'triceps', 'barbell'],
  ['Lying Crossover', 'glutes', 'bodyweight'],
  ['Lying Dumbbell Tricep Extension', 'triceps', 'dumbbell'],
  ['Lying Face Down Plate Neck Resistance', 'traps', 'other'],
  ['Lying Face Up Plate Neck Resistance', 'traps', 'other'],
  ['Lying Glute', 'glutes', 'bodyweight'],
  ['Lying Hamstring', 'hamstrings', 'other'],
  ['Lying High Bench Barbell Curl', 'biceps', 'barbell'],
  ['Lying Leg Curls', 'hamstrings', 'machine'],
  ['Lying Machine Squat', 'quads', 'machine'],
  ['Lying One-Arm Lateral Raise', 'shoulders', 'dumbbell'],
  ['Lying Prone Quadriceps', 'quads', 'bodyweight'],
  ['Lying Rear Delt Raise', 'shoulders', 'dumbbell'],
  ['Lying Supine Dumbbell Curl', 'biceps', 'dumbbell'],
  ['Lying T-Bar Row', 'back', 'machine'],
  ['Lying Triceps Press', 'triceps', 'barbell'],
  ['Machine Bench Press', 'chest', 'machine'],
  ['Machine Bicep Curl', 'biceps', 'machine'],
  ['Machine Preacher Curls', 'biceps', 'machine'],
  ['Machine Shoulder (Military) Press', 'shoulders', 'machine'],
  ['Machine Triceps Extension', 'triceps', 'machine'],
  ['Medicine Ball Chest Pass', 'chest', 'other'],
  ['Medicine Ball Full Twist', 'core', 'other'],
  ['Medicine Ball Scoop Throw', 'shoulders', 'other'],
  ['Middle Back Shrug', 'back', 'dumbbell'],
  ['Middle Back Stretch', 'back', 'other'],
  ['Mixed Grip Chin', 'back', 'other'],
  ['Monster Walk', 'glutes', 'band'],
  ['Mountain Climbers', 'quads', 'other'],
  ['Moving Claw Series', 'hamstrings', 'other'],
  ['Muscle Snatch', 'hamstrings', 'barbell'],
  ['Muscle Up', 'back', 'other'],
  ['Narrow Stance Hack Squats', 'quads', 'machine'],
  ['Narrow Stance Leg Press', 'quads', 'machine'],
  ['Narrow Stance Squats', 'quads', 'barbell'],
  ['Natural Glute Ham Raise', 'hamstrings', 'bodyweight'],
  ['Neck-SMR', 'traps', 'other'],
  ['Neck Press', 'chest', 'barbell'],
  ['Oblique Crunches', 'core', 'bodyweight'],
  ['Oblique Crunches - On The Floor', 'core', 'bodyweight'],
  ['Olympic Squat', 'quads', 'barbell'],
  ['On-Your-Back Quad Stretch', 'quads', 'other'],
  ['On Your Side Quad Stretch', 'quads', 'other'],
  ['One-Arm Dumbbell Row', 'back', 'dumbbell'],
  ['One-Arm Flat Bench Dumbbell Flye', 'chest', 'dumbbell'],
  ['One-Arm High-Pulley Cable Side Bends', 'core', 'cable'],
  ['One-Arm Incline Lateral Raise', 'shoulders', 'dumbbell'],
  ['One-Arm Kettlebell Clean', 'hamstrings', 'kettlebell'],
  ['One-Arm Kettlebell Clean and Jerk', 'shoulders', 'kettlebell'],
  ['One-Arm Kettlebell Floor Press', 'chest', 'kettlebell'],
  ['One-Arm Kettlebell Jerk', 'shoulders', 'kettlebell'],
  ['One-Arm Kettlebell Military Press To The Side', 'shoulders', 'kettlebell'],
  ['One-Arm Kettlebell Para Press', 'shoulders', 'kettlebell'],
  ['One-Arm Kettlebell Push Press', 'shoulders', 'kettlebell'],
  ['One-Arm Kettlebell Row', 'back', 'kettlebell'],
  ['One-Arm Kettlebell Snatch', 'shoulders', 'kettlebell'],
  ['One-Arm Kettlebell Split Jerk', 'shoulders', 'kettlebell'],
  ['One-Arm Kettlebell Split Snatch', 'shoulders', 'kettlebell'],
  ['One-Arm Kettlebell Swings', 'hamstrings', 'kettlebell'],
  ['One-Arm Long Bar Row', 'back', 'barbell'],
  ['One-Arm Medicine Ball Slam', 'core', 'other'],
  ['One-Arm Open Palm Kettlebell Clean', 'hamstrings', 'kettlebell'],
  ['One-Arm Overhead Kettlebell Squats', 'quads', 'kettlebell'],
  ['One-Arm Side Deadlift', 'quads', 'barbell'],
  ['One-Arm Side Laterals', 'shoulders', 'dumbbell'],
  ['One-Legged Cable Kickback', 'glutes', 'cable'],
  ['One Arm Against Wall', 'back', 'other'],
  ['One Arm Chin-Up', 'back', 'other'],
  ['One Arm Dumbbell Bench Press', 'chest', 'dumbbell'],
  ['One Arm Dumbbell Preacher Curl', 'biceps', 'dumbbell'],
  ['One Arm Floor Press', 'triceps', 'barbell'],
  ['One Arm Lat Pulldown', 'back', 'cable'],
  ['One Arm Pronated Dumbbell Triceps Extension', 'triceps', 'dumbbell'],
  ['One Arm Supinated Dumbbell Triceps Extension', 'triceps', 'dumbbell'],
  ['One Half Locust', 'quads', 'other'],
  ['One Handed Hang', 'back', 'other'],
  ['One Knee To Chest', 'glutes', 'other'],
  ['One Leg Barbell Squat', 'quads', 'barbell'],
  ['Open Palm Kettlebell Clean', 'hamstrings', 'kettlebell'],
  ['Otis-Up', 'core', 'other'],
  ['Overhead Cable Curl', 'biceps', 'cable'],
  ['Overhead Lat', 'back', 'other'],
  ['Overhead Slam', 'back', 'other'],
  ['Overhead Squat', 'quads', 'barbell'],
  ['Overhead Stretch', 'core', 'other'],
  ['Overhead Triceps', 'triceps', 'bodyweight'],
  ['Pallof Press', 'core', 'cable'],
  ['Pallof Press With Rotation', 'core', 'cable'],
  ['Palms-Down Dumbbell Wrist Curl Over A Bench', 'forearms', 'dumbbell'],
  ['Palms-Down Wrist Curl Over A Bench', 'forearms', 'barbell'],
  ['Palms-Up Barbell Wrist Curl Over A Bench', 'forearms', 'barbell'],
  ['Palms-Up Dumbbell Wrist Curl Over A Bench', 'forearms', 'dumbbell'],
  ['Parallel Bar Dip', 'triceps', 'other'],
  ['Pelvic Tilt Into Bridge', 'back', 'other'],
  ['Peroneals-SMR', 'calves', 'other'],
  ['Peroneals Stretch', 'calves', 'other'],
  ['Physioball Hip Bridge', 'glutes', 'other'],
  ['Pin Presses', 'triceps', 'barbell'],
  ['Piriformis-SMR', 'glutes', 'other'],
  ['Plank', 'core', 'bodyweight'],
  ['Plate Pinch', 'forearms', 'other'],
  ['Plate Twist', 'core', 'other'],
  ['Platform Hamstring Slides', 'hamstrings', 'other'],
  ['Plie Dumbbell Squat', 'quads', 'dumbbell'],
  ['Plyo Kettlebell Pushups', 'chest', 'kettlebell'],
  ['Plyo Push-up', 'chest', 'bodyweight'],
  ['Posterior Tibialis Stretch', 'calves', 'other'],
  ['Power Clean', 'hamstrings', 'barbell'],
  ['Power Clean from Blocks', 'hamstrings', 'barbell'],
  ['Power Jerk', 'quads', 'barbell'],
  ['Power Partials', 'shoulders', 'dumbbell'],
  ['Power Snatch', 'hamstrings', 'barbell'],
  ['Power Snatch from Blocks', 'quads', 'barbell'],
  ['Power Stairs', 'hamstrings', 'other'],
  ['Preacher Curl', 'biceps', 'barbell'],
  ['Preacher Hammer Dumbbell Curl', 'biceps', 'dumbbell'],
  ['Press Sit-Up', 'core', 'barbell'],
  ['Prone Manual Hamstring', 'hamstrings', 'other'],
  ['Prowler Sprint', 'hamstrings', 'other'],
  ['Pull Through', 'glutes', 'cable'],
  ['Pullups', 'back', 'bodyweight'],
  ['Push-Up Wide', 'chest', 'bodyweight'],
  ['Push-Ups - Close Triceps Position', 'triceps', 'bodyweight'],
  ['Push-Ups With Feet Elevated', 'chest', 'bodyweight'],
  ['Push-Ups With Feet On An Exercise Ball', 'chest', 'other'],
  ['Push Press', 'shoulders', 'barbell'],
  ['Push Press - Behind the Neck', 'shoulders', 'barbell'],
  ['Push Up to Side Plank', 'chest', 'bodyweight'],
  ['Pushups', 'chest', 'bodyweight'],
  ['Pushups (Close and Wide Hand Positions)', 'chest', 'bodyweight'],
  ['Pyramid', 'back', 'other'],
  ['Quad Stretch', 'quads', 'other'],
  ['Quadriceps-SMR', 'quads', 'other'],
  ['Quick Leap', 'quads', 'other'],
  ['Rack Delivery', 'shoulders', 'barbell'],
  ['Rack Pull with Bands', 'back', 'barbell'],
  ['Rack Pulls', 'back', 'barbell'],
  ['Rear Leg Raises', 'quads', 'bodyweight'],
  ['Recumbent Bike', 'quads', 'machine'],
  ['Return Push from Stance', 'shoulders', 'other'],
  ['Reverse Band Bench Press', 'triceps', 'barbell'],
  ['Reverse Band Box Squat', 'quads', 'barbell'],
  ['Reverse Band Deadlift', 'back', 'barbell'],
  ['Reverse Band Power Squat', 'quads', 'barbell'],
  ['Reverse Band Sumo Deadlift', 'hamstrings', 'barbell'],
  ['Reverse Barbell Curl', 'biceps', 'barbell'],
  ['Reverse Barbell Preacher Curls', 'biceps', 'barbell'],
  ['Reverse Cable Curl', 'biceps', 'cable'],
  ['Reverse Crunch', 'core', 'bodyweight'],
  ['Reverse Flyes', 'shoulders', 'dumbbell'],
  ['Reverse Flyes With External Rotation', 'shoulders', 'dumbbell'],
  ['Reverse Grip Bent-Over Rows', 'back', 'barbell'],
  ['Reverse Grip Triceps Pushdown', 'triceps', 'cable'],
  ['Reverse Hyperextension', 'hamstrings', 'machine'],
  ['Reverse Machine Flyes', 'shoulders', 'machine'],
  ['Reverse Plate Curls', 'biceps', 'other'],
  ['Reverse Triceps Bench Press', 'triceps', 'barbell'],
  ['Rhomboids-SMR', 'back', 'other'],
  ['Rickshaw Carry', 'forearms', 'other'],
  ['Rickshaw Deadlift', 'quads', 'other'],
  ['Ring Dips', 'triceps', 'other'],
  ['Rocket Jump', 'quads', 'bodyweight'],
  ['Rocking Standing Calf Raise', 'calves', 'barbell'],
  ['Rocky Pull-Ups/Pulldowns', 'back', 'other'],
  ['Romanian Deadlift', 'hamstrings', 'barbell'],
  ['Romanian Deadlift from Deficit', 'hamstrings', 'barbell'],
  ['Rope Climb', 'back', 'other'],
  ['Rope Crunch', 'core', 'cable'],
  ['Rope Jumping', 'quads', 'other'],
  ['Rope Straight-Arm Pulldown', 'back', 'cable'],
  ['Round The World Shoulder Stretch', 'shoulders', 'other'],
  ['Rowing, Stationary', 'quads', 'machine'],
  ['Runner\'s Stretch', 'hamstrings', 'other'],
  ['Running, Treadmill', 'quads', 'machine'],
  ['Russian Twist', 'core', 'bodyweight'],
  ['Sandbag Load', 'quads', 'other'],
  ['Scapular Pull-Up', 'traps', 'other'],
  ['Scissor Kick', 'core', 'bodyweight'],
  ['Scissors Jump', 'quads', 'bodyweight'],
  ['Seated Band Hamstring Curl', 'hamstrings', 'other'],
  ['Seated Barbell Military Press', 'shoulders', 'barbell'],
  ['Seated Barbell Twist', 'core', 'barbell'],
  ['Seated Bent-Over One-Arm Dumbbell Triceps Extension', 'triceps', 'dumbbell'],
  ['Seated Bent-Over Rear Delt Raise', 'shoulders', 'dumbbell'],
  ['Seated Bent-Over Two-Arm Dumbbell Triceps Extension', 'triceps', 'dumbbell'],
  ['Seated Biceps', 'biceps', 'bodyweight'],
  ['Seated Cable Rows', 'back', 'cable'],
  ['Seated Cable Shoulder Press', 'shoulders', 'cable'],
  ['Seated Calf Raise', 'calves', 'machine'],
  ['Seated Calf Stretch', 'calves', 'other'],
  ['Seated Close-Grip Concentration Barbell Curl', 'biceps', 'barbell'],
  ['Seated Dumbbell Curl', 'biceps', 'dumbbell'],
  ['Seated Dumbbell Inner Biceps Curl', 'biceps', 'dumbbell'],
  ['Seated Dumbbell Palms-Down Wrist Curl', 'forearms', 'dumbbell'],
  ['Seated Dumbbell Palms-Up Wrist Curl', 'forearms', 'dumbbell'],
  ['Seated Dumbbell Press', 'shoulders', 'dumbbell'],
  ['Seated Flat Bench Leg Pull-In', 'core', 'bodyweight'],
  ['Seated Floor Hamstring Stretch', 'hamstrings', 'other'],
  ['Seated Front Deltoid', 'shoulders', 'bodyweight'],
  ['Seated Glute', 'glutes', 'bodyweight'],
  ['Seated Good Mornings', 'back', 'barbell'],
  ['Seated Hamstring', 'hamstrings', 'other'],
  ['Seated Hamstring and Calf Stretch', 'hamstrings', 'other'],
  ['Seated Head Harness Neck Resistance', 'traps', 'other'],
  ['Seated Leg Curl', 'hamstrings', 'machine'],
  ['Seated Leg Tucks', 'core', 'bodyweight'],
  ['Seated One-Arm Dumbbell Palms-Down Wrist Curl', 'forearms', 'dumbbell'],
  ['Seated One-Arm Dumbbell Palms-Up Wrist Curl', 'forearms', 'dumbbell'],
  ['Seated One-arm Cable Pulley Rows', 'back', 'cable'],
  ['Seated Overhead Stretch', 'core', 'other'],
  ['Seated Palm-Up Barbell Wrist Curl', 'forearms', 'barbell'],
  ['Seated Palms-Down Barbell Wrist Curl', 'forearms', 'barbell'],
  ['Seated Side Lateral Raise', 'shoulders', 'dumbbell'],
  ['Seated Triceps Press', 'triceps', 'dumbbell'],
  ['Seated Two-Arm Palms-Up Low-Pulley Wrist Curl', 'forearms', 'cable'],
  ['See-Saw Press (Alternating Side Press)', 'shoulders', 'dumbbell'],
  ['Shotgun Row', 'back', 'cable'],
  ['Shoulder Circles', 'shoulders', 'other'],
  ['Shoulder Press - With Bands', 'shoulders', 'band'],
  ['Shoulder Raise', 'shoulders', 'other'],
  ['Shoulder Stretch', 'shoulders', 'other'],
  ['Side-Lying Floor Stretch', 'back', 'other'],
  ['Side Bridge', 'core', 'bodyweight'],
  ['Side Hop-Sprint', 'quads', 'other'],
  ['Side Jackknife', 'core', 'bodyweight'],
  ['Side Lateral Raise', 'shoulders', 'dumbbell'],
  ['Side Laterals to Front Raise', 'shoulders', 'dumbbell'],
  ['Side Leg Raises', 'glutes', 'bodyweight'],
  ['Side Lying Groin Stretch', 'glutes', 'other'],
  ['Side Neck Stretch', 'traps', 'other'],
  ['Side Standing Long Jump', 'quads', 'other'],
  ['Side To Side Chins', 'back', 'other'],
  ['Side Wrist Pull', 'shoulders', 'other'],
  ['Side to Side Box Shuffle', 'quads', 'other'],
  ['Single-Arm Cable Crossover', 'chest', 'cable'],
  ['Single-Arm Linear Jammer', 'shoulders', 'barbell'],
  ['Single-Arm Push-Up', 'chest', 'bodyweight'],
  ['Single-Cone Sprint Drill', 'quads', 'other'],
  ['Single-Leg High Box Squat', 'quads', 'other'],
  ['Single-Leg Hop Progression', 'quads', 'other'],
  ['Single-Leg Lateral Hop', 'quads', 'other'],
  ['Single-Leg Leg Extension', 'quads', 'machine'],
  ['Single-Leg Stride Jump', 'quads', 'other'],
  ['Single Dumbbell Raise', 'shoulders', 'dumbbell'],
  ['Single Leg Butt Kick', 'quads', 'bodyweight'],
  ['Single Leg Glute Bridge', 'glutes', 'bodyweight'],
  ['Single Leg Push-off', 'quads', 'other'],
  ['Sit-Up', 'core', 'bodyweight'],
  ['Sit Squats', 'quads', 'other'],
  ['Skating', 'quads', 'other'],
  ['Sled Drag - Harness', 'quads', 'other'],
  ['Sled Overhead Backward Walk', 'shoulders', 'other'],
  ['Sled Overhead Triceps Extension', 'triceps', 'other'],
  ['Sled Push', 'quads', 'other'],
  ['Sled Reverse Flye', 'shoulders', 'other'],
  ['Sled Row', 'back', 'other'],
  ['Sledgehammer Swings', 'core', 'other'],
  ['Smith Incline Shoulder Raise', 'shoulders', 'barbell'],
  ['Smith Machine Behind the Back Shrug', 'traps', 'machine'],
  ['Smith Machine Bench Press', 'chest', 'machine'],
  ['Smith Machine Bent Over Row', 'back', 'machine'],
  ['Smith Machine Calf Raise', 'calves', 'machine'],
  ['Smith Machine Close-Grip Bench Press', 'triceps', 'machine'],
  ['Smith Machine Decline Press', 'chest', 'machine'],
  ['Smith Machine Hang Power Clean', 'hamstrings', 'machine'],
  ['Smith Machine Hip Raise', 'core', 'machine'],
  ['Smith Machine Incline Bench Press', 'chest', 'machine'],
  ['Smith Machine Leg Press', 'quads', 'machine'],
  ['Smith Machine One-Arm Upright Row', 'shoulders', 'machine'],
  ['Smith Machine Overhead Shoulder Press', 'shoulders', 'machine'],
  ['Smith Machine Pistol Squat', 'quads', 'machine'],
  ['Smith Machine Reverse Calf Raises', 'calves', 'machine'],
  ['Smith Machine Squat', 'quads', 'machine'],
  ['Smith Machine Stiff-Legged Deadlift', 'hamstrings', 'machine'],
  ['Smith Machine Upright Row', 'traps', 'machine'],
  ['Smith Single-Leg Split Squat', 'quads', 'machine'],
  ['Snatch', 'quads', 'barbell'],
  ['Snatch Balance', 'quads', 'barbell'],
  ['Snatch Deadlift', 'hamstrings', 'barbell'],
  ['Snatch Pull', 'hamstrings', 'barbell'],
  ['Snatch Shrug', 'traps', 'barbell'],
  ['Snatch from Blocks', 'quads', 'barbell'],
  ['Speed Band Overhead Triceps', 'triceps', 'band'],
  ['Speed Box Squat', 'quads', 'barbell'],
  ['Speed Squats', 'quads', 'barbell'],
  ['Spell Caster', 'core', 'dumbbell'],
  ['Spider Crawl', 'core', 'bodyweight'],
  ['Spider Curl', 'biceps', 'barbell'],
  ['Spinal Stretch', 'back', 'other'],
  ['Split Clean', 'quads', 'barbell'],
  ['Split Jerk', 'quads', 'barbell'],
  ['Split Jump', 'quads', 'bodyweight'],
  ['Split Snatch', 'hamstrings', 'barbell'],
  ['Split Squat with Dumbbells', 'quads', 'dumbbell'],
  ['Split Squats', 'hamstrings', 'other'],
  ['Squat Jerk', 'quads', 'barbell'],
  ['Squat with Bands', 'quads', 'barbell'],
  ['Squat with Chains', 'quads', 'barbell'],
  ['Squat with Plate Movers', 'quads', 'barbell'],
  ['Squats - With Bands', 'quads', 'band'],
  ['Stairmaster', 'quads', 'machine'],
  ['Standing Alternating Dumbbell Press', 'shoulders', 'dumbbell'],
  ['Standing Barbell Calf Raise', 'calves', 'barbell'],
  ['Standing Barbell Press Behind Neck', 'shoulders', 'barbell'],
  ['Standing Bent-Over One-Arm Dumbbell Triceps Extension', 'triceps', 'dumbbell'],
  ['Standing Bent-Over Two-Arm Dumbbell Triceps Extension', 'triceps', 'dumbbell'],
  ['Standing Biceps Cable Curl', 'biceps', 'cable'],
  ['Standing Biceps Stretch', 'biceps', 'other'],
  ['Standing Bradford Press', 'shoulders', 'barbell'],
  ['Standing Cable Chest Press', 'chest', 'cable'],
  ['Standing Cable Lift', 'core', 'cable'],
  ['Standing Cable Wood Chop', 'core', 'cable'],
  ['Standing Calf Raises', 'calves', 'machine'],
  ['Standing Concentration Curl', 'biceps', 'dumbbell'],
  ['Standing Dumbbell Calf Raise', 'calves', 'dumbbell'],
  ['Standing Dumbbell Press', 'shoulders', 'dumbbell'],
  ['Standing Dumbbell Reverse Curl', 'biceps', 'dumbbell'],
  ['Standing Dumbbell Straight-Arm Front Delt Raise Above Head', 'shoulders', 'dumbbell'],
  ['Standing Dumbbell Triceps Extension', 'triceps', 'dumbbell'],
  ['Standing Dumbbell Upright Row', 'traps', 'dumbbell'],
  ['Standing Elevated Quad Stretch', 'quads', 'other'],
  ['Standing Front Barbell Raise Over Head', 'shoulders', 'barbell'],
  ['Standing Gastrocnemius Calf Stretch', 'calves', 'other'],
  ['Standing Hamstring and Calf Stretch', 'hamstrings', 'other'],
  ['Standing Hip Circles', 'glutes', 'bodyweight'],
  ['Standing Hip Flexors', 'quads', 'other'],
  ['Standing Inner-Biceps Curl', 'biceps', 'dumbbell'],
  ['Standing Lateral Stretch', 'core', 'other'],
  ['Standing Leg Curl', 'hamstrings', 'machine'],
  ['Standing Long Jump', 'quads', 'bodyweight'],
  ['Standing Low-Pulley Deltoid Raise', 'shoulders', 'cable'],
  ['Standing Low-Pulley One-Arm Triceps Extension', 'triceps', 'cable'],
  ['Standing Military Press', 'shoulders', 'barbell'],
  ['Standing Olympic Plate Hand Squeeze', 'forearms', 'other'],
  ['Standing One-Arm Cable Curl', 'biceps', 'cable'],
  ['Standing One-Arm Dumbbell Curl Over Incline Bench', 'biceps', 'dumbbell'],
  ['Standing One-Arm Dumbbell Triceps Extension', 'triceps', 'dumbbell'],
  ['Standing Overhead Barbell Triceps Extension', 'triceps', 'barbell'],
  ['Standing Palm-In One-Arm Dumbbell Press', 'shoulders', 'dumbbell'],
  ['Standing Palms-In Dumbbell Press', 'shoulders', 'dumbbell'],
  ['Standing Palms-Up Barbell Behind The Back Wrist Curl', 'forearms', 'barbell'],
  ['Standing Pelvic Tilt', 'back', 'other'],
  ['Standing Rope Crunch', 'core', 'cable'],
  ['Standing Soleus And Achilles Stretch', 'calves', 'other'],
  ['Standing Toe Touches', 'hamstrings', 'other'],
  ['Standing Towel Triceps Extension', 'triceps', 'bodyweight'],
  ['Standing Two-Arm Overhead Throw', 'shoulders', 'other'],
  ['Star Jump', 'quads', 'bodyweight'],
  ['Step-up with Knee Raise', 'glutes', 'bodyweight'],
  ['Step Mill', 'quads', 'machine'],
  ['Stiff-Legged Barbell Deadlift', 'hamstrings', 'barbell'],
  ['Stiff-Legged Dumbbell Deadlift', 'hamstrings', 'dumbbell'],
  ['Stiff Leg Barbell Good Morning', 'back', 'barbell'],
  ['Stomach Vacuum', 'core', 'bodyweight'],
  ['Straight-Arm Dumbbell Pullover', 'chest', 'dumbbell'],
  ['Straight-Arm Pulldown', 'back', 'cable'],
  ['Straight Bar Bench Mid Rows', 'back', 'barbell'],
  ['Straight Raises on Incline Bench', 'shoulders', 'barbell'],
  ['Stride Jump Crossover', 'quads', 'other'],
  ['Sumo Deadlift', 'hamstrings', 'barbell'],
  ['Sumo Deadlift with Bands', 'hamstrings', 'barbell'],
  ['Sumo Deadlift with Chains', 'hamstrings', 'barbell'],
  ['Superman', 'back', 'bodyweight'],
  ['Supine Chest Throw', 'triceps', 'other'],
  ['Supine One-Arm Overhead Throw', 'core', 'other'],
  ['Supine Two-Arm Overhead Throw', 'core', 'other'],
  ['Suspended Fallout', 'core', 'other'],
  ['Suspended Push-Up', 'chest', 'other'],
  ['Suspended Reverse Crunch', 'core', 'other'],
  ['Suspended Row', 'back', 'other'],
  ['Suspended Split Squat', 'quads', 'other'],
  ['Svend Press', 'chest', 'other'],
  ['T-Bar Row with Handle', 'back', 'barbell'],
  ['Tate Press', 'triceps', 'dumbbell'],
  ['The Straddle', 'hamstrings', 'other'],
  ['Thigh Abductor', 'glutes', 'machine'],
  ['Thigh Adductor', 'glutes', 'machine'],
  ['Tire Flip', 'quads', 'other'],
  ['Toe Touchers', 'core', 'bodyweight'],
  ['Torso Rotation', 'core', 'other'],
  ['Trail Running/Walking', 'quads', 'other'],
  ['Trap Bar Deadlift', 'quads', 'other'],
  ['Tricep Dumbbell Kickback', 'triceps', 'dumbbell'],
  ['Tricep Side Stretch', 'triceps', 'other'],
  ['Triceps Overhead Extension with Rope', 'triceps', 'cable'],
  ['Triceps Pushdown', 'triceps', 'cable'],
  ['Triceps Pushdown - Rope Attachment', 'triceps', 'cable'],
  ['Triceps Pushdown - V-Bar Attachment', 'triceps', 'cable'],
  ['Triceps Stretch', 'triceps', 'other'],
  ['Tuck Crunch', 'core', 'bodyweight'],
  ['Two-Arm Dumbbell Preacher Curl', 'biceps', 'dumbbell'],
  ['Two-Arm Kettlebell Clean', 'shoulders', 'kettlebell'],
  ['Two-Arm Kettlebell Jerk', 'shoulders', 'kettlebell'],
  ['Two-Arm Kettlebell Military Press', 'shoulders', 'kettlebell'],
  ['Two-Arm Kettlebell Row', 'back', 'kettlebell'],
  ['Underhand Cable Pulldowns', 'back', 'cable'],
  ['Upper Back-Leg Grab', 'hamstrings', 'other'],
  ['Upper Back Stretch', 'back', 'other'],
  ['Upright Barbell Row', 'shoulders', 'barbell'],
  ['Upright Cable Row', 'traps', 'cable'],
  ['Upright Row - With Bands', 'traps', 'band'],
  ['Upward Stretch', 'shoulders', 'other'],
  ['V-Bar Pulldown', 'back', 'cable'],
  ['V-Bar Pullup', 'back', 'bodyweight'],
  ['Vertical Swing', 'hamstrings', 'dumbbell'],
  ['Walking, Treadmill', 'quads', 'machine'],
  ['Weighted Ball Hyperextension', 'back', 'other'],
  ['Weighted Ball Side Bend', 'core', 'other'],
  ['Weighted Bench Dip', 'triceps', 'other'],
  ['Weighted Crunches', 'core', 'other'],
  ['Weighted Jump Squat', 'quads', 'barbell'],
  ['Weighted Pull Ups', 'back', 'other'],
  ['Weighted Sissy Squat', 'quads', 'barbell'],
  ['Weighted Sit-Ups - With Bands', 'core', 'other'],
  ['Weighted Squat', 'quads', 'other'],
  ['Wide-Grip Barbell Bench Press', 'chest', 'barbell'],
  ['Wide-Grip Decline Barbell Bench Press', 'chest', 'barbell'],
  ['Wide-Grip Decline Barbell Pullover', 'chest', 'barbell'],
  ['Wide-Grip Lat Pulldown', 'back', 'cable'],
  ['Wide-Grip Pulldown Behind The Neck', 'back', 'cable'],
  ['Wide-Grip Rear Pull-Up', 'back', 'bodyweight'],
  ['Wide-Grip Standing Barbell Curl', 'biceps', 'barbell'],
  ['Wide Stance Barbell Squat', 'quads', 'barbell'],
  ['Wide Stance Stiff Legs', 'hamstrings', 'barbell'],
  ['Wind Sprints', 'core', 'bodyweight'],
  ['Windmills', 'glutes', 'other'],
  ['World\'s Greatest Stretch', 'hamstrings', 'other'],
  ['Wrist Circles', 'forearms', 'bodyweight'],
  ['Wrist Roller', 'forearms', 'other'],
  ['Wrist Rotations with Straight Bar', 'forearms', 'barbell'],
  ['Yoke Walk', 'quads', 'other'],
  ['Zercher Squats', 'quads', 'barbell'],
  ['Zottman Curl', 'biceps', 'dumbbell'],
  ['Zottman Preacher Curl', 'biceps', 'dumbbell'],
];
