// Vidéos démo Google Drive par exercice.
// Clé normalisée du nom d'exercice -> URL de la vidéo (ou vide).

const RAW_MEDIA: readonly (readonly [string, string])[] = [
  ["abfundamental", "https://drive.google.com/file/d/1MVoDMhRgYIHZOv_Qr_OGLaP6JDXzfDpc/view"],
  ["backfundamental", "https://drive.google.com/file/d/1-jzdFQfDJDvsXB4xiUdI-OOYURgDjhdT/view"],
  ["bodylinefundamental", "https://drive.google.com/file/d/1-DhTEptQUR47H6BvPkA14Ye1uVvR0i_C/view"],
  ["dipsfundamental", "https://drive.google.com/file/d/1RA7HUGzV6MqOuyanHW9N1XHQzF1N9BE-/view"],
  ["handstandfundamental", "https://drive.google.com/file/d/1J6YSRQzMPzG96NbPIC8tTGDKrmDqc0e8/view"],
  ["pullupfundamental", "https://drive.google.com/file/d/1__SuQGhe_mw48W1Yc7suh4B2134441oq/view"],
  ["pushupfundamental", "https://drive.google.com/file/d/1vICwmMXmPHUvcbpVvCJVcZZ5b6xYs9YW/view"],
  ["sidefundamental", "https://drive.google.com/file/d/1x0uxNgtzw5ZUIyhQc4lFd8Bzm1DYb-l3/view"],
  ["squatfundamental", "https://drive.google.com/file/d/1iFNcLKMuuYC25ZX5xzKkAk0kyTkZTE_U/view"],
  ["bearwalk", "https://drive.google.com/file/d/1AMlr1AlEnUlA8Hmq6zPL3j-bFJfMtNWu/view"],
  ["calfraises", "https://drive.google.com/file/d/1XZQpggvAMOrtBe9lb1wyxJV3rgWO47eT/view"],
  ["downwarddog", "https://drive.google.com/file/d/1MPuCltb8uQSEbQ439ZsPx95G4JiJmSFC/view"],
  ["forwardroll", "https://drive.google.com/file/d/1m7szi9A3JhERic-K2FDgLzlHMXYQ_cl9/view"],
  ["backplank", "https://drive.google.com/file/d/16aiQdSaNKhTfyTPEPFfj2p2hPhZDQ4Sk/view"],
  ["backwardroll", "https://drive.google.com/file/d/1qQ-CXVlnk1knMuwbQuqztQWZnhe_Dnm5/view"],
  ["bridge", "https://drive.google.com/file/d/1QpuwceAtTZSk_Y4nTMU-kPnWWWXmFrNj/view"],
  ["cartwheel", "https://drive.google.com/file/d/1mKgjXmPEoH98YZhZ_5NA6QR3HiBS65fc/view"],
  ["cartwheelwithonelegbent", "https://drive.google.com/file/d/1-W05Zie6D91pFMFKtkvn0WWD1mYf7mkw/view"],
  ["elevatedbridgebridgeprep", "https://drive.google.com/file/d/1NOitW_uX-NPW7j2RBobkGse0HDmhdLxj/view"],
  ["forearmstandstage1wall", "https://drive.google.com/file/d/12tfw69Ab-sLtdUehm_m0XSajEls6mN-P/view"],
  ["forearmstandstage2freestanding", "https://drive.google.com/file/d/19ty4ZL2LHOQ0h69szl_2WREzL1G8fbb9/view"],
  ["forwarddips", "https://drive.google.com/file/d/1ZwN3xQgFnZI0H5Yvhw7YxkUIsbf45ufJ/view"],
  ["forwardrollcartwheel", "https://drive.google.com/file/d/1unDpa0brzRBRC0bxyHGCSyNFpz-sug_X/view"],
  ["hanginglegraises", "https://drive.google.com/file/d/1pTXr9YrRt6kI3s3-to8fangqFgJWq3ym/view"],
  ["jumpinggrasshopperpullup", "https://drive.google.com/file/d/11YdJc6DVkFpgSfdcpMTFLNzdKT75rppg/view"],
  ["kneebentdips", "https://drive.google.com/file/d/1kd-ifuD1n_IS54ZCvH242yG7WW1kIiSQ/view"],
  ["planchestage1tuckhold", "https://drive.google.com/file/d/1EmYwafgyZwLDNsxBO_-nUfiP0L-pzYjd/view"],
  ["wallheadstand", "https://drive.google.com/file/d/10EgXeZC0GC4Q6wzPqxfjPr1DRC97tZ6f/view"],
  ["advancedobliques", "https://drive.google.com/file/d/1mSBEocCBSb8geZZmWGtTaB3ihbyoozrV/view"],
  ["backlever", "https://drive.google.com/file/d/1y-Y4wtZsHmuGU2hnahy2LuykxR-rCnUN/view"],
  ["bridgehipsitandextend", "https://drive.google.com/file/d/1yddZidbdE44E5k8pmVcJuJi_z_GtvvyP/view"],
  ["bridgepushups", "https://drive.google.com/file/d/1uu66vuPpjAIJ3Bhikis4GILHPeCTm9qz/view"],
  ["cartwheelwithoppositehand", "https://drive.google.com/file/d/14f0JqzrAwahSXLhvg8CA64MnOwOzYlYb/view"],
  ["cartwheelwithoppositeleg", "https://drive.google.com/file/d/12Yig9w2z-A0-F83IPvBIfu-QHQ9BgzIm/view"],
  ["declineonearmpushup", "https://drive.google.com/file/d/1e97LwnlsZ-9SexjniaRUmCLwPS7uJSGh/view"],
  ["diamondbridgeadvancedbridge", "https://drive.google.com/file/d/1n_UbT-8uXArY1uBlYrVwBoopQDcQngCF/view"],
  ["freestandinghandstand", "https://drive.google.com/file/d/1K4TC4DZPFJF9NGupblZ-mQfY-S_h3cjU/view"],
  ["freestandinghandstandpushup", "https://drive.google.com/file/d/1YnuexFBI8SCUa0hSN78mYrhKCKcQsRrU/view"],
  ["frontlever", "https://drive.google.com/file/d/1rM5Xg3EvkfPk7pda28Z05OQy1ApKObmR/view"],
  ["handstandpirouettes", "https://drive.google.com/file/d/1rITN0sdmicKSSomY8uldOzTwJCsmJ-3E/view"],
  ["handstandshouldertaps", "https://drive.google.com/file/d/1sEHrv-3R5YUK81gsttTY2szubZh18cyd/view"],
  ["handstandwalk", "https://drive.google.com/file/d/11fZu_ebhre-WjBX3PI-AgSW5rx12b66J/view"],
  ["kippingbarmuscleup", "https://drive.google.com/file/d/1pGslBEGYy32ZXR-uBMQkQmMkrViPYOXC/view"],
  ["kippingringmuscleup", "https://drive.google.com/file/d/1E4SCrSHBZuksAewnCVV7XlD1mVzmtQLo/view"],
  ["lsitdips", "https://drive.google.com/file/d/1UZma6ZHjRQmwDMsOAicfHKTb7rE1vHXm/view"],
  ["muscleupintro", "https://drive.google.com/file/d/1w8tLeohCg_URbZOBfQjJAsWCIeRIUTkB/view"],
  ["onearmpullup", "https://drive.google.com/file/d/1z2Fl1nUkn04La9tkMH50nI-OfkSWB-oC/view"],
  ["onearmpushup", "https://drive.google.com/file/d/1tjWMO8dXNXwhbWY2D7KSBm97Y_BmSDrj/view"],
  ["onearmstraightlegvraise", "https://drive.google.com/file/d/1rru_JSqSxzCvblzaD7asr_z70pXNPEG6/view"],
  ["pistolsquat", "https://drive.google.com/file/d/1vQw3bIoLoRqdJlqx_-9mQFgfmSe8MY0X/view"],
  ["planchestage2fullplanchehold", "https://drive.google.com/file/d/1BfViIiJSSv5BqfAJy2dTAVoYTxlh3ifL/view"],
  ["presshandstand", "https://drive.google.com/file/d/1YEfFsMQO6L_revfAp29ejG_9Giq6ZSYn/view"],
  ["ringdips", "https://drive.google.com/file/d/1bnSIHDjTuq-y6owmm1wDL0GiKU0zyjth/view"],
  ["sideplank", "https://drive.google.com/file/d/1vDZI0Au7Z8y-w0u2nVOYFyWJBNR95wt2/view"],
  ["strictringmuscleup", "https://drive.google.com/file/d/13fawit2Cs4QCPwfrKs-1C6a2zWP8Qvcr/view"],
  ["wallhandstandpushup", "https://drive.google.com/file/d/1QSoV0E7EYtx7TVX03kII4pMc8wznkc2y/view"],
];

export function getSkillVideo(key: string): string {
  const found = RAW_MEDIA.find(([k]) => k === key);
  return found ? found[1] : '';
}
