#!/usr/bin/env python3
"""Match nos exercices français vers free-exercise-db (domaine public)."""
import json, re, unicodedata
from difflib import SequenceMatcher

# --- Chargement de notre seed ---
def load_seed():
    src = open('src/db/seed-exercises.ts').read()
    body = src.split('=', 1)[1]
    pairs = re.findall(r"\['([^']+)',\s*'(\w+)',\s*'(\w+)'\]", body)
    return [p[0] for p in pairs]

# --- Traduction FR -> EN par phrases (les plus longues d'abord) ---
PHRASES = [
    ("développé couché prise serrée", "close-grip bench press"),
    ("développé couché barre", "barbell bench press"),
    ("développé couché haltères", "dumbbell bench press"),
    ("développé couché", "bench press"),
    ("développé incliné barre", "incline barbell bench press"),
    ("développé incliné haltères", "incline dumbbell bench press"),
    ("développé incliné", "incline bench press"),
    ("développé décliné", "decline bench press"),
    ("développé militaire debout", "standing military press"),
    ("développé militaire assis", "seated military press"),
    ("développé militaire", "military press"),
    ("développé haltères assis", "seated dumbbell press"),
    ("développé haltères debout", "dumbbell standing overhead press"),
    ("développé haltères", "dumbbell press"),
    ("développé machine épaules", "machine shoulder press"),
    ("développé machine couché", "machine chest press"),
    ("développé machine incliné", "incline machine chest press"),
    ("développé machine", "machine chest press"),
    ("développé smith machine", "smith machine bench press"),
    ("développé incliné smith machine", "smith machine incline bench press"),
    ("développé arnold", "arnold press"),
    ("développé", "press"),
    ("presse arnold", "arnold press"),
    ("press landmine", "landmine press"),
    ("landmine shoulder press", "landmine shoulder press"),
    ("floor press barre", "barbell floor press"),
    ("floor press haltères", "dumbbell floor press"),
    ("push press", "push press"),
    ("z-press", "z press"),
    ("guillotine press", "guillotine press"),
    ("svend press", "svend press"),
    ("rowing pendlay", "pendlay row"),
    ("rowing t-bar", "t-bar row"),
    ("rowing barre", "barbell row"),
    ("rowing buste soutenu haltères", "chest supported dumbbell row"),
    ("rowing banc incliné haltères", "incline dumbbell row"),
    ("rowing haltère unilatéral", "single arm dumbbell row"),
    ("rowing haltères bilatéral", "two arm dumbbell row"),
    ("rowing haltères prise neutre haut", "dumbbell shrug"),
    ("rowing haltères", "dumbbell row"),
    ("rowing machine unilatéral", "single arm machine row"),
    ("rowing machine prise neutre", "neutral grip machine row"),
    ("rowing machine", "machine row"),
    ("rowing assis poulie", "seated cable row"),
    ("rowing poulie prise serrée", "close grip cable row"),
    ("rowing poulie prise large", "wide grip cable row"),
    ("rowing poulie", "cable row"),
    ("rowing menton barre", "barbell upright row"),
    ("rowing menton haltères", "dumbbell upright row"),
    ("rowing menton poulie", "cable upright row"),
    ("rowing menton", "upright row"),
    ("rowing inversé", "inverted row"),
    ("rowing suspension", "suspension row"),
    ("meadows row", "meadows row"),
    ("kroc row", "kroc row"),
    ("renegade row", "renegade row"),
    ("seal row", "seal row"),
    ("rowing", "row"),
    ("tirage vertical poitrine devant", "lat pulldown"),
    ("tirage vertical prise serrée", "close grip lat pulldown"),
    ("tirage vertical prise inversée", "reverse grip lat pulldown"),
    ("tirage vertical prise large", "wide grip lat pulldown"),
    ("tirage vertical prise neutre", "neutral grip lat pulldown"),
    ("tirage vertical unilatéral", "single arm lat pulldown"),
    ("tirage vertical", "lat pulldown"),
    ("straight-arm pulldown", "straight arm pulldown"),
    ("pullover poulie bras tendus", "straight arm pulldown"),
    ("pull-over poulie", "cable pullover"),
    ("pull-over haltère", "dumbbell pullover"),
    ("tractions pronation", "pull up"),
    ("tractions supination", "chin up"),
    ("tractions prise neutre", "neutral grip pull up"),
    ("tractions prise large", "wide grip pull up"),
    ("tractions lestées", "weighted pull up"),
    ("tractions assistées élastique", "band assisted pull up"),
    ("tractions machine assistée", "assisted pull up machine"),
    ("tractions", "pull up"),
    ("chin-up biceps", "chin up"),
    ("pompes prise rapprochée élastique", "band push up"),
    ("pompes prise serrée", "close grip push up"),
    ("pompes lestées", "weighted push up"),
    ("pompes déficit", "deficit push up"),
    ("pompes suspension", "suspension push up"),
    ("pompes déclinées", "decline push up"),
    ("pompes inclinées", "incline push up"),
    ("pompes larges", "wide grip push up"),
    ("pompes diamant", "diamond push up"),
    ("pompes", "push up"),
    ("dips lestés buste penché", "chest dip"),
    ("dips machine buste penché", "machine chest dip"),
    ("dips triceps", "triceps dip"),
    ("bench dips", "bench dip"),
    ("dips", "dip"),
    ("écarté à la poulie", "cable chest fly"),
    ("écarté poulie basse", "low cable chest fly"),
    ("écarté poulie haute", "high cable chest fly"),
    ("écarté incliné haltères", "incline dumbbell fly"),
    ("écarté haltères", "dumbbell fly"),
    ("écarté", "fly"),
    ("pec deck", "pec deck"),
    ("reverse pec deck", "reverse pec deck"),
    ("machine à pecs converging", "lever chest fly"),
    ("chest fly élastique", "band chest fly"),
    ("extension nu barre (skull crusher)", "skull crusher"),
    ("extension nu ez", "ez bar skull crusher"),
    ("extension nu incliné haltères", "incline dumbbell skull crusher"),
    ("extension nu haltères couché", "dumbbell lying triceps extension"),
    ("extension nu haltères", "dumbbell lying triceps extension"),
    ("extension nu", "lying triceps extension"),
    ("barre au front poulie allongé", "lying cable triceps extension"),
    ("extension verticale poulie corde", "cable overhead triceps extension"),
    ("extension verticale poulie barre", "cable overhead triceps extension bar"),
    ("extension verticale haltère deux mains", "seated overhead dumbbell triceps extension"),
    ("extension verticale haltère unilatéral", "single arm overhead dumbbell triceps extension"),
    ("extension verticale", "overhead triceps extension"),
    ("french press assis", "seated french press"),
    ("extension triceps élastique", "band triceps extension"),
    ("pushdown poulie", "cable triceps pushdown"),
    ("pushdown corde", "rope cable triceps pushdown"),
    ("pushdown unilatéral", "single arm cable pushdown"),
    ("pushdown", "triceps pushdown"),
    ("kickback poulie cheville", "cable glute kickback"),
    ("kickback poulie", "cable kickback"),
    ("kickback haltère", "dumbbell kickback"),
    ("jm press", "jm press"),
    ("close-grip push-up lesté", "weighted close grip push up"),
    ("curl barre ez", "ez bar curl"),
    ("curl pupitre barre", "barbell preacher curl"),
    ("curl pupitre haltères", "dumbbell preacher curl"),
    ("curl barre", "barbell curl"),
    ("curl haltères debout", "dumbbell bicep curl"),
    ("curl marteau croisé", "cross body hammer curl"),
    ("curl marteau", "hammer curl"),
    ("curl incliné haltères", "incline dumbbell curl"),
    ("curl concentration", "concentration curl"),
    ("curl spider", "spider curl"),
    ("curl poulie basse", "low cable curl"),
    ("curl poulie unilatéral", "single arm cable curl"),
    ("bayesian cable curl", "bayesian cable curl"),
    ("curl corde", "rope cable curl"),
    ("curl prise inversée", "reverse curl"),
    ("drag curl", "drag curl"),
    ("zottman curl", "zottman curl"),
    ("curl 21s", "21 curl"),
    ("curl élastique", "band curl"),
    ("curl", "curl"),
    ("wrist curl barre", "barbell wrist curl"),
    ("wrist curl haltères", "dumbbell wrist curl"),
    ("reverse wrist curl", "reverse wrist curl"),
    ("reverse curl barre ez", "ez reverse curl"),
    ("farmer walk", "farmers walk"),
    ("farmer carry", "farmers walk"),
    ("suitcase carry", "suitcase carry"),
    ("dead hang", "dead hang"),
    ("plate pinch hold", "plate pinch"),
    ("wrist roller", "wrist roller"),
    ("shrugs barre", "barbell shrug"),
    ("shrugs haltères", "dumbbell shrug"),
    ("shrugs machine", "machine shrug"),
    ("shrugs poulie", "cable shrug"),
    ("shrugs trap bar", "trap bar shrug"),
    ("shrugs", "shoulder shrug"),
    ("y-t-w raises au banc", "ytw raise"),
    ("cuban press", "cuban press"),
    ("overhead carry haltère", "overhead carry"),
    ("élévations latérales haltères", "dumbbell lateral raise"),
    ("élévations latérales poulie", "cable lateral raise"),
    ("élévations latérales machine", "machine lateral raise"),
    ("élévations latérales unilatéral poulie", "single arm cable lateral raise"),
    ("élévations latérales élastique", "band lateral raise"),
    ("leaning lateral raise", "leaning lateral raise"),
    ("élévations latérales", "lateral raise"),
    ("élévations frontales haltères", "dumbbell front raise"),
    ("élévations frontales disque", "plate front raise"),
    ("élévations frontales poulie", "cable front raise"),
    ("élévations frontales", "front raise"),
    ("oiseau haltères", "dumbbell rear lateral raise"),
    ("oiseau poulie", "cable rear lateral raise"),
    ("oiseau", "rear delt raise"),
    ("face pull corde", "rope face pull"),
    ("face pull barre ez", "ez bar face pull"),
    ("face pull", "face pull"),
    ("handstand push-up", "handstand push up"),
    ("pike push-up", "pike push up"),
    ("soulevé de terre roumain", "romanian deadlift"),
    ("soulevé de terre sumo", "sumo deadlift"),
    ("soulevé de terre jambes tendues haltères", "stiff legged deadlift dumbbell"),
    ("soulevé de terre jambes tendues", "stiff legged deadlift"),
    ("soulevé de terre unilatéral haltère", "single leg romanian deadlift"),
    ("soulevé de terre", "deadlift"),
    ("stiff leg deadlift trap bar", "trap bar stiff legged deadlift"),
    ("trap bar deadlift", "trap bar deadlift"),
    ("rack pull", "rack pull"),
    ("good morning barre", "good morning"),
    ("good morning", "good morning"),
    ("hyperextensions lestées", "weighted back extension"),
    ("hyperextensions", "back extension"),
    ("back extension focus fessiers", "glute back extension"),
    ("squat barre dos", "barbell back squat"),
    ("squat barre devant", "barbell front squat"),
    ("squat box", "box squat"),
    ("squat pause", "pause squat"),
    ("squat goblet", "goblet squat"),
    ("squat goblet press", "goblet squat press"),
    ("squat sumo haltère", "dumbbell sumo squat"),
    ("squat sumo barre focus fessiers", "barbell sumo squat"),
    ("squat bulgare haltères", "bulgarian split squat dumbbell"),
    ("squat bulgare barre", "barbell bulgarian split squat"),
    ("squat libre poids du corps", "bodyweight squat"),
    ("squat sauté", "jump squat"),
    ("squat élastique", "band squat"),
    ("sissy squat", "sissy squat"),
    ("belt squat", "belt squat"),
    ("pistol squat", "pistol squat"),
    ("wall sit", "wall sit"),
    ("curtsy lunge", "curtsy lunge"),
    ("leg press calf raise", "leg press calf raise"),
    ("leg press", "leg press"),
    ("hack squat machine", "hack squat"),
    ("hack squat barre", "barbell hack squat"),
    ("hack squat", "hack squat"),
    ("extension quadriceps machine", "leg extension"),
    ("vmo squat sissy machine", "machine sissy squat"),
    ("fentes marchées haltères", "walking lunge dumbbell"),
    ("fentes avant", "forward lunge"),
    ("fentes arrière haltères", "reverse lunge dumbbell"),
    ("fentes latérales", "side lunge"),
    ("fentes", "lunge"),
    ("step-up sur banc haltères", "dumbbell step up"),
    ("step-up latéral", "lateral step up"),
    ("step-up", "step up"),
    ("leg curl allongé", "lying leg curl"),
    ("leg curl assis", "seated leg curl"),
    ("leg curl unilatéral", "single leg curl"),
    ("leg curl élastique", "band leg curl"),
    ("leg curl", "leg curl"),
    ("nordic hamstring curl", "nordic curl"),
    ("glute ham raise", "glute ham raise"),
    ("slider leg curl", "slider leg curl"),
    ("hip thrust barre", "barbell hip thrust"),
    ("hip thrust machine", "machine hip thrust"),
    ("hip thrust une jambe", "single leg hip thrust"),
    ("hip thrust", "hip thrust"),
    ("pont fessier au sol", "glute bridge"),
    ("pont fessier lesté", "weighted glute bridge"),
    ("pont fessier", "glute bridge"),
    ("abduction machine", "machine hip abduction"),
    ("adduction machine", "machine hip adduction"),
    ("abduction élastique debout", "band hip abduction"),
    ("fire hydrant élastique", "fire hydrant"),
    ("donkey kick élastique", "donkey kick"),
    ("kickback machine", "machine glute kickback"),
    ("mollets debout barre", "standing calf raise barbell"),
    ("mollets debout machine", "standing calf raise machine"),
    ("mollets debout unilatéral haltère", "single leg standing calf raise"),
    ("mollets assis machine", "seated calf raise"),
    ("mollets presse à cuisses", "leg press calf raise"),
    ("mollets donkey machine", "donkey calf raise"),
    ("mollets hack squat", "hack squat calf raise"),
    ("mollets smith machine", "smith machine calf raise"),
    ("mollets au poids du corps", "bodyweight calf raise"),
    ("marche sur la pointe des pieds lestée", "weighted toe walk"),
    ("mollets", "calf raise"),
    ("marche sur la pointe", "toe walk"),
    ("clean and jerk", "clean and jerk"),
    ("arraché (snatch)", "snatch"),
    ("power clean", "power clean"),
    ("hang clean", "hang clean"),
    ("hang snatch", "hang snatch"),
    ("thruster barre", "barbell thruster"),
    ("thruster haltères", "dumbbell thruster"),
    ("clean and press haltères", "dumbbell clean and press"),
    ("clean and press", "clean and press"),
    ("turkish get-up", "turkish get up"),
    ("kettlebell swing", "kettlebell swing"),
    ("kettlebell snatch", "kettlebell snatch"),
    ("kettlebell clean and press", "kettlebell clean and press"),
    ("burpees avec saut box", "box jump burpee"),
    ("burpees", "burpee"),
    ("devil press", "devil press"),
    ("man maker", "man maker"),
    ("wall balls", "wall ball"),
    ("sandbag carry", "sandbag carry"),
    ("yoke carry", "yoke carry"),
    ("sled push", "sled push"),
    ("sled pull", "sled pull"),
    ("battle ropes", "battle rope wave"),
    ("box jump", "box jump"),
    ("broad jump", "broad jump"),
    ("med ball slam", "medicine ball slam"),
    ("gainage planche", "plank"),
    ("planché", "plank"),
    ("planche lestée", "weighted plank"),
    ("planche latérale", "side plank"),
    ("relevés de jambes suspendu", "hanging leg raise"),
    ("relevés de genoux suspendu", "hanging knee raise"),
    ("toes to bar", "toes to bar"),
    ("crunch poulie à genoux", "cable crunch"),
    ("crunch bicyclette", "bicycle crunch"),
    ("crunch machine", "machine crunch"),
    ("crunch au sol", "crunch"),
    ("sit-up", "sit up"),
    ("russian twist", "russian twist"),
    ("ab wheel rollout", "ab roller"),
    ("rollout genoux", "kneeling rollout"),
    ("mountain climbers", "mountain climber"),
    ("v-up", "v up"),
    ("hollow body hold", "hollow hold"),
    ("dead bug", "dead bug"),
    ("bird dog", "bird dog"),
    ("relevés de jambes au sol", "lying leg raise"),
    ("flutter kicks", "flutter kick"),
    ("scissor kicks", "scissor kick"),
    ("woodchopper poulie", "cable wood chop"),
    ("pallof press", "pallof press"),
    ("side bend haltère", "dumbbell side bend"),
    ("leg raise banc romain", "captains chair leg raise"),
    ("dragon flag", "dragon flag"),
    ("course à pied extérieure", "running"),
    ("tapis de course", "treadmill"),
    ("vélo d'appartement", "stationary bike"),
    ("vélo elliptique", "elliptical machine"),
    ("rameur", "row machine"),
    ("air bike", "air bike"),
    ("escalier / stepmill", "stepmill"),
    ("corde à sauter", "jump rope"),
    ("natation", "swimming"),
    ("randonnée", "hiking"),
    ("marche rapide", "walking"),
    ("stair sprint", "stair sprint"),
    ("assault bike intervalles", "air bike sprint"),
    ("ski erg", "ski erg"),
]

def norm(s):
    s = unicodedata.normalize('NFD', s.lower())
    return ''.join(c for c in s if not unicodedata.combining(c))

def translate(fr):
    n = norm(fr)
    for fr_phrase, en in PHRASES:
        if norm(fr_phrase) in n:
            return en
    return None

def tokens(s):
    return set(re.findall(r"[a-z0-9]+", norm(s)))

db = json.load(open('/tmp/fedb.json'))
for e in db:
    e['_tok'] = tokens(e['name'])
    e['_str'] = norm(e['name'])
img_by_name = {e['name']: (e['images'][0] if e['images'] else None) for e in db}

def best_match(fr):
    tr = translate(fr)
    ft = tokens(fr) | (tokens(tr) if tr else set())
    best, bs = None, 0.0
    for e in db:
        inter = len(ft & e['_tok'])
        union = len(ft | e['_tok'])
        jac = inter / union if union else 0
        seq = SequenceMatcher(None, norm(tr or fr), e['_str']).ratio()
        # le ratio de séquence ne compte que s'il y a au moins un mot commun
        score = max(jac, seq * 0.85) if inter > 0 else jac
        if score > bs:
            bs, best = score, e
    return best, bs

MANUAL = {
    "Pec deck": "Butterfly",
    "Reverse pec deck": "Cable Rear Delt Fly",
    "Curtsy lunge": "Crossover Reverse Lunge",
    "Turkish get-up": "Kettlebell Turkish Get-Up (Lunge style)",
    "Fire hydrant élastique": "Rear Leg Raises",
    "Donkey kick élastique": "Rear Leg Raises",
    "Course à pied extérieure": "Trail Running/Walking",
    "Randonnée": "Trail Running/Walking",
    "Marche rapide": "Walking, Treadmill",
    "Corde à sauter": "Fast Skipping",
    "Yoke carry": "Yoke Walk",
    "Wrist curl barre": "Palms-Up Barbell Wrist Curl Over A Bench",
    "Wrist curl haltères": "Palms-Up Dumbbell Wrist Curl Over A Bench",
    "Reverse wrist curl": "Seated Palms-Down Barbell Wrist Curl",
    "Curl 21s": "Barbell Curl",
    "Fentes avant": "Dumbbell Lunges",
    "Fentes arrière haltères": "Dumbbell Rear Lunge",
    "Fentes latérales": "Barbell Side Split Squat",
    "Leg curl allongé": "Lying Leg Curls",
    "Leg curl assis": "Seated Leg Curl",
    "Leg curl unilatéral": "Standing Leg Curl",
    "Slider leg curl": "Platform Hamstring Slides",
    "Hyperextensions": "Hyperextensions (Back Extensions)",
    "Back extension focus fessiers": "Hyperextensions (Back Extensions)",
    "Dips lestés buste penché": "Dips - Chest Version",
    "Dips machine buste penché": "Dip Machine",
    "Dips triceps": "Dips - Triceps Version",
    "Meadows row": "Bent Over One-Arm Long Bar Row",
    "Kroc row": "Bent Over One-Arm Long Bar Row",
    "Rowing Pendlay": "Bent Over Barbell Row",
    "Rowing menton poulie": "Upright Cable Row",
    "Tractions pronation": "Pullups",
    "Tractions prise neutre": "Rocky Pull-Ups/Pulldowns",
    "Pompes prise serrée": "Close-Grip Push-Up off of a Dumbbell",
    "Pompes diamant": "Close-Grip Push-Up off of a Dumbbell",
    "Close-grip push-up lesté": "Incline Push-Up Close-Grip",
    "Pike push-up": "Handstand Push-Ups",
    "V-up": "Jackknife Sit-Up",
    "Wall sit": "Chair Squat",
    "Squat pause": "Barbell Squat To A Bench",
    "Sumo squat barre focus fessiers": "Barbell Side Split Squat",
    "Burpees avec saut box": "Box Jump (Multiple Response)",
    "Stair sprint": "Bench Sprint",
    "Tapis de course": "Running, Treadmill",
    "Leg raise banc romain": "Knee/Hip Raise On Parallel Bars",
    "Écarté poulie basse": "Low Cable Crossover",
    "Écarté poulie haute": "Single-Arm Cable Crossover",
    "Écarté à la poulie": "Cable Crossover",
    "Y-T-W raises au banc": "Bent Over Dumbbell Rear Delt Raise With Head On Bench",
    "Chest fly élastique": "Bodyweight Flyes",
    "Leg curl élastique": None,
    "Devil press": None,
    "Hip thrust une jambe": None,
    "Pull-over poulie": "Rope Straight-Arm Pulldown",
}

# Pas d'image disponible dans la base -> silhouette de secours
NO_IMAGE = {
    "Hollow body hold", "Bird dog", "Dragon flag", "Burpees", "Man maker",
    "Escalier / stepmill", "Natation", "Ski erg", "Toes to bar", "Nordic hamstring curl",
    "Wall balls", "Broad jump", "Pompes larges", "Pompes déficit",
    "Pompes prise rapprochée élastique", "Rowing machine unilatéral",
    "Rowing machine prise neutre", "Rowing poulie prise large",
    "Marche sur la pointe des pieds lestée",
}

seed = load_seed()
matched, unmatched = {}, []
for fr in seed:
    if fr in NO_IMAGE:
        continue
    if fr in MANUAL:
        target = MANUAL[fr]
        img = img_by_name.get(target) if target else None
        if img:
            matched[fr] = (MANUAL[fr], img, 1.0)
        else:
            unmatched.append((fr, MANUAL[fr], 'introuvable'))
        continue
    m, s = best_match(fr)
    if m and s >= 0.45:
        matched[fr] = (m['name'], m['images'][0] if m['images'] else None, round(s, 2))
    else:
        unmatched.append((fr, m['name'] if m else '-', round(s, 2)))

json.dump(matched, open('/tmp/matches.json', 'w'), ensure_ascii=False, indent=1)
print(f"matchés: {len(matched)} / {len(seed)}")
print("\n--- NON MATCHÉS ---")
for fr, en, s in unmatched:
    print(f"{fr}  ->  {en} ({s})")
